### ISSUE TITLE
Client crash with creative menu

### ISSUE THREAD

**Issue by BedrockLegends** [baileyholl/Ars-Nouveau#100]
[crash-2020-12-18_15.11.36-client.txt](https://github.com/baileyholl/Ars-Nouveau/files/5718063/crash-2020-12-18_15.11.36-client.txt)

[debug.log](https://github.com/baileyholl/Ars-Nouveau/files/5718070/debug.log)
[latest.log](https://github.com/baileyholl/Ars-Nouveau/files/5718071/latest.log)

**Comment by BedrockLegends** [comment]
All I did was search wands

**Comment by baileyholl** [comment]
Should be fixed next version, probably released today.

**Comment by baileyholl** [comment]
https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3143328
