### ISSUE TITLE
Inability to move hot bar slots

### ISSUE THREAD

**Issue by Humber89** [baileyholl/Ars-Nouveau#1004]
When I use a spell I am unable to change hotbar slots until I fully disconnect from my server

**Comment by Jakarius** [comment]
Also occurs to me on 1.19.2-3.15.1 (as part of FTB Direwolf20 for 1.19). After casting some spells (not always the first spell, but within the first few, and occurring on different spells) the number keys stop working to change the hotbar selection. The scroll wheel also stops working. The number keys actually do work if you hold them down for a second or so. Rebinding the hotbar selection key to a non-number key allows it to work normally.

**Comment by baileyholl** [comment]
Hello,
This is a bug with supplementaries quiver. You need to unbind the keybind or resolve the conflict. It captures the hotbar even if you do not have it equipped.
