### ISSUE TITLE
Feedback: Leap allowing flight is OP

### ISSUE THREAD

**Issue by Aceplante2** [baileyholl/Ars-Nouveau#1006]
especially as a level 2 spell EDIT ITS LEVEL 1???. Leap should do just that; a powerful leap upward but only when on the ground. Otherwise, without checking to make sure the player is on the ground, it can be used repeatedly in midair allowing easy indefinite flight. Perhaps a new level 3 spell called "launch" can be added that does not have this check and therefore can be used for indefinite flight? unless the glide spell already does that. I dont know because I haven't even been to the end yet. And I dont need to since the leap spell is currently better than the elytra as it does not waste gunpowder/rockets.

And if you do add a new spell like that, make it require a chorus fruit or something so flight, whether through the vanilla elytra or one of your spells, is at least post end.

With this change, the leap spell would still be very useful for travelling midgame. I imagine leap+amplifly plus delayed slow falling to negate fall damage or something would be the meta?

Edit2: it has come to my attention that launch does basically the same thing, but slightly less accurate, so same for that

**Comment by Aceplante2** [comment]
oh boo hoo, I guess people dont like how this would actually make things more fair, which I suppose is not why most people are downloading this mod.

**Comment by baileyholl** [comment]
Leap may have changes in the future but nothing certain at this time. You can adjust the casting cost or tier in the configs to make it prohibitive for endless flight.
