### ISSUE TITLE
[1.18.2] Turning bound scripts back into charms

### ISSUE THREAD

**Issue by KirikaAetheria** [baileyholl/Ars-Nouveau#1007]
I couldn't find any information on how to turn a bound script back into a regular charm, neither on discord nor the ingame manual. If it doesn't exist, would you consider implementing this? Maybe allowing the bound script to be used as a regular charm when you already have the famliar unlocked, or even just a simple crafting table recipe to turn a bound script back into a normal charm

I've accidentally had little helpers run into the ritual area more than once, and ended up with unusable leftover scripts, so it would be pretty helpful if there was a way to revert the process too

**Comment by baileyholl** [comment]
They cannot be converted, it is intended to be a permanent unlock.
