### ISSUE TITLE
[1.19.2] Dupe glitch with Sophisticated Storage

### ISSUE THREAD

**Issue by katubug** [baileyholl/Ars-Nouveau#1016]
Hi! I have a nice weird edge case for you today.

Ars Nouveau 3.17.3
Forge 43.2.9
Sophisticated Core 0.5.71.319
Sophisticated Storage 0.8.28.453

I am in creative in a singleplayer testing world. I have a Sophisticated Barrel which has the "Filter Upgrade" from soph applied. I have it hooked to a Storage Lectern/Bookwyrm, and nothing else.

The barrel contains coal, manipulation essence, and 1 diamond. The filter is set to only allow coal and manipulation essence in or out of the barrel. I manually placed the diamond in. Then, when I go to my Storage Lectern, I am able to withdraw Diamonds, as many as I want, one at a time. I'm assuming this is because the Storage Lectern doesn't know to listen for the Filter, so it goes "yes you can take this item, it exists in this inventory," and the filter says "this item cannot be taken, it still exists in this inventory." And so on.

As a short-term workaround, I'll be disabling the Filter Upgrade for my modpack, but I would love if we could smooth this hiccup over. Thanks for your time, and for the fantastic mod!

**Comment by Mitchell5200** [comment]
Confirmed with Mekanism personal chests/barrels as well, with Ars 3.17.10 . I also cannot find any way to blacklist certain inventories from the lectern either, so that would've been a possible fix for pack devs, had that been an option.
