### ISSUE TITLE
Configurable spell levels

### ISSUE THREAD

**Issue by Aceplante2** [baileyholl/Ars-Nouveau#1018]
As in, making leap a level 3 spell, or making wither a level 2 etc. Since my idea of actually balancing the leap spell https://github.com/baileyholl/Ars-Nouveau/issues/1006 (which, despite allowing easy indefinite flight making the elyra completely useless, is a level 1 spell for some reason) does not seem to be popular, I decided to just change the recipe myself, which I suppose I can do with a datapack, but I do not seem to be able to change the spell level. Meaning, that if a player unlocks the recipe (regardless of how difficult I make it), it can still be shared with other players using a codex and used by players with only a level 1 book

**Comment by baileyholl** [comment]
This is already possible in 1.19 in the glyph config. This wont be back ported.
