### ISSUE TITLE
jar_blacklist.json and drygmy_blacklist.json are not respected

### ISSUE THREAD

**Issue by katubug** [baileyholl/Ars-Nouveau#1020]
We're having an issue where on our SMP, the datapacks for these two files are not being respected.  They do seem to work in singleplayer, but not on a server. I'm not at all sure why this is occurring. We load our datapacks via KubeJS and all the other datapacks seem to work just fine. Perhaps I've done something wrong on my end? Here's my (local) file structure: https://i.imgur.com/SFz0ZGc.png

And here are the two files (uploaded as .txt because github didn't like .json):
[drygmy_blacklist.txt](https://github.com/baileyholl/Ars-Nouveau/files/11926157/drygmy_blacklist.txt)
[jar_blacklist.txt](https://github.com/baileyholl/Ars-Nouveau/files/11926158/jar_blacklist.txt)

**Comment by baileyholl** [comment]
I think you need 
{
"replace":true
}
for tags right?

**Comment by baileyholl** [comment]
You can also get faster help on the discord, more people are available to assist.

**Comment by katubug** [comment]
Adding the "replace" line does seem to work! I'm new to datapacks so I had no idea. Thanks for your help!
