### ISSUE TITLE
[1.20.1] Crash sometimes while browsing JEI / Creative Tab.

### ISSUE THREAD

**Issue by Gbergz** [baileyholl/Ars-Nouveau#1028]
Title ^

**Versions:**
MC: 1.20.1
Forge: 47.1.0
Ars Nouveau: 4.0.1

Crash-Report: https://gist.githubusercontent.com/Gbergz/671097e35558cc6a9aaeaa32f3f114b1/raw/018b0a16fd813400672cbf8cae9c9294cc1c1fbd/gistfile1.txt

**-** Gbergz

**Comment by baileyholl** [comment]
fix is being uploaded
