### ISSUE TITLE
Altering recipe via datapack not working

### ISSUE THREAD

**Issue by Aceplante** [baileyholl/Ars-Nouveau#1031]
I wanted to add an item from another mod to one of your recipes. It worked fine with glyph recipes etc, but not pedistal crafting:

Here is what i have

{
  "type": "ars_nouveau:enchanting_apparatus",
  "keepNbtOfReagent": false,
  "output": {
    "item": "ars_nouveau:ring_of_lesser_discount"
  },
  "pedestalItems": [
    {
      "item": "quark:diamond_heart"
    },
    {
      "tag": "forge:gems/diamond"
    },
    {
      "tag": "forge:gems/diamond"
    },
    {
      "tag": "forge:ender_pearls"
    },
    {
      "tag": "forge:ender_pearls"
    },
    {
      "tag": "forge:gems/source"
    },
    {
      "tag": "forge:gems/source"
    }
  ],
  "reagent": [
    {
      "item": "ars_nouveau:ring_of_potential"
    }
  ],
  "sourceCost": 0
}

the quark item causes it to not load

**Comment by shkschneider** [comment]
I have the same non-working behavior on 1.19.2-3.17.11
`1 {
 2     "type": "ars_nouveau:enchanting_apparatus",
 3     "output": { "item": "..." },
 4     "reagant": [ { "item": "..." } ],
 5     "pedestalItems": [
 6         { "item": "..." },
 7         { "item": "..." },
 8         { "item": "..." } 
 9     ],
10     "sourceCost": 500 
11 }`

Recipe works fine with Imbuement, but never with Apparatus.
