### ISSUE TITLE
Windows Defender is detecting a trojan

### ISSUE THREAD

**Issue by xan-dr** [baileyholl/Ars-Nouveau#1033]
It was working completely fine 2 hours prior, but now windows defender is marking it as a trojan and aggressively deleting it. I've downloaded the file through prismMC and directly from curseforge it didn't make a difference.

![image](https://github.com/baileyholl/Ars-Nouveau/assets/139074213/fd952763-8c47-4de4-86c0-8e828aa0bccf)

ars_nouveau-1.20.1-forge-1.4.9.jar

**Comment by baileyholl** [comment]
This can happen from time to time with mods and is typically out of our control beyond reporting the file to Microsoft.
