### ISSUE TITLE
Arcanist Armor Textures Purple/Black

### ISSUE THREAD

**Issue by DrSnijder** [baileyholl/Ars-Nouveau#1038]
This is only when used in combination with Optifine.
![image](https://github.com/baileyholl/Ars-Nouveau/assets/37208556/47eb2db0-90e5-46d9-b3e3-dbf5837d2b87)

**Comment by DrSnijder** [comment]
Any way to fix it? Optifine seems to be incompatible.

**Comment by baileyholl** [comment]
Optifine is not compatible. You should use Rubidium for performance and Oculus for Shaders as alternatives.
