### ISSUE TITLE
Increasing the Maximum Value of Spell Damage Bonus

### ISSUE THREAD

**Issue by TianBoxv587** [baileyholl/Ars-Nouveau#1040]
Could you please modify the maximum value of SPELL_DAMAGE_BONUS = registerAttribute("ars_nouveau.perk.spell_damage", (id) -> new RangedAttribute(id, 0.0D, 0.0D, 10.0D).setSyncable(true), "50b50137-9c92-4e64-b350-6044e9e609de"); to 100 or greater? In [RpgSkillable](https://www.curseforge.com/minecraft/mc-mods/rpgskillable), spell power can be enhanced based on skill levels, but clearly, the current value of 10 is a bit small.

**Comment by baileyholl** [comment]
Good catch, fixed next update.
