### ISSUE TITLE
[1.20.1] [47.1.3] [4.2.0-all] Conflict with Geckolib Causes Server to Reject Client Version

### ISSUE THREAD

**Issue by Gibil** [baileyholl/Ars-Nouveau#1043]
This is in reference to this issue I logged with Geckolib, thinking the problem was there.
https://github.com/bernie-g/geckolib/issues/459

The server and modpack have the exact same version of Geckolib installed, however the server would reject the login based on a missing geckolib mod that clearly is loaded and in the server debug log.  The fix for this was downgrading Ars to 4.1.1...  I can't really explain that.

`[Netty Client IO #2/DEBUG] [net.minecraftforge.network.NetworkRegistry/NETREGISTRY]: Channel 'geckolib:main' : Version test of 'ABSENT ?' from server : REJECTED`

This error goes away after the Ars-Nouveau downgrade. Still not sure who's ultimately the cause.

**Comment by baileyholl** [comment]
Ah, looks some stuff was missed converting over to JIJ. Looks like a race condition from Ars disabling the geckolib network before it loads, which would explain why you were able to log in occasionally between restarts.

**Comment by baileyholl** [comment]
Try 4.2.1.
