### ISSUE TITLE
[1.20.1 Forge] Crash when rendering the temporary light item 

### ISSUE THREAD

**Issue by chorbintime** [baileyholl/Ars-Nouveau#1044]
When in the creative menu and searching "por" then scrolling down, the game will crash due to ars_nouveau:temporary_light_block being rendered. Crash is happening on the MMC4 Forge modpack.
[crash-2023-07-21_20.31.15-client (1).txt](https://github.com/baileyholl/Ars-Nouveau/files/12123664/crash-2023-07-21_20.31.15-client.1.txt)

**Comment by baileyholl** [comment]
Hello,
I cannot recreate this. 
![image](https://github.com/baileyholl/Ars-Nouveau/assets/13970203/2d9f7f0b-3c72-4405-a1d6-4056e893226b)
At a glance, it looks like a failing mixin from Legendary Tooltips. Are you able to recreate this without that mod?

**Comment by chorbintime** [comment]
The issue persists with Legendary Tooltips & its dependencies disabled. Disabling Ars Nouveau fixes the issue

**Comment by baileyholl** [comment]
Ah sorry, I should have clarified. The mixin in question is from Iceberg, which is a library for Legendary Tooltips. Would you be able to recreate without Iceberg and Legendary Tooltips? The library has to be removed as well. If you do, please attach the new crash report.

Thank you, sorry about that.

**Comment by chorbintime** [comment]
It's worth noting this was an instant crash after typing "por" into the creative menu, and its easily reproducible across multiple machines.
[crash-2023-07-21_21.52.32-client.txt](https://github.com/baileyholl/Ars-Nouveau/files/12135584/crash-2023-07-21_21.52.32-client.txt)

**Comment by ChaseDRedmon** [comment]
I am also reporting the same issue as I encountered in the MMC4 modpack as well. I can provide my crash reports if needed

**Comment by Bronski** [comment]
I'm having a crash that mentions Ars when typing "em" into JEI, and I can't help but notice that's part of the word "temporary," though mine doesn't mention a light item. In case it helps: https://gist.github.com/Bronski/ce8c9abf3e2db18eef59b37a48fee742

**Comment by baileyholl** [comment]
Embeddedt identified it as an issue with ModernFix, this has been fixed on the latest version of this mod, as well as the next release of Modern Fix.
