### ISSUE TITLE
1.19.2 Crash on launch

### ISSUE THREAD

**Issue by LazyNarcissist** [baileyholl/Ars-Nouveau#1049]
Was trying a modpack with some people and I'm seems to be only one with this problem.

[crash-2023-07-23_23.21.54-client.txt](https://github.com/baileyholl/Ars-Nouveau/files/12141330/crash-2023-07-23_23.21.54-client.txt)

**Comment by baileyholl** [comment]
Hello,
looks like a possible compat issue with your graphics hardware.
In the meantime, you coudl try to downgrade to `1.19.2 - 3.17.8`, that should work just fine with the latest version.

**Comment by baileyholl** [comment]
Should be fixed in the latest. https://legacy.curseforge.com/minecraft/mc-mods/ars-nouveau/files/4673548
