### ISSUE TITLE
The game crashes at launching 1.20.1

### ISSUE THREAD

**Issue by bpop06** [baileyholl/Ars-Nouveau#1051]
In the launcher, when "play" is clicked, forge starts loading and after saying "loading bootstrap resources" and then "loading mods", a Minecraft window loads, saying: 

"Mod ars_nouveau requires forge between 47.1.0 and 71.1.3 (inclusive)" "Currently, forge is 47.1.30"
"Mod ars_nouveau requires curios 1.19-5.0.7.1 or above" "Currently, curios is not installed"

However, I did install the required dependencies for Ars Nouveau. My mods folder has the following files:

curios-forge-5.2.0-beta.3+1.20.1-api
TerraBlender-forge-1.20.1-3.0.0.169
Geckolib-forge-1.20.1-4.2.1
Ars_nouveau-1.20.1-4.2.1-all

The crash window gave me, as well, this crash file:
[crash-2023-07-25_19.25.39-fml.txt](https://github.com/baileyholl/Ars-Nouveau/files/12166690/crash-2023-07-25_19.25.39-fml.txt)

**Comment by BuddaKream** [comment]
Same issue here, attempted to run the mod by itself along with dependencies and the error persists, regardless of forge version. From the looks of it it just seems the 1.20.1 version of Ars Nouveau is just broken.

**Comment by baileyholl** [comment]
`	Failure message: Mod ars_nouveau requires forge between 47.1.0 and 47.1.3 (inclusive)
		Currently, forge is 47.1.30`
.30 is not .3. Only <= .3 is supported.
