### ISSUE TITLE
Odd behavior with EvilCraft mob spirits

### ISSUE THREAD

**Issue by Pultex** [baileyholl/Ars-Nouveau#1055]
This might have been posted already some other way but did not see

If you make a spell that has freeze > coldsnap

the mob when will turn into a spirit when they die
the spell effects the spirit that comes from them
I don't think you should as it uses Evilcraft tools to detect them and harm them

This also seem to effect drops as all looting is disabled from this interaction as the mob is some part is not dead but a spirit

A spell that is ignite > Flare does not have this effect and will drop things with Looting

I think the slowness effect is not blocked by the Evilcraft Spirit but the mob did die as the spirit should not 100% spawn from killing them

The freeze > coldsnap spell makes the spirit form every time and acts like it fell on death so low drops and No player drops

Not sure if there could be a black list to spells effecting Vengeance Spirits as that might cause other problems and look like a bug

This is on the as of now NEW 1.20.1 version minecraft
forge-47.1.3
ars_nouveau-1.20.1-4.1.1
EvilCraft-1.20.1-1.2.25

This does not cause a crash or anything just odd interaction

**Comment by baileyholl** [comment]
Evilcraft does this with any magic damage source.
