### ISSUE TITLE
Ars Nouveau does not behave well with ModernUI

### ISSUE THREAD

**Issue by sandalle** [baileyholl/Ars-Nouveau#1060]
MC: 1.20.1
Forge: 41.7.3
Ars Nouveau: 1.20.1-4.2.4
ModernUI: 1.20.1-3.7.1.3

When having both Ars Nouvou and ModernUI ( https://www.curseforge.com/minecraft/mc-mods/modern-ui ) and I try to create a new spell, when typing in the name field to name my spell it crashes the client (but not the dedicated server): [crash-2023-08-08_20.08.06-client.txt](https://github.com/baileyholl/Ars-Nouveau/files/12297855/crash-2023-08-08_20.08.06-client.txt)

"Spell Name" text field is the bottom left field:
![Ars Nouveau Spell Name](https://github.com/baileyholl/Ars-Nouveau/assets/2447608/0144c045-70b4-44bc-b1c2-a9e4d62bcf03)
Typing in the "Search" field in the top right causes the same crash.

ModernUI bug filed: https://github.com/BloCamLimb/ModernUI/issues/164

**Comment by baileyholl** [comment]
They would need to fix it, and looks like they have in the latest version.
