### ISSUE TITLE
Starbuncles prioritize source berry bushes over extracting from containers

### ISSUE THREAD

**Issue by TheExperiment1** [baileyholl/Ars-Nouveau#1062]
![2023-08-09_18 16 05](https://github.com/baileyholl/Ars-Nouveau/assets/70029903/492d4b3f-6ead-484c-b1ca-04b76f725193)

When tasked with transferring source berries to a couple of pedestals for the Mycelial Sourcelink, the starbuncle prioritized picking the berries from nearby bushes one by one instead of making the transfer. It will do so even through walls, causing the starbuncle to freeze until a path to the bushes is formed.

**Comment by baileyholl** [comment]
1.16 is no longer updated. You can give them shades to disable berry pickup. I would use 2 if you need one task to be prioritized.
