### ISSUE TITLE
50 crashes from the Starbuncle

### ISSUE THREAD

**Issue by DaeTheKnight** [baileyholl/Ars-Nouveau#1064]
Is there a way I can disable Ars Nouveau’s starbuncle from ever spawning?

My logs show a crash whenever they’re supposed to spawn. I can’t explore the world because of it.

The logs also say “shadowed” when they crash.

I’ve been trying to find workarounds by just not exploring but now I’ve got to get to the end dimension so I have no choice but to move.

I’m using GD launcher on the steam deck.

**Comment by baileyholl** [comment]
Please post the crash log.

**Comment by DaeTheKnight** [comment]
file:///home/deck/.var/app/io.gdevs.GDLauncher/config/gdlauncher_next/instances/All the mods 8 - 1.0.22/logs/2023-08-10-6.log.gz

let me know if this works. please and thank you

**Comment by DaeTheKnight** [comment]
https://api.mclo.gs/1/raw/nsDQk7E

https://mclo.gs/nsDQk7E

also there's this if it doesn't

**Comment by baileyholl** [comment]
That looks like the log.latest - the crash_reports folder would have the relevant log, there is nothing crash related in the one linked.

**Comment by DaeTheKnight** [comment]
https://mclo.gs/MDEvUB8

https://api.mclo.gs/1/raw/MDEvUB8

omg you're fast. try this one. it's from the correct folder now

**Comment by baileyholl** [comment]
That crash log just points to iris (oculus). 
`java.lang.IncompatibleClassChangeError: class net.coderbot.iris.gui.option.ShadowDistanceOption cannot inherit from final class net.minecraft.client.OptionInstance`

**Comment by DaeTheKnight** [comment]
![IMG_6435](https://github.com/baileyholl/Ars-Nouveau/assets/142058563/91f18f46-1b3d-41b1-b5cf-803c237e6b6a)

here’s what I get when I play

**Comment by DaeTheKnight** [comment]
![IMG_6436](https://github.com/baileyholl/Ars-Nouveau/assets/142058563/c28a7c42-0fbb-442c-83cf-83243c040295)

**Comment by DaeTheKnight** [comment]
here is my latest log.

https://mclo.gs/Ej9ILwQ

https://api.mclo.gs/1/raw/Ej9ILwQ

**Comment by DaeTheKnight** [comment]
![IMG_6459](https://github.com/baileyholl/Ars-Nouveau/assets/142058563/51f227f4-4ba3-4265-afee-cf9ffef54e66)

**Comment by DaeTheKnight** [comment]
Okay this time I think I have the crash report you're looking for.

https://mclo.gs/4cEYD88

https://api.mclo.gs/1/raw/4cEYD88
