### ISSUE TITLE
Crash with Ars Nouveau

### ISSUE THREAD

**Issue by HenrikoMagnifico** [baileyholl/Ars-Nouveau#1066]
Ars Nouveau causes the server to crash, for no clear reason. Any help would be very much appreciated!

[crash-2023-08-12_10.46.19-fml.txt](https://github.com/baileyholl/Ars-Nouveau/files/12327197/crash-2023-08-12_10.46.19-fml.txt)

**Comment by hsingh1312** [comment]
mine crashes as well but only when I hover over the clothes from the mod

**Comment by vitalikyarina** [comment]
Also, crash with Apotheosis
