### ISSUE TITLE
[1.16.4] Crash When Changing Resource Packs

### ISSUE THREAD

**Issue by GeoTerra** [baileyholl/Ars-Nouveau#107]
Crash when changing resource packs to the Faithful 1.16.4 downloaded directly from faithful.team.

Log: https://pastebin.com/msrQcpwM

If this is not Ars Nouveau's fault and is some other mod misbehaving, please let me know. I only come here as Ars is mentioned in the first line of the log.

**Comment by GeoTerra** [comment]
It's worth noting that it crashes before the change can be serialized to options.txt or however Minecraft saves its settings now so it doesn't crash on subsequent reloads of the pack.

**Comment by baileyholl** [comment]
this has been fixed on the latest version, 1.9.2/1.9.3 :)

**Comment by GeoTerra** [comment]
Ah, thank you. I had just updated the pack (DW20) but the FTB Launcher is giving me grief trying the launch the game but that's a topic that doesn't belong here.
