### ISSUE TITLE
Missing armor textures with optifine on

### ISSUE THREAD

**Issue by SeyVetch** [baileyholl/Ars-Nouveau#1073]
![2023-08-19_12 26 01](https://github.com/baileyholl/Ars-Nouveau/assets/39887104/b71fe6a5-fa8f-4f53-862a-3f8e5a761fba)
with optifine
![2023-08-19_12 34 26](https://github.com/baileyholl/Ars-Nouveau/assets/39887104/8b6d82e0-36d6-445e-9cad-82e41aa6587b)
without optifine
I have the latest versions of the mod and of optifine - OptiFine HD U I6 pre6. Should I just play without optifine or is there something I can do to change this

**Comment by baileyholl** [comment]
Optifine is not supported. There are lots of optifine alternatives that play nice with mods. Some include Rubidium for performance, and Oculus for shaders.
