### ISSUE TITLE
Add blacklist or whitelist ( Form - Effect )

### ISSUE THREAD

**Issue by steam9w** [baileyholl/Ars-Nouveau#1076]
- Example:
Form Projectile cannot be used Effect Ignite.

This will give more customization options for custom Modpacks.

**Comment by steam9w** [comment]
- In the configuration, you can configure ( Effect - Augment ):
    #Limits the number of times a given augment may be applied to a given effect
    #Example entry: "glyph_amplify=5"
    augment_limits = []
    
- My suggestion is to add a setting:
Form - Effect
At the moment, you can add any effect to the form.
I suggest making it so that certain effects cannot be added to the form.

Example:
glyph_projectile.toml
    effect_blacklist = ["ars_nouveau:glyph_ignite", "ars_nouveau:glyph_invisibility"...]

At the moment, there is no such setting either in the configuration or in the code.

**Comment by dkmk100** [comment]
I suggest also exposing the blacklist that already exists for effects

**Comment by baileyholl** [comment]
This is added in the latest version.
