### ISSUE TITLE
Crash after loading world. 

### ISSUE THREAD

**Issue by Xplodin** [baileyholl/Ars-Nouveau#1077]
https://gist.github.com/Xplodin/8c23d660b5561116b79c9289406f7856

happens to load all the way until the world is finished loading.
Server goes up and runs, then crashes 5 seconds after everything loads.
most notable line: java.lang.NoClassDefFoundError: com/hollingsworth/arsnouveau/client/gui/book/BaseBook

**Comment by baileyholl** [comment]
Fixed in latest version.
