### ISSUE TITLE
[1.19.2] showSupporterMessage ignored

### ISSUE THREAD

**Issue by SigmaFlame** [baileyholl/Ars-Nouveau#1084]
The message indicating that Ars Nouveau support dynamic light is shown every world launch.
The setting ``showSupporterMessage`` is not set to false automaticly and even if it set to false manually, the message is still shown.
In 1.19.2 latest version : 3.17.10.

**Comment by baileyholl** [comment]
Show supporter message is for patrons, you would be looking for `informLights`. That however was also bugged, and is fixed  next version.
