### ISSUE TITLE
Abnormal Font Shadows with Modern UI Usage in JEI

### ISSUE THREAD

**Issue by Dr-WeiAL** [baileyholl/Ars-Nouveau#1087]
The fonts in Ars Nouveau's JEI/EMI messages are shaded when using the Modern UI.
![image](https://github.com/baileyholl/Ars-Nouveau/assets/47446553/bb592461-8111-4a67-924b-441aef78a23c)
Other mods that also display text in JEI don't have this problem
For example, JustEnoughResources, AppliedEnergistics2, Create
![image](https://github.com/baileyholl/Ars-Nouveau/assets/47446553/beda857c-7013-49c4-94d3-e538580c083a)
![image](https://github.com/baileyholl/Ars-Nouveau/assets/47446553/528d2bae-e07c-4c0a-9f3f-44d46a132077)
![image](https://github.com/baileyholl/Ars-Nouveau/assets/47446553/13e62949-3c31-4db1-be72-0bad43db97e5)
Hopefully this can be fixed

**Comment by Alexthw46** [comment]
This was actually fixed in-dev more than a month ago but apparently Bailey hasn't released it yet
