### ISSUE TITLE
1.20.1-4.3.0 have wrong game version on curseforge

### ISSUE THREAD

**Issue by CubeTwo** [baileyholl/Ars-Nouveau#1095]
Ars Nouveau 1.20.1-4.3.0 on curse-forge have set game version 1.0 and have no change-log, its intended?
 
![image](https://github.com/baileyholl/Ars-Nouveau/assets/16674396/5045a65a-8aa5-443f-bedf-02b0859c6986)

**Comment by uhloin** [comment]
Also there are 2 files: ...jar and -all.jar
What's difference?

**Comment by baileyholl** [comment]
-all contains necessary dependencies.
