### ISSUE TITLE
list of glyphs stuck on screen

### ISSUE THREAD

**Issue by MiniNinja1810** [baileyholl/Ars-Nouveau#1097]
![image](https://github.com/baileyholl/Ars-Nouveau/assets/76655877/43e277b4-90d8-4c67-bb73-802f352b5170)
as seen, the list of glyphs are just.. stuck on my screen and idk how to get rid of em

**Comment by Alexthw46** [comment]
That list is not from this mod, you must have triggered something from a questbook or similar that brought up the ToDo list
