### ISSUE TITLE
1.19.2-3.17.10 Bookwyrms causing major lag

### ISSUE THREAD

**Issue by Zyrafosii** [baileyholl/Ars-Nouveau#1100]
Hello, for some reason bookwyrms have been causing major lag in our areas, some are unaffected, some are really bad laggers. 
It seems like they're stuck in place when they're lagging really badly, but some were moving too.

![image](https://github.com/baileyholl/Ars-Nouveau/assets/18689152/d64efa4b-ffa1-4f91-bd4e-4b94804c2653)

**Comment by baileyholl** [comment]
Can you post a spark profile?

Unfortunately this is likely due to the vanilla pathfinder. After you profile them, you can kill them to turn them back into charms. They do not need to be alive for any reason other than to bind inventories.

**Comment by Zyrafosii** [comment]
https://spark.lucko.me/3fmSBR2gG8

**Comment by Zyrafosii** [comment]
I did not mean to close the issue, sorry.
