### ISSUE TITLE
Dynamic Lights doesn't work with Embeddium

### ISSUE THREAD

**Issue by StarskyXIII** [baileyholl/Ars-Nouveau#1101]
Game Version: 1.20.1
Ars Nouveau: 4.4.0
Embeddium: 0.1.5

Items which can emit light no longer produce Dynamic Lights.
Maybe related to https://github.com/LambdAurora/LambDynamicLights/issues/175

**Comment by baileyholl** [comment]
Embeddium has since fixed this.
