### ISSUE TITLE
Illusion "Weave" Blocks turn Invisible and lose their imitation properties on Save reload 

### ISSUE THREAD

**Issue by DarianStardust** [baileyholl/Ars-Nouveau#1110]
blocks like Ghostweave and Fakeweave, I will set them to imitate a block (source stone, archwood logs for example), and they behave as expected, but upon saving and re-entering save they First turn invisible, Even the ones that can't be made invisible by Invisible spell) Then lose the appearance of the last block they were turned into, basically reset to default block, Fakeweave in particular shouldn't be able to become invisible, and Ghostweave turns visible again after some time, and also loses it's imitated block on Save re-load

They can be forced to appear visible again by placing blocks on top of them, or breaking connected blocks, some of them Re-appear by themselves after a while but Idk why. Using a block for them to mimic will work, but they will stay invisible until a block is placed ib top of them, or broken to "update" them.

![2023-09-27_15 46 26](https://github.com/baileyholl/Ars-Nouveau/assets/145576730/269320fa-6803-4945-b3a7-89dad9687561)
![2023-09-27_15 47 10](https://github.com/baileyholl/Ars-Nouveau/assets/145576730/525841b3-3482-4934-bae6-04bddecd7fe6)

Minecraft 1.20.1 
Forge 47.1.43
Ars Nouveau 4.4.0

Log-Chan
[latest.log](https://github.com/baileyholl/Ars-Nouveau/files/12754083/latest.log)
[debug.log](https://github.com/baileyholl/Ars-Nouveau/files/12754084/debug.log)

Side issue with Bookwyrm familiar not dispelling, using the shortcut or the book will summon a second bookwyrm instead, the first one won't be dispelled by dissipate command nor Dispel Spells (I tried in many ways), And don't reserve a portion of the mana bar anymore, what seems to work is exit game, Enter save, attempt to dispel, and repeat until the familiar is dispelled.
     I'm not sure of the bug trigger yet, nor if it's only the Bookwyrm familiar that bugs like this, last time it happened after many quick short actions so I can't guess the cause, need to test, Will post log if I get the bug again

Just to show it, two familiars
![2023-09-26_10 10 05](https://github.com/baileyholl/Ars-Nouveau/assets/145576730/825f1863-a280-47c6-99e9-90c1bd9d2f67)

**Comment by baileyholl** [comment]
This is now fixed in latest.
