### ISSUE TITLE
Bug Report - Leap Glyph Tier Level Incorrect

### ISSUE THREAD

**Issue by Necronomis** [baileyholl/Ars-Nouveau#1115]
I've identified a bug where the Leap glyph reports the incorrect tier level somewhere along the line. In the book, it is listed under the level 1 glyphs. However, when you learn it, it is limited to the level 3 book.

**Comment by baileyholl** [comment]
This is a limitation of patchouli, as items cannot be moved categories at will. Your pack adjusted it to tier 3, but it unfortunately cannot be moved without a pack modifying the pages manually.
