### ISSUE TITLE
[3.18.0] [Bug] Wilden dens crash game

### ISSUE THREAD

**Issue by SemGamerNL** [baileyholl/Ars-Nouveau#1117]
i have a generated world in a previous version when i started my modpack, with a wilden den, no problems, but i wanned to remove some unwanted chucks but when i tried to remove the part with the wilden den it crashed since it has to generate a new one on that place. ik for sure its the den since when i removed all chucks except the den, the wolrd was fine. but ones it needs to generate a new one, the world crashes.

even when i generated a new world with the same seed, the wold crashed when it tried to generate the chunks with the den. 

i have verson 1.19.2-3.18.0

**Comment by baileyholl** [comment]
Can you post a log?
