### ISSUE TITLE
crash compat between ars and sodium (forge one tho)

### ISSUE THREAD

**Issue by Vadewolf** [baileyholl/Ars-Nouveau#1130]
[crash-2023-10-07_13.24.32-client.txt](https://github.com/baileyholl/Ars-Nouveau/files/12838496/crash-2023-10-07_13.24.32-client.txt)

feel free to ping me on discord if needed i m CHarliePratt in the discord

**Comment by baileyholl** [comment]
Update to latest rubidium or use Embeddium.
