### ISSUE TITLE
Exchange Spell Crash

### ISSUE THREAD

**Issue by ChosenArchitect** [baileyholl/Ars-Nouveau#1131]
Issue:
-> I was using Projectile>exchange>AOEx2 and when exchanging dirt with stone it crashed me.

Crashlog:
-> https://pastebin.com/YZWK7kUL

Mod Version:
-> Ars Nouveau 1.20.1-4.6.0-all

**Comment by Darkinian** [comment]
does the same thing to me. same version. I tried different configuration of the spell like touch or projectile, with aoe, no aoe, different block to replace and it just always crash with the book disappearing from the hotbar afterward when loading the world again.

https://pastebin.com/rMP3mAQB

**Comment by baileyholl** [comment]
Should be fixed next version, hopefully here in a few hours.

**Comment by Darkinian** [comment]
yup it works!
