### ISSUE TITLE
Spell cost changes (or mana quartered?) during play

### ISSUE THREAD

**Issue by Rimplestilt** [baileyholl/Ars-Nouveau#1132]
Playing 1.20.1 forge, with Ars Nouveau, Elemental, and Creo. Have not done much in the mod yet. A bit turned off that my spell cost is changing on me. When i load into the game i can use my spells a decent amount. But then in a short amount of time, that cost goes 3x-4x.
For example, the simplest spell using Projectile and Harm, when i load into the game, i can fire 7 times before letting it recharge. But this soon changes to only 2 fires before i must recharge. I don't know enough about the mod to know which one would be standard, but i have base mana as far as i know. It's possible the issue is that my mana pool goes down?

I have not determined what causes this, it is possible it happens after dying. Regardless, the only way to fix it has been to log out of the server and rejoin.

**Comment by baileyholl** [comment]
This was just fixed today, once the update is approved the fix will be available
