### ISSUE TITLE
Volcanic Sourcelink is overheating server processor

### ISSUE THREAD

**Issue by Midas1026** [baileyholl/Ars-Nouveau#1135]
1.20.1 V. 4.60
When placing the volcanic source link, the server processor immediately spikes to 100% usage and begins overheating. This does not occur during single player.  This happens when the block has simply been placed and no items are being consumed by it. 
[iot lives 1.20.1.zip](https://github.com/baileyholl/Ars-Nouveau/files/12898841/iot.lives.1.20.1.zip)
This is all the mods we have with it.

**Comment by baileyholl** [comment]
Please run a profile using the Spark mod and attach the results.
