### ISSUE TITLE
Chicken in a jar leaking eggs ;)

### ISSUE THREAD

**Issue by Medivha** [baileyholl/Ars-Nouveau#1136]
Ars 1.201 4.7.1 NeoForge(all)
MC 1.20.1
Direwolf20 1.20 1.1.0

Chicken in a Containment Jar drops Eggs out of the Jar and get not generated from the Drygmy

![](https://i.imgur.com/EsNGjqE.png)

**Comment by baileyholl** [comment]
This is intended, you can use a starbuncle to pick them up.
