### ISSUE TITLE
Attempting to add ANY augment to any spell crashes the game

### ISSUE THREAD

**Issue by 5ubject** [baileyholl/Ars-Nouveau#1138]
I tested this 3 times. Twice on the same spell, and once on a different spell. Seems consistent. The first crash occurred only shortly after I freshly unlocked my first augments. Let me know if you need more details.

[crash-2023-10-14_07.01.03-client.txt](https://github.com/baileyholl/Ars-Nouveau/files/12904650/crash-2023-10-14_07.01.03-client.txt)

**Comment by baileyholl** [comment]
This happens when using incompatible versions of rubidium. Replace it with embeddium for better support.

**Comment by 5ubject** [comment]
Thank you so much! You're a lovely wonderful personnnnnn! ❤️❤️❤️
