### ISSUE TITLE
Dynamic lights don't work with Rubidium in 1.20.1

### ISSUE THREAD

**Issue by Gorgok** [baileyholl/Ars-Nouveau#1141]
ars_nouveau-1.20.1-4.7.2-all.jar
curios-forge-5.3.5+1.20.1.jar
rubidium-mc1.20.1-0.7.1.jar

Forge - 47.2.1

Dynamic lights don't work with Rubidium installed. Removing it and lights work fine again.

**Comment by baileyholl** [comment]
Embeddium is better supported, please use that if possible.
