### ISSUE TITLE
[1.19.2-3.21.2][Bug]Summon Steed causes a crash

### ISSUE THREAD

**Issue by jaynesb** [baileyholl/Ars-Nouveau#1143]
Minecraft: 1.19.2
Forge: 43.3.2
Ars Nouveau: 3.21.2

Casting Summon steed (tried with self and projectile focuses) causes a crash the moment the horse comes into existence. The rest of the summon types work fine.

[crash-2023-10-18_16.35.31-server.txt](https://github.com/baileyholl/Ars-Nouveau/files/13035022/crash-2023-10-18_16.35.31-server.txt)

**Comment by baileyholl** [comment]
You need to update Ars Elemental.

**Comment by jaynesb** [comment]
My Ars Elemental version is 0.5.9.2.1, the latest version available for 1.19.2 from Curseforge (newer versions are listed for 1.20.1 only). Should I report this over there then?
