### ISSUE TITLE
Crash when using spell book on scribes table

### ISSUE THREAD

**Issue by Canpake59** [baileyholl/Ars-Nouveau#1145]
I am using Prominence II Forge modpack and when using the spell book on the scribes table I crash. Here is my latest.log

[latest.log](https://github.com/baileyholl/Ars-Nouveau/files/13047985/latest.log)

**Comment by baileyholl** [comment]
Are you using rubidium? If so, it should be replaced with Embeddium.

**Comment by Canpake59** [comment]
> Are you using rubidium? If so, it should be replaced with Embeddium. 

I was using rubidium. Just switched to Embeddium and am no longer crashing. Thank you very much.
