### ISSUE TITLE
Starbuncles cause server tick time to triple even when 'off'

### ISSUE THREAD

**Issue by Gorgok** [baileyholl/Ars-Nouveau#1146]
Forge 47.2.1
ars_nouveau 4.7.3

I have a pair of starbuncles automating my imbuement chambers, 1 to empty all 8 of them with an item filter for essence and another to fill them from a lectern with gems. Both have a bed and a lever with them powered, so they are idle. Tick time goes from around 30ms to around 10ms if I dispel them and back again if i place them down and they hop back in their beds. Seems a little excessive for idle automation. 

With idle starbuncles:
https://spark.lucko.me/9nenK9YKlo

After dispelling the starbuncles:
https://spark.lucko.me/RtyvkPwQoV

**Comment by baileyholl** [comment]
Most of the time is spent loading the pedestals, are they attached to an imbuement chamber that is on a chunk boundary?

**Comment by Gorgok** [comment]
Pedestals for their respective imbuement chamber are in the same chunk, but of the 8 imbuement chambers (and 3x pedestals) half are in one chunk and the other its neighbor. I can test if moving them all to one chunk makes a difference, but im also standing in one of the chunks in question so both are loaded by me.

**Comment by baileyholl** [comment]
Found a quick fix that should help a lot - thanks for reporting.
