### ISSUE TITLE
unable to open scribe table 1.20.1

### ISSUE THREAD

**Issue by ItsBonezey** [baileyholl/Ars-Nouveau#1147]
right clicking with the basic spellbook on the scribe table ctd's minecraft. 
it was achieved by right clicking a basic spellbook on a scribe table.
(the crash report doesn't seem to be helping, just listing a bunch of rendering mods... why would they have an impact?)
[crash-2023-10-21_19.04.37-client.txt](https://github.com/baileyholl/Ars-Nouveau/files/13062218/crash-2023-10-21_19.04.37-client.txt)

**Comment by baileyholl** [comment]
If you are using rubidium, swap it to embeddium, it is more compatible.
