### ISSUE TITLE
Game crashes when using the spell book on the scribe table

### ISSUE THREAD

**Issue by ErebiusBlue** [baileyholl/Ars-Nouveau#1156]
I recently installed ars nouveau and when I try to craft glyphs the game ends up crashing. 
Here is the crash report.
[crash-2023-11-06_23.02.19-client.txt](https://github.com/baileyholl/Ars-Nouveau/files/13275620/crash-2023-11-06_23.02.19-client.txt)

**Comment by baileyholl** [comment]
Sorry for the late reply. This is a bug with Rubidium. You can swap it out for Embeddium.
