### ISSUE TITLE
AOE spells do not work in 1.20.1

### ISSUE THREAD

**Issue by GooseOfGeese** [baileyholl/Ars-Nouveau#1159]
AOE spells dont work as intended, only applies to single blocks but not the targeted block

eg, having projectile > break > aoe* 8 should break a 9x9 square, but instead only destroys a single block and not the target block

having projectile > ignite > aoe * 8 should set a 9x9 square on fire, but instead only sets one block on fire and not the target block

Reproduction Steps
- do Touch => Break => AOE = only breaks one block
- Add more AOE
- Still only affects one block

**Comment by Alexthw46** [comment]
HT Tree Chop breaks AOE effects.
You have to go to treechop-common.toml and change multimine to false or the AoE won't work as it breaks a random block
