### ISSUE TITLE
Crash when right clicking on storage lectern

### ISSUE THREAD

**Issue by Kythulhu** [baileyholl/Ars-Nouveau#1161]
Whenever I right click on a storage lectern I get the below crash.
I have tried:
  1. Breaking and replacing block
  2. Removing inventory sorting mods
  3. Removing shaders
  4. Trying different versions of Ars and other mods
  
  
  
[crash-2023-11-09_12.51.31-client.txt](https://github.com/baileyholl/Ars-Nouveau/files/13312778/crash-2023-11-09_12.51.31-client.txt)

**Comment by baileyholl** [comment]
Hello,
I cannot reproduce this unfortunately. The crash log isn't particularly helpful, would you be able to reproduce this in an only vanilla + ars instance? You have multiple performance mods you could also attempt to reproduce without, or without hammerlib as well.

**Comment by Kythulhu** [comment]
Sorry for the delay in responding, It took a while to figure out what the problem was! It is caused by a mod called "Visual Overhaul". I literally had to go through all my mods one by one to find it, but wanted to update here in case anyone else had the issue!
