### ISSUE TITLE
Chunk-ban-like crash when converting lapis into source gem

### ISSUE THREAD

**Issue by MidnightDragons** [baileyholl/Ars-Nouveau#1163]
There seems to be an issue when converting lapis into source gems.

Steps to reproduce:
1. Place lapis in imbuement chamber with a source jar nearby.
2. Crash

The issue here is that when this happens, you cannot join the server again until the recipe is done cooking.

The exact thing that pops up when you get disconnected is this:
"Internal Exception: io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException: Index 64 out of bounds for length 7"

Here are the server logs:
[client-latest.log](https://github.com/baileyholl/Ars-Nouveau/files/13323442/client-latest.log)
[server-latest.log](https://github.com/baileyholl/Ars-Nouveau/files/13323443/server-latest.log)

**Comment by MidnightDragons** [comment]
Update: It seems to do it only if there's source jar near by.

**Comment by fourthhouse** [comment]
Bump, very similar issue. Only non-op players rendering chunks that are using source jars to produce magic (especially making essence) get kicked. I'm op and it does not kick me. But anyone on my server trying to make essence gets kicked immediately when they begin the creation of the essence.

**Comment by Willsr71** [comment]
We've run into this as well across ~30 players, there doesn't seem to be any consistency on who is affected, be it ops, gamemode, shaders. The problem pretty consistently follows the same ~50% of players even after client and playerdata wipes.

There are a couple things that cause the disconnects that we've observed.
- Source Jar being next to Imbuement chambers as listed initially
- Drygmy summoning with a drygmy henge
- Certain glyphs scribe table

Unaffected players are able to break the offending blocks and the affected ones are promptly able to join again.

**Comment by Aetheran** [comment]
Ars Nouveau - Things that cause chunk crashes

Depleting Source Jars
Examples:
Hooking up a source jar to an enchanting Apparatus (which depletes it)
Ritual Braziers which require a source connection (which depletes it or requires an active connection)
Drygmy Farms (which depletes it)

Other:
-Jar of Containment on an archevoker creates a lag machine and will exist when you hold or look at it

**Comment by baileyholl** [comment]
Please update both bumblezone and Ars Nouveau to latest, a fix has just been uploaded.
