### ISSUE TITLE
Suggestion: add notebook, spell books, and caster tomes to #minecraft:bookshelf_books tag

### ISSUE THREAD

**Issue by gardenappl** [baileyholl/Ars-Nouveau#1165]
The `minecraft:bookshelf_books` item tag determines whether or not an item can be placed inside the new 1.20.1 Chiseled Bookshelf. I'd be cool to use interactive bookshelves for all the different mods' guide books, and for my Ars caster tome collection.

This is similar to #639

*(Also this is not exactly related but from what I've seen, the `lectern_books` tag doesn't really inherently work, I can't place my spell book inside a lectern, even though it's tagged with `lectern_books`. But I can place a Worn Notebook in there. Maybe Patchouli has special integration with it, or maybe the Spell Book's right click functionality messes with it. Maybe the lectern tag should just be removed from it)*

**Comment by baileyholl** [comment]
Looks like this was added in April
