### ISSUE TITLE
alter tree generation?

### ISSUE THREAD

**Issue by lawrencedumarey** [baileyholl/Ars-Nouveau#1166]
Please let me know if there is any way to actually alter the spawn rate of archwood trees in ars nouveau, as I feel like they spawn a bit too frequently and are a strange thing to see in some biomes. I have found ways to dissable biomes but not the trees themselves sadly.

Thanks you!
Larry

**Comment by Alexthw46** [comment]
the random ones are controlled by 
https://github.com/baileyholl/Ars-Nouveau/blob/1.20/src/generated/resources/data/ars_nouveau/worldgen/placed_feature/placed_mixed_archwoods.json
for spawnrate, while by
https://github.com/baileyholl/Ars-Nouveau/blob/1.20/src/generated/resources/data/ars_nouveau/forge/biome_modifier/rare_archwood_mix.json
for which biomes to spawn in
