### ISSUE TITLE
Sanctuary Ritual Incorrect Cost

### ISSUE THREAD

**Issue by blacksabin** [baileyholl/Ars-Nouveau#1169]
Per the in-game documentation on the Ritual of Sanctuary; "Costs source once a minute if a spawn is denied". 
So first to mention is that there isn't much more described here, and understandably so. Looking at the code, source is definitely only taken should a spawn be denied, but the twist here is that augmenting/upgrading the ritual with a bigger radius doesn't increase the source cost of the ritual. If that is by design, great! The real issue is the timing. If I understand it correctly, a Minecraft world tick is something along the lines of 20 ticks per 1 real world second. The minute specified in the documentation makes no distinction between real world time or Minecraft time. The code runs on a modulo 300 operation, which would be 15 seconds and not 1 minute. In "Minecraft time" technically speaking 16.6 ticks would equate to 1 minute; if the minute is supposed to be real-world, then it should instead be 1,200 ticks, and thus modulo 1200. Either a change to the documentation is necessary or a change to the code.

**Comment by baileyholl** [comment]
Oops, thanks
