### ISSUE TITLE
Ars Noveau crashes when using a spellbook on a scribe's table. 

### ISSUE THREAD

**Issue by Basketball985** [baileyholl/Ars-Nouveau#1170]
Playing on a modpack with friends and our game crashes when we attempt to use a scribe's table with an apprentice book.

Crash log:
[crash-2023-11-24_11.20.48-client.txt](https://github.com/baileyholl/Ars-Nouveau/files/13457263/crash-2023-11-24_11.20.48-client.txt)

**Comment by baileyholl** [comment]
This is caused by Rubidium, Embeddium is the same mod but more compatible, I would switch if possible.
