### ISSUE TITLE
[compat bug] 1.19.2 summon focus summon steed is crashing with alexs domesticationinnovation mod

### ISSUE THREAD

**Issue by CKY-** [baileyholl/Ars-Nouveau#1181]
Hate to do this to you but seems there is a mod commutability issue with [domesticationinnovation ](https://github.com/AlexModGuy/DomesticationInnovation) that is causing a server side crash.

here is the crash log 
https://gist.github.com/CKY-/f201e59f8fcbd385596184a00a8cb5a3
more important here is the last bit of the latest log 

https://gist.github.com/CKY-/38f79af402c779fd76ee461e84c6ce5c

I will be sending this to alex as well as it may be an issue on their end.. https://github.com/AlexModGuy/DomesticationInnovation/issues/173

thank you for your time.

**Comment by baileyholl** [comment]
I believe this was already fixed, feel free to reopen if this still happens on the lastest version.
