### ISSUE TITLE
Release older versions on Modrinth

### ISSUE THREAD

**Issue by colin-heffernan** [baileyholl/Ars-Nouveau#1186]
Would it be possible to release the latest builds for some older versions on Modrinth? I'm trying not to use CurseForge if possible, and currently the only mod from CurseForge is Ars Nouveau. If you'd rather not, I understand. Just reply and I will close the issue.
EDIT: Forgot to mention, my pack is for 1.18.2, in case it matters.

**Comment by baileyholl** [comment]
I uploaded the 1.18 version. 1.18 isn't supported any longer and is missing a large amount of content from 1.19+.

**Comment by colin-heffernan** [comment]
Thanks!
