### ISSUE TITLE
Source Bucket item and Source liquid is missing in JEI

### ISSUE THREAD

**Issue by AlisonHuang777** [baileyholl/Ars-Nouveau#1187]
https://github.com/LunaPixelStudios/Prominence/issues/376
I don't know whether or not it's caused by some mods in the modpack. I will be appreciated if someone can help me identify what is causing this. Thanks in advance!

**Comment by AlisonHuang777** [comment]
Is Source Bucket still present in the modern version of the mod?
![2023-12-14_22 49 39](https://github.com/baileyholl/Ars-Nouveau/assets/51637996/26904370-f2ac-4f62-8fcc-163275801300)
If not then this line can be misleading.

**Comment by baileyholl** [comment]
Source buckets were removed a while ago. Thank you for pointing out the docs, I will fix that.
