### ISSUE TITLE
Translucent Particles missing with shaders

### ISSUE THREAD

**Issue by blagdorfinguy** [baileyholl/Ars-Nouveau#1189]
MC Version 1.20.1
Running Oculus 1.6.13 and Embeddium 0.2.13
Utilizing shaders causes particles with an alpha channel to be rendered VERY faintly

![2023-12-18_00 30 20](https://github.com/baileyholl/Ars-Nouveau/assets/10915910/b2332e0a-137b-4c24-809f-695758f1cb65)

**Comment by baileyholl** [comment]
We are unable to dedicate full shader support, some shaders will work better than others. I have seen Complimentary shaders be recommended as compatible.
