### ISSUE TITLE
Imbuement Chamber with Source Jar causing server connection loss via Internal Exception

### ISSUE THREAD

**Issue by yakusai** [baileyholl/Ars-Nouveau#1196]
Since the error is exactly as outlined [here](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3915), I will copy most of its bug report but with some additional information:

### Modpack
Custom modpack, over 250+ mods

### Ars Nouveau Version
Bug replicated on both 4.7.6 and 4.8.2

### Describe the bug
In my personal server that I host for a custom modpack, whenever an item goes in the imbuement chamber while it is powered by a source jar, be it Lapis or Amethyst, or any of the ingredients for creating essences, etc, this error appears, with "[XX]" being a different number every time the disconnect is triggered:

"Connection Lost

Internal Exception: io.netty.handler.codec.DecoderException: unknown serializer type [XX]"

The problem only comes when source is used in the crafting process. Placing the item into the chamber will immediately disconnect everyone in the area, and they will continue to disconnect upon rejoining until the imbuement process is complete.
It also does not matter if I put the item in there, another player, or even a hopper.

I should also note that this does not cause a crash or disconnection in my single player world tests. It only causes disconnections when it occurs on the server. It also does not occur with any other thing that requires source such as spell turrets, and the disconnection occurs even after resetting my server's world, or reinstalling or updating Ars Nouveau. I also tried to remove Ars Nouveau from the server, load into the world without Ars Nouveau, then reinstall the mod into the server in an attempt to reset it, which did not work either.

### Log Files
No relevant log information is generated, by both the server's log files or the user's log files. No errors are mentioned within any logs or debug logs when the disconnection occurs.

### Steps to Reproduce
-Place Imbuement Chamber
-Place down a creative source jar, or a source jar filled with any amount of source
-Put an amethyst shard, lapis lazuli, or really anything that can be imbued in the imbuement chamber
-Immediately disconnect, and continue to disconnect until the imbuement process is complete.

I would really hope that any insight can be given on this issue. I have several friends that would love to learn this mod on my server, and I myself have succesfully used the mod and all its systems in a different server with a different modpack (ATM9), but I just can't figure out how to debug this issue. If anyone can help, thank you in advance.

**Comment by baileyholl** [comment]
Hello,
a few users have reported this issue, but one has narrowed it down to Bumblezone. Still trying to figure out a fix at this time.

**Comment by baileyholl** [comment]
Please update both bumblezone and Ars Nouveau to latest, a fix has just been uploaded.

**Comment by yakusai** [comment]
IT WORKS!!! Thank you so very much for taking the time to resolve this issue, you are a godsend! I appreciate all that you do for Minecraft, and applaud your talents! Thank you for making such a fun mod, and thank you for taking care of it so well!
