### ISSUE TITLE
summon steed crash

### ISSUE THREAD

**Issue by pibblepower** [baileyholl/Ars-Nouveau#1198]
hey, I'm playing a modified ATM 8 pack (ie; ATM 8 with more mods installed). For some reason, the game crashes whenever I try to use summon steed. I tried uninstalling mods recently installed and ones that seemed to be causing the issue in the crash report, but to no avail. Here's the 3 different crash reports, does anyone know what's happening?
[crash-2023-12-28_17.58.07-server.txt](https://github.com/baileyholl/Ars-Nouveau/files/13789987/crash-2023-12-28_17.58.07-server.txt)
[crash-2023-12-28_16.55.52-server.txt](https://github.com/baileyholl/Ars-Nouveau/files/13789990/crash-2023-12-28_16.55.52-server.txt)
[crash-2023-12-27_22.07.35-server.txt](https://github.com/baileyholl/Ars-Nouveau/files/13789991/crash-2023-12-27_22.07.35-server.txt)

**Comment by youriolatus** [comment]
Yea omg I have the same issue. Everytime I try to summon a steed it summons a horse and half a second after it freezes and crashes the game. Can anyone please help this issue?

**Comment by Hexasan** [comment]
Same here, my Valhelsia 5 server with updated versions of ars + addons of ars crashes when I cast summon steed
