### ISSUE TITLE
Feature Request: Archwood Config

### ISSUE THREAD

**Issue by TheCowKing-moo** [baileyholl/Ars-Nouveau#121]
Being able to tune the generation would be greatly appreciated. Currently the trees spawn a bit too much for my preference in world generators such as Terraforged. 

Perhaps a way to configure which biome(s) they can spawn in?

**Comment by baileyholl** [comment]
Added here: https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3156519

**Comment by RejectedTM** [comment]
I think this issue should be reopened as `TREE_SPAWN_RATE` has since been set to a constant. I think being able to configure the spawn weight of archwood trees is especially important for players using terrain gen and LOD mods, where so many archwood trees might look jarring.
