### ISSUE TITLE
Have spell turrets use a fake player based on who last changed its spell

### ISSUE THREAD

**Issue by Pitfallingpat** [baileyholl/Ars-Nouveau#1212]
I recently ran into an incompatibility / bad interaction with spell turrets on a server running FTB chunks, all spell turrets use "ars_nouveau" for any fake player interactions which causes an all or nothing situation with chunk protection on my server, players have to risk allowing any spell turret from any player to effect their area or none at all. Create and other mods have been able to tie their fake players to the user who placed their block that will be interacting with the world which plays nice with FTB chunk permissions. This also occasionally affects single players who don't understand fake players but use FTB chunks for chunk loading.

**Comment by baileyholl** [comment]
This is now in the latest version
