### ISSUE TITLE
[Suggestion] Better visual feedback when commanding starbunkles

### ISSUE THREAD

**Issue by TheDeviantCrafter** [baileyholl/Ars-Nouveau#1213]
Right now, commanding a starbunkle only spawns chat messages. It will stand perfectly still until it performs an action such as moving an item. This adds a bit of a learning curve since it's not always clear at a glance if you set up the starbunkle correctly.

Here are a few possible changes:

1. When the player binds a starbunkle to an inventory, the it will stare at that inventory for a few seconds.
2. Starbunkles share their head in confusion when their memory is cleared.
3. Looking at a starbunkle while holding a dominion wand causes a line of particles to spawn that connect it to any linked inventories. Particles move away from inventories set to extract and towards inventories set to insert.

**Comment by baileyholl** [comment]
Starbuncles will highlight their positions when selected with the dominion wand, using the same particles as scrying.
