### ISSUE TITLE
Starbuncle memory leak

### ISSUE THREAD

**Issue by DBotThePony** [baileyholl/Ars-Nouveau#1216]
After reading and checking i can't see why this doesn't work the way it should
https://github.com/baileyholl/Ars-Nouveau/blob/6f1cb58a783c7b5bf623878a7de9328e1f67cbc9/src/main/java/com/hollingsworth/arsnouveau/common/entity/debug/FixedStack.java#L17

There is also `removeElementAt` method:
![oJ090Wrc4N](https://github.com/baileyholl/Ars-Nouveau/assets/6339511/673db6e4-5472-494e-b9e8-c5bf89fd7e95)

------------

Any reason why you don't use `Deque<>` implementations (example: `ArrayDeque<>` or `LinkedList<>`), and instead use `Stack<>`? `LinkedList<>` works really good when list is relatively small and you do a lot of push/pop on both sides of deque

https://github.com/baileyholl/Ars-Nouveau/blob/6f1cb58a783c7b5bf623878a7de9328e1f67cbc9/src/main/java/com/hollingsworth/arsnouveau/common/entity/Starbuncle.java#L94

![3CW5biYuUW](https://github.com/baileyholl/Ars-Nouveau/assets/6339511/22aaa955-cdeb-4d82-b52b-cdb916251f9b)

![seoVp5xpi1](https://github.com/baileyholl/Ars-Nouveau/assets/6339511/5e008074-6b97-4922-a820-70cab4960545)
![69UV743wCx](https://github.com/baileyholl/Ars-Nouveau/assets/6339511/6bf7fafb-bf3d-4b34-8c9d-31666c6dd2ff)

![j7o6A7m2Yj](https://github.com/baileyholl/Ars-Nouveau/assets/6339511/c6f8f3c2-7dd4-4d02-9bcd-d3f4cd657bf4)

**Comment by baileyholl** [comment]
Hello, thank you for looking into this.

What version are you testing on? I tested by adding 1,000 elements to the debugger and only see 100 logged to the file. 

```java
    @Override
    public InteractionResult useOn(UseOnContext context) {
        if (!context.getLevel().isClientSide) {
            try {
                // Write the file
                Path path = Paths.get("ars_nouveau", "entity_log_" + System.currentTimeMillis() + ".log");
                File file = path.toFile();
                Files.createDirectories(path.getParent());
                PrintWriter w = new PrintWriter(new FileWriterWithEncoding(file, "UTF-8", false));
                EntityDebugger debugger = new EntityDebugger(new Starbuncle(context.getLevel(), true));
                for (int i = 0; i < 1000; i++) {
                    debugger.addEntityEvent(new DebugEvent("test" + i, "test" + i));
                }
                debugger.writeFile(w);
                System.out.println(debugger.events.size());
                w.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        return super.useOn(context);
    }
```

The file maintains the 900th to 999. 

The implementation for remove and removeAt are nearly identical.
```java
   /**
     * Removes the element at the specified position in this Vector.
     * Shifts any subsequent elements to the left (subtracts one from their
     * indices).  Returns the element that was removed from the Vector.
     *
     * @param index the index of the element to be removed
     * @return element that was removed
     * @throws ArrayIndexOutOfBoundsException if the index is out of range
     *         ({@code index < 0 || index >= size()})
     * @since 1.2
     */
    public synchronized E remove(int index) {
        modCount++;
        if (index >= elementCount)
            throw new ArrayIndexOutOfBoundsException(index);
        E oldValue = elementData(index);

        int numMoved = elementCount - index - 1;
        if (numMoved > 0)
            System.arraycopy(elementData, index+1, elementData, index,
                             numMoved);
        elementData[--elementCount] = null; // Let gc do its work

        return oldValue;
    }
```

**Comment by DBotThePony** [comment]
ars_nouveau-1.19.2-3.22.2

**Comment by DBotThePony** [comment]
This was fixed via https://github.com/baileyholl/Ars-Nouveau/commit/ee6638bb771447944435cd1a87580997272763ec
