### ISSUE TITLE
Possible issue w/ CoreProtect causing items to disappear when using Fell spell

### ISSUE THREAD

**Issue by aidenpike** [baileyholl/Ars-Nouveau#1222]
This could also be on CoreProtect's end, but when I use the spell Fell on any tree, the items don't appear until I break another block. I checked to see if a tick update could cause it, but nothing else worked. Additionally, using Fell on a blazing archwood tree and then breaking a block will not drop any blocks at all.

**Version:** 1.20.1

**Comment by Jarva** [comment]
CoreProtect is a plugin, this would mean you're running on Hybrid Server Software which isn't supported by most mod/plugin developers because they're not made to interact with each other.

**Comment by aidenpike** [comment]
> CoreProtect is a plugin, this would mean you're running on Hybrid Server Software which isn't supported by most mod/plugin developers because they're not made to interact with each other.

Host is saying it may also be ArcLight, but the point stands nonetheless. Do you have any recommendations for fixing such an issue?

**Comment by Jarva** [comment]
My only advice is to report the issue to Arclight and hope for the best

**Comment by aidenpike** [comment]
> My only advice is to report the issue to Arclight and hope for the best

We're switching to Magma to see if that does the trick. After some time I realized that magebloom bushes have the same behavior, and at one point another non-AN block was doing the same thing, so it's definitely not an issue on the mod's end.

Thanks!
