### ISSUE TITLE
HORIZONTAL PORTAL SIZE // NORTH ONLY ACTIVATION // HORIZONTAL PORTAL BREAK

### ISSUE THREAD

**Issue by PantACRO4life** [baileyholl/Ars-Nouveau#1223]
- Portal frame of 23x23 can be activated if vertical but not horizontal.
- Activating the portal only work with the scroll dropping from the North side of the frame.
- Horizontal portal break if click with the wand or a block is placed anywhere but the North side (first row).

@baileyholl , Look at the 2 videos. I made a setup in creative to demonstrate the issue. 

Video No1 : https://youtu.be/RA6W0MuvHMs
Video No2 : https://youtu.be/re6beQCcOqc

Only Ars Nouveau and Curios API were installed.

MC Version: 1.20.1
Forge Version: 47.2.20

Ars Version: 4.9.0
Curios API Version: 5.7.0+1.20.1

Config Files Default.

**Comment by baileyholl** [comment]
fixed in latest
