### ISSUE TITLE
Crash when crafting glyph: Create Terrain

### ISSUE THREAD

**Issue by Tonomo** [baileyholl/Ars-Nouveau#1224]
[crash-2024-02-11_17.16.50-server.txt](https://github.com/baileyholl/Ars-Nouveau/files/14233106/crash-2024-02-11_17.16.50-server.txt)

Crash happens when you click the glyph: Create Terrain and can see the items hovering above the crafting station. Any attempt to rejoin the world afterwards will also result in an instant crash.

**Comment by baileyholl** [comment]
Super late response, but this is from Primal Magick's WandCharger having an invalid inventory, which the scribes tbale auto pulls from.
