### ISSUE TITLE
Obtainable Budding Amethyst blocks

### ISSUE THREAD

**Issue by SonZir0** [baileyholl/Ars-Nouveau#1228]
This issue was already (although very briefly) touched upon in issue #892, but rather than question if this block should even drop at all through "Pull" or "Gravity" gimmicks, that discussion came down to how easy (or not) it is to access certain materials for the glyph recipes themselves and whether or not they should be re-adjusted.

I don't propose to change any recipes or core mechanic (the whole "Silk Touch with extra steps" thing is irrelevant); the only point of concern here is the Budding Amethyst block, which players are not supposed to be able to get at all, much like bedrock or end portal frame blocks. Minecraft developers tried to make these blocks unobtainable through usual means: you can't get them with a Silk Touch Pickaxe, and you can't move or drop them as an item with a piston either. There's only one difference between them: budding amethyst blocks break rather easily, while bedrock and end portal blocks don't.

Ars Nouveau spells allow us to circumvent that, and now, instead of setting up an outpost and securing the area deep inside the cave as Minecraft developers intended, people can just raid a few Amethyst Geodes, and they're basically set up for the rest of their playthrough. Is that intended? How hard would it be to add some sort of check to break Budding Amethyst blocks instead of pulling them in any direction?

If it is actually intended to be this way, then feel free to close this issue.

**Comment by Alexthw46** [comment]
If you make an ameth golem by converting one budding block, it will convert normal blocks into budding over time. Being able to "glitch" the budding only speed up the process of setting up the golem farm afterall. 

If a modpack wants to delay the awakening ritual and force the player to vanillish behavior, there is ars_nouveau:gravity_blacklist that will cancel the item drop of the falling block

**Comment by SonZir0** [comment]
I'll admit, amethyst golems completely slipped my mind up to this point, so this is not as big of an issue as I thought it was. That said, I really wanted more vanillish behavior in the matter, so gravity_blacklist property is exactly something I've been looking for.

Thank you so much for your response, that's the end of it.
