### ISSUE TITLE
Crash in Enigmatica 6

### ISSUE THREAD

**Issue by SpookyGrian** [baileyholl/Ars-Nouveau#123]
Hi! I loaded a creative world solely to use Create 0.3 in Enigmatica 6, no modifications to the pack at all. I loaded in, went walking for a bit, and crashed. The crash report mentioned a rendering error on a carbuncle, so I submitted it here. At the time of crash, I had my inventory open and had been hovering over a create item in JEI. Please let me know if additional information is needed!
Ars nouvea version 1.9.3
Enigmatica 6 version 0.3.2
Forge version 35.1.13
[crash-2020-12-31_20.01.21-client.txt](https://github.com/baileyholl/Ars-Nouveau/files/5758605/crash-2020-12-31_20.01.21-client.txt)

**Comment by NillerMedDild** [comment]
I recommend that you update to 0.3.4, this issue is most likely fixed :)
