### ISSUE TITLE
Crash From Opening Storage Lectern Crafting Terminal

### ISSUE THREAD

**Issue by Ivy31415** [baileyholl/Ars-Nouveau#1232]
"at TRANSFORMER/ars_nouveau@4.9.0/com.hollingsworth.arsnouveau.client.container.CraftingTerminalScreen.m_181908_(CraftingTerminalScreen.java:144)"

Can provide full crash log if neccessary

Edit: tested with assigning the lectern to an empty container, crash still occured. I don't know what mod could be causing this, possibly EMI/JEI though I have been using those with ars without issue previously, so I'm unsure what is causing the issue.
The only ars addons I have are Ars Creo, Ars EC compat, and Ars Energistique (AE2 compat)

Edit 2: It is a mod conflict between (most likely) Ars Nouveau and one of these mods:
Adaptive Performance Tweaks Series
AI Improvements
Datapack Reload Helper
Load My Resources
Shut Up GL Error
Smoothboot Reloaded
Visual Overhaul

**Comment by Vaelzan** [comment]
It's Visual Overhaul. That's also the pinned issue, and this is a duplicate.

https://github.com/baileyholl/Ars-Nouveau/issues/1161
