### ISSUE TITLE
[1.19.2] Crash on single player startup

### ISSUE THREAD

**Issue by HoottooH** [baileyholl/Ars-Nouveau#1237]
Here's the log!
[crash-2024-03-06_02.25.27-server.txt](https://github.com/baileyholl/Ars-Nouveau/files/14506438/crash-2024-03-06_02.25.27-server.txt)
There seems to be issues with the config. Once I deleted the folder so it could rebuild, it started throwing:

net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigLoadingException: Failed loading config file ars_nouveau-server.toml of type SERVER for modid ars_nouveau

BEFORE resetting the config, it would throw this:

net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigLoadingException: Failed loading config file ars_nouveau/glyph_self.toml of type SERVER for modid ars_nouveau
Here's that log:
[crash-2024-03-04_23.16.12-server.txt](https://github.com/baileyholl/Ars-Nouveau/files/14506512/crash-2024-03-04_23.16.12-server.txt)

**Comment by baileyholl** [comment]
There is a folder of glyph configs and several top level configs in the configs folder. You will need to delete those in the configs folder as they are corrupted as well.
