### ISSUE TITLE
Bugreport: Projectile - Place block [Sign]

### ISSUE THREAD

**Issue by saforer** [baileyholl/Ars-Nouveau#124]
I love the mod, and I'm glad to see it starting out. THank you. To fly around with a spell called yump that we made of self leap launch slowfall and whatnot. This is going in any modpack of any version I support from here on 'cause it's a lot of fun.

Anyway, Building a small blood magic area and needed to fill in some blocks that were out of reach. Not a problem! I have cobblestone in my inventory and my hotbar is [Sentient sword] [Book] [Signs] [Cobblestone] and it'll ignore the sign. Craft up an extendo arm spell of Projectile - Place Block and rightclick. I expected it to go "we can't place signs from a distance" in the same way it goes "you can't place sentient swords from a distance", Instead the server crashed and I think that's because it tried to open the sign interface.

Is there any other info you would need to replicate this?

**Comment by saforer** [comment]
Also, upon reloading the server and rejoining, the sign was, infact, placed.

**Comment by baileyholl** [comment]
Fixes in 1.10.3, releasing today. Thank you
