### ISSUE TITLE
How do I use a flask cannon?

### ISSUE THREAD

**Issue by Noz-Eternis** [baileyholl/Ars-Nouveau#1245]
Whenever I right click, the flask just says that I have no potions in my inventory even though I have 3 flasks, multiple splash potions and 2 normal potions. When I open the radial menu and select a potion, my character just drinks the potion. Am I doing something wrong?

**Comment by baileyholl** [comment]
You have the alchemists crown attached if you are drinking it. Press 'v' while holding the flask cannon to pull up its radial.
