### ISSUE TITLE
Self-Knockback always breaks

### ISSUE THREAD

**Issue by TheMasterJecht** [baileyholl/Ars-Nouveau#1246]
I don't understand why or when, but at some point during every playthrough, on any version (I've tried 1.16.5, 1.18.2 and 1.19.2 so far), Self-Knockback stops working. It does nothing while standing and it pulls you to the ground if mid-air, while also removing momentum.
It still works with Touch or Projectile, though.

The issue disappears if you create a new world but then reappears after some time. It makes the spell ever more of a lesser version of Leap.

**Comment by baileyholl** [comment]
I do not know why that would occur, but knockback works akin to damage knockback. If you have knockback resistance or immunity that would make it non-functional.
