### ISSUE TITLE
Damage spells will not AOE or Pierce

### ISSUE THREAD

**Issue by spdkils** [baileyholl/Ars-Nouveau#125]
I tried to use an AOE to make a better mob farm spell.. Will not AOE ignite spiders.
I tried to use Pierce to hurt multiple mobs at once in a line with peirce.. Does not hit multiple targets...

I'd also suggest you make a self harm AOE and AOE around the player.
Same with self ignite...
any offensive spell used on the player should be a range 0 AOE at the player...
any defensive spell should be the same, and just have AOE increase the range...

Then have it consume mana per target affected to compensate for the massive abuse it may cause by casting regen on 30 players.

**Comment by Darth-Pikachu** [comment]
We have come across the same issue
