### ISSUE TITLE
Can't make Warp Portals from Soucestone or its variants.

### ISSUE THREAD

**Issue by Furious1964** [baileyholl/Ars-Nouveau#1253]
Using the latest version of the mod (Version 4.10.0) with ATM 9 (Version 0.2.54) and I can't make any Warp Portals whatsoever. I make a portal out of Sourcestone, place a Source Jar next to it and throw a Warp Scroll into the frame and nothing happens....no Source is used and the scroll doesn't vanish.

Can the Warp Portals be used to travel to another dimension?

**Comment by Jarva** [comment]
Stabilized Warp Scrolls can be used to travel to other dimensions but normal warp scrolls can't.

You should be able to make Warp Portals with any kind of sourcestone, as long as the scroll is valid.
