### ISSUE TITLE
Harvest spell is broken

### ISSUE THREAD

**Issue by KamiSami** [baileyholl/Ars-Nouveau#128]
Hi, yeah, basically the title... So... The thing is... I was trying to harvest wheat from the little WIP house my friend has been making, so i added some AoE so i can harvest all plants possibly at once, but guess what? The harvest spell BROKE ALL BLOCKS. ...Why? x.x;

Using ars noveau version 1.10.4

**Comment by DerringersMods** [comment]
Harvest vein-mines tree blocks, which includes logs. This can have unfortunate results if a log cabin is in the area of effect.

**Comment by baileyholl** [comment]
has been toned down here: https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3174543
