### ISSUE TITLE
[1.20.1] Request: Config option for disabling intro fanfare

### ISSUE THREAD

**Issue by son0fether** [baileyholl/Ars-Nouveau#1284]
The intro fanfare, or whatever the term is within the mod, is a long musical sequence that plays the first time a player joins a world with Ars Nouveau loaded.  The fanfare is louder than monsters being right next to the player, and lasts for quite a while.  Its volume is set using the hostile mobs sound selector, not music or even ambient sound, so normal sound settings would have it at full volume with other things turned down.

Please add a config option to disable the intro fanfare for MC 1.20.1.  I am making a modpack, and I believe that the people I'm making it for would consider it extremely jarring.  I'm also worried that someone might get hearing damage if they were using headphones.  

Thank you.

An additional option that might be nice would be a quieter version of the intro.

**Comment by baileyholl** [comment]
This mod doesn't add any intro music.

**Comment by son0fether** [comment]
Some mod I've got is causing a fanfare when Ars Nouveau is installed and not doing it when Ars Nouveau is not installed.  I have to create entirely new worlds to test this so it's taking time to figure it out.  I couldn't find the fanfare music inside the Ars Nouveau jar, so I trust what you're saying.  I suspect some integration mod that I haven't disabled.  I'll keep looking.

**Comment by son0fether** [comment]
Update: it's from an add-on to Aquamirae, that adds boss music to that mod:
https://www.curseforge.com/minecraft/mc-mods/aquamirae-mod-music

The 'triumph' music for killing the boss plays on first login, but only if both Ars Nouveau and Destroy (and Create) are also installed.  I don't think that's a problem with Ars Nouveau, so feel free to close this.

**Comment by baileyholl** [comment]
Huh, weird.
