### ISSUE TITLE
1.20.1 | Ars Nouveau (4.10.0) | Abuse loot from hostile mobs, with the help of drogmas

### ISSUE THREAD

**Issue by DesiRe234** [baileyholl/Ars-Nouveau#1294]
**Detailed description of the problem:**
The bottom line is that drygmas should interact only with peaceful creatures, but they also interact with hostile ones, which is why, having only one creature (cyclops, hydra, etc., as an example), it will be possible, albeit slowly, but infinitely to get resources from them with the help of drygmas.

**Tags:**
'art_nouveau:drugmy_charm' - The mascot of drugma
'art_nouveau:drugmy_stone' - Drygma's Dugout

**Video:**
https://youtu.be/vWVSI3yD8DA
https://youtu.be/bfwqIlgrO3g

**Comment by baileyholl** [comment]
There is a blacklist config to remove mobs from the loot pool.
