### ISSUE TITLE
1.20.1 | Art Nouveau (4.10.0) | The creative jug with the source is not mined by anything

### ISSUE THREAD

**Issue by DesiRe234** [baileyholl/Ars-Nouveau#1295]
**Detailed description of the problem:**
When trying to get a Creative jug with a source with any tool (tested with a hand, pickaxes, a disassembler), it simply disappears and is not extracted. The rest of the pitchers fall even if you break them with your hand.

**Tags:**
'art_nouveau:creative_source_jar'

**Comment by baileyholl** [comment]
This was added in the latest version.
