### ISSUE TITLE
[1.20.1] Bookwyrm Charms named at an anvil creates a chunk ban when used at a Storage Lecturn

### ISSUE THREAD

**Issue by junofoppy** [baileyholl/Ars-Nouveau#1296]
This is my first time writing a bug report on github, sorry if I am missing any etiquette.

![image](https://github.com/baileyholl/Ars-Nouveau/assets/164414878/d29344d4-49be-46b5-b546-af1cb1e883d3)
This was the first iteration of the error message I received when using the named bookwyrm charm on a storage lecturn. I had specifically killed the bookwyrm when it was unnamed to get the charm back to rename it in the hopes of giving it a name as i lacked any name tags or access to a tier 2 spellbook.
![image](https://github.com/baileyholl/Ars-Nouveau/assets/164414878/9447e3d3-7505-46b5-b142-db3608e5dacc)
It then started showing me this error.

I found out this was affecting others who were trying to join the server as now it kicks anyone who happens to load the chunks where I tried to spawn the bookwyrm.

If you need any additional information I will be happy to oblige.

**Comment by Jarva** [comment]
Can you provide client and server logs showing the crash?
