### ISSUE TITLE
Idea add a command that gives a glyph

### ISSUE THREAD

**Issue by Acat1234** [baileyholl/Ars-Nouveau#1301]
I want it so I can get all of them quickly without using creative spell book cuz reasons

**Comment by baileyholl** [comment]
This has been added

**Comment by Quezler** [comment]
Came here looking for such a command, its not immediately obvious but just press enter and do not select a suggested one:

![Screenshot 2025-04-13 at 18 31 32](https://github.com/user-attachments/assets/0dbd0e68-cd80-498f-b313-bdfbc016ff77)

https://github.com/baileyholl/Ars-Nouveau/pull/1269/files#diff-63e3ab983cc5d543254958d071dafff43d2e47a2edc5614c9122ffb7f895f2ecR51
