### ISSUE TITLE
[1.20.1] Warp Portal player facing direction

### ISSUE THREAD

**Issue by felipefloresfaf** [baileyholl/Ars-Nouveau#1305]
I noticed that warp portals in version 1.20.1 do not save the direction the player was facing when the warp scroll was created (when player goes through the portal they come out facing the direction they were facing when entering the portal which is very annoying in most cases), and in version 1.19.2 they do remember. 

Is it perhaps intentional since it's been like this since the first 1.20 version?
If so is there somewhere in the code where I can change it and recompile myself?

Thanks for you time.

**Comment by Cragsand** [comment]
Looks like this bug is back in version 1.20.1-4.12.1

**Comment by Cragsand** [comment]
Looks like this bug is back in version 1.20.1-4.12.1 @baileyholl
