### ISSUE TITLE
Crash on World startup after updating. Loot table issue?

### ISSUE THREAD

**Issue by border999** [baileyholl/Ars-Nouveau#1308]
ars_nouveau-1.20.1-4.11.0
https://gist.github.com/border999/8ca25fd66d51562c73e14149d3188fac

**Comment by hisakid** [comment]
Seconded. For more info, it looks like it happens when Ars Additions is installed.

**Comment by evhub** [comment]
Getting a similar issue (and don't have Ars Additions installed): https://gist.github.com/evhub/98fa94b2aaa4b072680ffba9845c355a
