### ISSUE TITLE
Server crash (single server tick took 60.00 seconds (should be max 0.05))

### ISSUE THREAD

**Issue by asdhuman-dev** [baileyholl/Ars-Nouveau#1311]
Server dying when world loaded
Any ways to fix that before bugfixes?

[crash-2024-06-03_13.40.06-server.txt](https://github.com/user-attachments/files/15534728/crash-2024-06-03_13.40.06-server.txt)

**Comment by asdhuman-dev** [comment]
Player provided what they did, maybe it will be helpful. They used the spell on minecraft:chicken

![CleanShot 2024-06-03 at 16 53 31](https://github.com/baileyholl/Ars-Nouveau/assets/48507580/bfc5031d-74cd-4201-a984-f1078e2d51cf)
![CleanShot 2024-06-03 at 16 53 45](https://github.com/baileyholl/Ars-Nouveau/assets/48507580/02af77f2-1014-44e4-98fa-5e8bc40a8785)
![image](https://github.com/baileyholl/Ars-Nouveau/assets/48507580/8f350355-e8e3-4aa9-8fe7-d2b1bcc7ec55)

**Comment by baileyholl** [comment]
Those are watchdog crashes that occur when a single tick takes too long. The spell you have created is likely recasting a high number of spells, bringing the TPS down significantly. The spell includes addons which are not in my control, but you can report them to their specific authors.
