### ISSUE TITLE
The server crashed while working near the withered skull using Drygmy.

### ISSUE THREAD

**Issue by Qiong-Mengzi** [baileyholl/Ars-Nouveau#1328]
This is a partial error message from our server console (published by the server administrator).

![image](https://github.com/baileyholl/Ars-Nouveau/assets/165121660/7a0c28d6-e0f0-4bcc-b08c-5cff22701bac)

The version of the Ars Nouveau module we installed is 2.9.0

(I forgot to place a box next to the Drygmy stone formation) The server crashed within a few minutes of placing the magic source jar.

I would like to know the cause and solution of the server crash, thank you.

**Comment by Qiong-Mengzi** [comment]
(I apologize for the translation error.)

The 'withered skull' in the title should be changed to 'Wither Skeleton'.

**Comment by baileyholl** [comment]
1.18 is no longer supported.
