### ISSUE TITLE
Armor not showing up

### ISSUE THREAD

**Issue by Rebether** [baileyholl/Ars-Nouveau#1329]
Armor just not showing up. I dont have an optifine, replaced it with Rubidium. But armor still now shows up even if i dont have a Rubidium. Idk what to do. 
![2024-06-23_15 54 09](https://github.com/baileyholl/Ars-Nouveau/assets/150285462/dbc64188-f540-4f64-b30e-4caebde2a576)

**Comment by Rebether** [comment]
Forgot to mention: Forge 1.20.1 47.30.0 and version of the mod is 4.12.1.

**Comment by baileyholl** [comment]
I would swap rubidium for embeddium, it is better supported.
