### ISSUE TITLE
Starbuncle charms sometimes have empty NBT tags, preventing them from stacking properly even when they have no memory

### ISSUE THREAD

**Issue by TheDeviantCrafter** [baileyholl/Ars-Nouveau#1332]
![image](https://github.com/baileyholl/Ars-Nouveau/assets/18755309/6f351ed4-8306-4525-913a-c26f59ad2e40)

Freshly crafted starbuncle charms have no NBT data.

Starbuncle charms that have been placed in the world and immediately killed have an empty behavior NBT tag. CraftTweaker's `/ct hand` reveals the following:

`<item:ars_nouveau:starbuncle_charm>.withTag({behavior: {id: "ars_nouveau:starby_transport"}})`

Starbuncle charms that have been placed in the world, bound to an inventory, mind wiped, and then killed have a second empty `itemScroll` NBT tag. Running `/ct hand` on this item reveals the following:

`<item:ars_nouveau:starbuncle_charm>.withTag({behavior: {id: "ars_nouveau:starby_transport", itemScroll: {id: "minecraft:air", tag: {"bountiful:bounty_data": "{}"}, Count: 0}}})`

Empty NBT tags should be removed so all starbuncle charms with no memory stack together.

**Comment by TheDeviantCrafter** [comment]
The same issue occurs with source jars. Crafting one, placing it, and immediately breaking it again creates a "0% full" NBT tag that prevents it from stacking with freshly crafted jars.

The `/ct hand` syntax is as follows:

`<item:ars_nouveau:source_jar>.withTag({BlockEntityTag: {source: 0, id: "ars_nouveau:source_jar", Items: []}}) * 2`

**Comment by baileyholl** [comment]
This is fixed in 1.21. May be backported to 1.20
