### ISSUE TITLE
Shift + Scroll to change spells

### ISSUE THREAD

**Issue by cobbkris** [baileyholl/Ars-Nouveau#134]
Can you add an option to SHIFT + Scroll to change the active spell in the spell book?  Many other mods use this method and is much more convenient for quick use.  Apologies if this has been added in a new update already.

**Comment by parandar** [comment]
I love the idea, it would be way easier to swap spells quickly.
You could change your post to "enhancement" and not an open issue tho

**Comment by cobbkris** [comment]
> You could change your post to "enhancement" and not an open issue tho

The owner has to do this, I do not see a way to change the label.
