### ISSUE TITLE
LightBlocks have a high tick impact

### ISSUE THREAD

**Issue by Castone22** [baileyholl/Ars-Nouveau#1341]
Versions:
NeoForge 1.20.1-47.1.104
ars_nouveau-1.20.1-4.10.0-all

Replication:
1. Create ~1.5k ars lights, as players will do
2. run observable, 
3. check aggregates, example
https://observable.tas.sh/p/X1LI/aggregated

**Comment by Jarva** [comment]
Run a spark profile, Observable is known to misappropriate lag. The LightBlocks only tick on clients.

**Comment by Castone22** [comment]
Spark shows something about a light tile, but the tick is negligible.  Going to close.
