### ISSUE TITLE
lava lillies

### ISSUE THREAD

**Issue by WindyJellyfish** [baileyholl/Ars-Nouveau#1347]
despite what was said in the last report on this issue, lava lilies seem to not exist in 1.20.1, which is weird, can;'t find them even with a command to give item

**Comment by JavidNoshadi** [comment]
i do believe the problem comes from volcanic sourcelink. they dont generate source either.

**Comment by baileyholl** [comment]
They were removed starting with 1.20, a new block will replace them.
