### ISSUE TITLE
[1.21 neoforge] In new world, no Ars Nouveau loot found in chests

### ISSUE THREAD

**Issue by ekarlsso** [baileyholl/Ars-Nouveau#1357]
Versions:

Minecraft 1.21
NeoForge: 21.0.133
Ars Nouveau: ars_nouveau-1.21.0-5.0.3-all.jar

Started a new world (with Ars version 5.0.1 and then updated to 5.0.3). Have found lot of chests from

- Sunken boats
- Nether gate ruins
- Dungeons/monster rooms
- Villages
- Treasure map chest

None of these chests have contained any Ars loot. No berries, no wilden drops nor spellbooks. Compared to my last 1.20 world the difference is pretty big. Makes it hard to progress when I haven't found any wilden nest either.  Naturally, I can use summon wilden for some drops. Perhaps this is the intended method?

Mods I use in this world are:

ars_nouveau-1.21.0-5.0.3-all.jar
curios-neoforge-9.0.5+1.21.jar
geckolib-neoforge-1.21-4.5.7.jar
jei-1.21-neoforge-19.5.0.59.jar
shulkerboxtooltip-neoforge-5.0.4+1.21.jar

Question: Is this intended behaviour or is this bug with 1.21 build?

**Comment by CubeTwo** [comment]
same, dont have any loot
ars_nouveau-1.21.0-5.0.5-all
curios-neoforge-9.0.5+1.21
geckolib-neoforge-1.21-4.5.7
jei-1.21-neoforge-19.5.3.67

**Comment by baileyholl** [comment]
This should be resolved in the latest version.
