### ISSUE TITLE
[1.21]Wilden dens dont spawn

### ISSUE THREAD

**Issue by CubeTwo** [baileyholl/Ars-Nouveau#1362]
Wilden dens dont spawn in worlds

ars_nouveau-1.21.0-5.0.5-all
curios-neoforge-9.0.5+1.21
geckolib-neoforge-1.21-4.5.7
jei-1.21-neoforge-19.5.3.67
NeoForge: 21.0.147

**Comment by baileyholl** [comment]
This should be resolved in the latest version.
