### ISSUE TITLE
[1.21] Ars items dont dyeable

### ISSUE THREAD

**Issue by CubeTwo** [baileyholl/Ars-Nouveau#1363]
you cant dye items anymore, books, armors, weapons, ect.

ars_nouveau-1.21.0-5.0.5-all
curios-neoforge-9.0.5+1.21
geckolib-neoforge-1.21-4.5.7
jei-1.21-neoforge-19.5.3.67
NeoForge: 21.0.147

**Comment by Alexthw46** [comment]
fix merged, wait for next release (5.0.8)
