### ISSUE TITLE
[1.21]Ingame documentation dont work

### ISSUE THREAD

**Issue by CubeTwo** [baileyholl/Ars-Nouveau#1364]
In-game documentation don't work, if you try open documentation book it opens site in browser, same with documentation in spell book

ars_nouveau-1.21.0-5.0.5-all
curios-neoforge-9.0.5+1.21
geckolib-neoforge-1.21-4.5.7
jei-1.21-neoforge-19.5.3.67
NeoForge: 21.0.147

**Comment by Papaturts** [comment]
need Patchouli mod for ingame docs-hasnt been updated yet far as im aware

**Comment by baileyholl** [comment]
The latest version will now include patchouli by default.
