### ISSUE TITLE
[1.21]alteration table dont render armor models

### ISSUE THREAD

**Issue by CubeTwo** [baileyholl/Ars-Nouveau#1365]
alteration table don't render armor models
ars_nouveau-1.21.0-5.0.5-all
curios-neoforge-9.0.5+1.21
geckolib-neoforge-1.21-4.5.7
jei-1.21-neoforge-19.5.3.67
NeoForge: 21.0.147
![2024-08-01_17 04 02](https://github.com/user-attachments/assets/42537316-7b18-4220-b982-a4ffbcb75006)

**Comment by ekarlsso** [comment]
For me it renders incorrectly everything I have

<img width="2125" alt="image" src="https://github.com/user-attachments/assets/738976bb-bf00-4cec-b0cf-8e5253a40129">


Here I just have a battlemage's gambenson

mods:
XaerosWorldMap_1.38.8_NeoForge_1.21.jar
Xaeros_Minimap_24.2.1_NeoForge_1.21.jar
ars_nouveau-1.21.0-5.0.3-all.jar
curios-neoforge-9.0.5+1.21.jar
geckolib-neoforge-1.21-4.5.7.jar
jei-1.21-neoforge-19.5.0.59.jar
shulkerboxtooltip-neoforge-5.0.4+1.21.jar

**Comment by ffuentesm** [comment]
This has been fix in the latest version.
