### ISSUE TITLE
[1.21 neo] No belt slot available 

### ISSUE THREAD

**Issue by ekarlsso** [baileyholl/Ars-Nouveau#1368]
Minecraft 1.21
NeoForge: 21.0.133
Ars Nouveau: ars_nouveau-1.21.0-5.0.3-all.jar

<img width="430" alt="image" src="https://github.com/user-attachments/assets/c0b3d4ae-fd87-448f-b9f2-fc6f21a56f20">

Mods installed

XaerosWorldMap_1.38.8_NeoForge_1.21.jar
Xaeros_Minimap_24.2.1_NeoForge_1.21.jar
ars_nouveau-1.21.0-5.0.3-all.jar
curios-neoforge-9.0.5+1.21.jar
geckolib-neoforge-1.21-4.5.7.jar
jei-1.21-neoforge-19.5.0.59.jar
shulkerboxtooltip-neoforge-5.0.4+1.21.jar
worldedit-mod-7.3.5.jar

**Comment by baileyholl** [comment]
This should be resolved in the latest version.
