### ISSUE TITLE
Can’t upgrade to Reactive 2 enchantments

### ISSUE THREAD

**Issue by posburn75** [baileyholl/Ars-Nouveau#137]
Enchanting apparatus is set up properly (since I was able to get Reactive 1), but nothing happens when I sneak and right click. Top left pedestal contains spell scroll, 3 Amplify glyphs flank the scroll. Is this a bug or am I doing something wrong? Nothing in my off-hand, and three full mana jars nearby.

**Comment by Cpt-Krakenecks** [comment]
Hi, I don't have a solution I'm afraid, but I'm stuck on the reactive 1 enchantment, how do you set it up, I can't find any recipes

**Comment by baileyholl** [comment]
There is a recipe on the second page of the book, right after the recipe for Reactive 1. Put your reactive 1 recipe in the apparatus, use those items listed on the reactive 2 enchant, and that will upgrade it.
