### ISSUE TITLE
too many ars entities

### ISSUE THREAD

**Issue by FUYUYI** [baileyholl/Ars-Nouveau#1370]
my sever  lag over time because ars_nouveau: follow_proj:50261 ，is there a way to solve problem,
entities always spawn in Source Jar near Timer Spell Turret and Agronomic Sourcelink (Glyph of Grow Glyph of AOE*3)

**Comment by baileyholl** [comment]
What version?

**Comment by FUYUYI** [comment]
1.20.1

**Comment by FUYUYI** [comment]
4.11.0,forge:47.3.1

**Comment by luo-zi** [comment]
maybe add an switch wand,it can use for hide the particle of machine.
that would be useful.

**Comment by FUYUYI** [comment]
its eneity，will switch wand work

**Comment by FUYUYI** [comment]
entity*
