### ISSUE TITLE
Den Mobs teleporting-spawning elsewhere???

### ISSUE THREAD

**Issue by Papaturts** [baileyholl/Ars-Nouveau#1372]
Has anyone had this happen in 1.20.1?
ars-1.20.1-4.12.3
the only thing that was weird was that I hit one of their dens off to the west and like they didn' tmove
like frozen
I grabbed a chest and flew back on my broom-hexerie broom
and then they nailed me
from another player on a Hardcore server
currently only addon is ars artillery
![2024-08-04_21 37 11](https://github.com/user-attachments/assets/31c9b684-40f7-41a6-a1e4-74c8389b785f)
[Hardcore-V1.1.zip](https://github.com/user-attachments/files/16490280/Hardcore-V1.1.zip)
for the modpack

**Comment by baileyholl** [comment]
They do not have the ability to teleport, but if you built your home on a den they will spawn as part of the structure.
