### ISSUE TITLE
[bug 1.19.2] wrong ingredients might freeze the game

### ISSUE THREAD

**Issue by 2929762171** [baileyholl/Ars-Nouveau#1381]
this fine,
![image](https://github.com/user-attachments/assets/584bc88c-26c0-42a6-bdd4-3b0db66ad3f2)
but this will freeze the game:
![image](https://github.com/user-attachments/assets/378acbac-2a77-455f-87c0-05398bb8efaf)

seems to happen when too many irrelevant ingredients.
no crash report, just freeze.

**Comment by baileyholl** [comment]
I cannot reproduce this in 1.21. Only 1.20 and 1.21 are currently updated, so this was likely either fixed or a different conflict.
