### ISSUE TITLE
[1.21] Armor not enchantable in table

### ISSUE THREAD

**Issue by Sloner42** [baileyholl/Ars-Nouveau#1387]
NeoForge: 21.0.167
jei-1.21-neoforge-19.8.2.99
geckolib-neoforge-1.21-4.5.8
curios-neoforge-9.0.5+1.21.0
ars_nouveau-1.21.0-5.0.7-all
Putting Ars armor in an enchantment table does not give the optons for enchanting:
![2024-08-15_19 01 50](https://github.com/user-attachments/assets/c070a890-79f9-4625-87c9-d22eba061f12)

Expected:
![2024-08-15_19 01 56](https://github.com/user-attachments/assets/58a7a4e3-8935-4bf8-a4bc-49f707f185de)

Combining armor with an enchanted book in an anvil seems to work.

**Comment by ffuentesm** [comment]
I am having the same problem as this. 
Also combining armors in an Avil. They are the same, with the same tier, and no threads. 
Both have enchantments that I want to combine. 
![image](https://github.com/user-attachments/assets/b458c834-fe03-4de0-9d14-db2e1b3ea2f0)
