### ISSUE TITLE
Performance problem after starting automation

### ISSUE THREAD

**Issue by Pardenia** [baileyholl/Ars-Nouveau#1395]
I'm playing now in 1.20.1, but it happened in older versions, when it starts to have too many lights going everywhere the game starts to suffer. I've allocated 10gb already lol.
I would be happy if I could just deactivate some particles and the visual light that goes from one block to another, it gets too much visually too.

**Comment by baileyholl** [comment]
Can you run a spark profile? Particles only render when looking at the source, unless you have a mod that disabled particle culling.

**Comment by Pardenia** [comment]
I'm sorry, this time the problem was between the the screen and the chair lol.
When starting the game I typed 100 instead of 10 to allocate memory. I remember that my game used to have low FPS when I was at my base and the only thing happening there was the automation. It's been a long time since that and I don't have such issue anymore. Everything got reinstalled and newer versions.
