### ISSUE TITLE
Bug Report: Server Crash When Conjuring Block and Shooting with Gravity

### ISSUE THREAD

**Issue by osyra42** [baileyholl/Ars-Nouveau#1397]
**Bug Report: Server Crash When Conjuring Block and Shooting with Gravity**

**Mod Version:** 5.0.10

**Minecraft Version:** 1.20.1

**Modpack:** ATM9 to the Sky v1.0.9 and v1.1.0

**Forge Version:** 47.2.20

**Description:**
When a player conjures a block using the Ars Nouveau mod and then shoots it with a Gravity spell or projectile, the server crashes immediately. This crash happens consistently and can be reproduced by following the steps below.

**Steps to Reproduce:**
1. Conjure a block using Ars Nouveau.
2. Cast a Gravity spell or shoot a projectile imbued with Gravity at the conjured block.
3. Observe the server crash.

**Expected Behavior:**
The conjured block should interact with the Gravity spell or projectile without causing a server crash.

**Actual Behavior:**
The server crashes immediately after the conjured block is hit with a Gravity spell or projectile.

**Crash Report:**
No crash report available.

**Logs:**
No logs available.

**Additional Information:**
This issue was observed in the "ATM9 to the Sky" modpack, versions 1.0.9 and 1.1.0.

**Comment by baileyholl** [comment]
5.0 is for 1.21, not 1.20. I cannot reproduce this in 1.21, please attach a log if you can.
