### ISSUE TITLE
crash Storage Lectern 

### ISSUE THREAD

**Issue by EnotScript** [baileyholl/Ars-Nouveau#1398]
Crashing when try pickup enchanted item from Storage Lectern.
[crash-2024-08-25_22.15.14-client.txt](https://github.com/user-attachments/files/16740930/crash-2024-08-25_22.15.14-client.txt)
[debug.log](https://github.com/user-attachments/files/16740931/debug.log)
[latest.log](https://github.com/user-attachments/files/16740932/latest.log)

ATM10 - 10-0.38
ars-1.21.0-5.0.10-all

**Comment by EnotScript** [comment]
Crash 2 
After binding Storage Lectern to itself. The game allowed this to be done. Consequences: the world does not start- Description: Ticking block entity
[crash-2024-08-25_22.41.03-server.txt](https://github.com/user-attachments/files/16741000/crash-2024-08-25_22.41.03-server.txt)
[debug.log](https://github.com/user-attachments/files/16741001/debug.log)
[latest.log](https://github.com/user-attachments/files/16741002/latest.log)

**Comment by baileyholl** [comment]
Hello, you can enabled 'removeErroringEntities` in the neoforge server config to get back into the world until this is fixed.
