### ISSUE TITLE
Rendering of Skyweave blocks is very inefficient

### ISSUE THREAD

**Issue by Qendolin** [baileyholl/Ars-Nouveau#1399]
For the Skyweave block the game has to render the sky, clouds and rain one extra time each frame. This is very inefficient and also causes issues with other mods that modify the rendering of these elements.

**Comment by Qendolin** [comment]
See https://github.com/baileyholl/Ars-Nouveau/issues/1399

**Comment by baileyholl** [comment]
I am not aware of another way, it is designed to capture the current skybox as is. I would welcome any PRs to potentially improve on it, but this is not something I could promise a change for.
