### ISSUE TITLE
[FORGE] [1.20.1] Armors display bug

### ISSUE THREAD

**Issue by BaruukReze** [baileyholl/Ars-Nouveau#1403]
I'm playing with the mod and Optifine on version 1.20.1 of MC and using Forge as modloader. The armors display is glitched: the helmets appear glitched and the other parts of the armor straight up don't appear. 

After testing it, the bug only happen if I'm using Optifine (version U I6 for Forge 47.2.18)
![2024-08-31_13 20 16](https://github.com/user-attachments/assets/d9252379-c423-4329-a90a-d5afd7d2b3cb)
![2024-08-31_13 20 50](https://github.com/user-attachments/assets/e432b98a-ad26-458c-abdd-bcb3b61bc496)

The bug is purely visual tho, as the armors still work.

**Comment by baileyholl** [comment]
Optifine is not supported for geckolib models.
