### ISSUE TITLE
Grow on Nether wart?

### ISSUE THREAD

**Issue by j-romchain** [baileyholl/Ars-Nouveau#1406]
the grow glyph doesn't work on nether wart, I don't know if this is intentional or not...

while nether wart is not bonemealable in vanilla mc, I feel like the argument that it is an alien plant and so it isn't fertalized by bonemeal doesn't work as much when it comes to magic...

**Comment by j-romchain** [comment]
related issue:
https://github.com/baileyholl/Ars-Nouveau/issues/369

**Comment by baileyholl** [comment]
It is designed to mimic bonemeal only.
