### ISSUE TITLE
Crashing when making a ability or spell

### ISSUE THREAD

**Issue by Gold3n12345** [baileyholl/Ars-Nouveau#1410]
Whenever i try to make a spell with glyphs if i try to click the top my minecraft will crash may i ask why or how do i fix this problem im currently using the version 1.20.1 and the version of Ars Nouveau is 4.9.0

**Comment by Gold3n12345** [comment]
and i added epic fight in the mod i know that epic fight is the problem in others mods but i removed it and still not letting me make a spell

**Comment by baileyholl** [comment]
Please post the crash log.
