### ISSUE TITLE
Is it possible to synchronize the new content of the higher version to the ars of version 1.16.5?

### ISSUE THREAD

**Issue by Langran66** [baileyholl/Ars-Nouveau#1417]
Recently, I've been playing E6E, and the absence of higher-version **Containment Jars** has been a disappointing experience. Could you please update a version that enables all 1.16.5 modpacks to utilize the latest content from ARS, including the latest Containment Jars?

**Comment by baileyholl** [comment]
No, backporting is not trivial. Only 1.20 and 1.21 are currently supported.
