### ISSUE TITLE
Cant find wilden structure

### ISSUE THREAD

**Issue by MOPSKATER** [baileyholl/Ars-Nouveau#1418]
Minecraft 1.21.1
Seed: 7687809446906757477
Ars_Nouveau 5.1.0

I tried for hours to find any wilden structures but I didn't succeed. After that,  I tried with structure compass mod and in told me that it can't find any structure. What to do?

**Comment by baileyholl** [comment]
Only the guardian den appears to have been broken. The stalker and hunter den could be found. They require a forest biome.
