### ISSUE TITLE
Reactive spell causing crash in particular circumstances.

### ISSUE THREAD

**Issue by RyozuK** [baileyholl/Ars-Nouveau#1419]
Setup: Wearing a piece of armor with Reactive III and given a spell as follows:

Touch->Cut

Another mod requires a player or mob to be put into a heated cauldron to produce blood.  Upon jumping into the cauldron (and facing down to see if the blood accumulates) the damage tick from the cauldron triggered reactive.  This results in a crash.

https://gist.github.com/RyozuK/3d5554eda6d2e48555d33aa50aed9d89

The following Ars related mods are in use:
ars_nouveau-1.21.0-5.0.12-all
ars_ocultas-1.21.0-2.0.1
ars_additions-1.21.0-21.0.2
ars_elemental-1.21.0-0.7.0.5

**Comment by AlexanderChang140** [comment]
This seems to occur when Iron's Spells 'n Spellbooks is installed, when jumping into a standard cauldron with a campfire under it.

**Comment by AlexanderChang140** [comment]
This issue is likely on Iron's Spells 'n Spellbooks end. From what I have tested, even right clicking the cauldron with an empty hand crashes the game.

**Comment by RyozuK** [comment]
I'm able to reproduce the crash without ars installed, though I can't get it to crash loop like it was doing to me the first time.  Still, if the root crash is fixed, the loop goes with it, will submit the issue with irons (but better this time.)
