### ISSUE TITLE
Carbonkle crashes server

### ISSUE THREAD

**Issue by FinalFart** [baileyholl/Ars-Nouveau#142]
Hi if you destroy a chest that a Carbonkle is taking from, it crashes the server!

pretty sure it's returning Null

**Comment by FinalFart** [comment]
for an update, this has crashed a multiplayer server twice now :P

**Comment by baileyholl** [comment]
This is fixed in dev, a new version containing this fix should be out today or tomorrow.

**Comment by baileyholl** [comment]
https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3174543
