### ISSUE TITLE
Crash on startup: "Requires JEI 1.19-5.0.7.1 or above"

### ISSUE THREAD

**Issue by ItsKipz** [baileyholl/Ars-Nouveau#1421]
If this is an actual dependency, it is unlisted and does not seem to be intended. Ars Nouveau version is 1.21.0-5.1.0, minecraft version is 1.21.1.

**Comment by leyxcx** [comment]
Will this ever be changed? A lot of us are moving to EMI as it's becoming more useful now so it's annoying having to be forced to stick with JEI

**Comment by baileyholl** [comment]
JEI can be run alongside EMI while using EMIs GUI. To drop JEI would require another integration with EMI to get the same recipe viewers which I do not have capacity for at the moment. Playing without JEI would render half of the recipes unviewable.

**Comment by baileyholl** [comment]
Latest version has removed the JEI dependency, but it is still recommended in order to see the recipes even in EMI.
