### ISSUE TITLE
Crash on breaking containment jar with captured mob

### ISSUE THREAD

**Issue by Gaz492** [baileyholl/Ars-Nouveau#1423]
Not entirely sure who's to blame with this crash, but when breaking a containment jar with a captured mob such as a blaze or camel the game will run into a crash if you also have the mod neat installed.

Crash log: https://pste.me/@1xvU6C1e7ss
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5808
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5790

Also reported this to neat: https://github.com/VazkiiMods/Neat/issues/157

**Comment by baileyholl** [comment]
This would be on Neat's side, looks like they made a fix.
