### ISSUE TITLE
Storage podium game crashes

### ISSUE THREAD

**Issue by INV-PLA** [baileyholl/Ars-Nouveau#1428]
[crash-2024-10-02_08.54.15-server.txt](https://github.com/user-attachments/files/17218523/crash-2024-10-02_08.54.15-server.txt)

**Comment by baileyholl** [comment]
This looks like an issue with dim-thread changing the way capabilities are accessed.

**Comment by INV-PLA** [comment]
> This looks like an issue with dim-thread changing the way capabilities are accessed.

By moving the sub podium to the bound inventory location through the transfer module, the game crashes, and loading this block will repeatedly crash
