### ISSUE TITLE
[Crash] java.lang.NullPointerException: Unexpected error

### ISSUE THREAD

**Issue by Ridanisaurus** [baileyholl/Ars-Nouveau#143]
Crash when using the bow, and having the 3 arrow types in my inv.

Crashlog: https://gist.github.com/Ridanisaurus/38b85b4d615cdd9c1a960bd9566e75b6

**Comment by baileyholl** [comment]
Fixed here: https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3174543
