### ISSUE TITLE
mobs won't spawn ars!den Please help me

### ISSUE THREAD

**Issue by fhntv9900** [baileyholl/Ars-Nouveau#1435]
forge 1.20.1-47.3.10
ars_nouveau-1.20.1-4.12.4-all (3).jar
geckolib-forge-1.20.1-4.4.9.jar
curios-forge-5.9.1+1.20.1 (1).jar
Patchouli-1.20.1-84-FORGE (1).jar

**Comment by baileyholl** [comment]
They only spawn in dens, found around the world in forest, plains, or taiga biomes. You can also use the summon wilden ritual.
