### ISSUE TITLE
[1.21.1]Alakarkinos reverse home bound bug?

### ISSUE THREAD

**Issue by CubeTwo** [baileyholl/Ars-Nouveau#1447]
if i try to bound home for Alakarkinos(select Alakarkinos 1t and 2d try to select block or chest for home) its do nothing.
if i select chest and than Alakarkinos its sets home with broken chat message.
![2024-10-20_21 03 00](https://github.com/user-attachments/assets/8d333c30-b308-4f41-927d-ee1bbcf92cdc)
![2024-10-20_21 00 07](https://github.com/user-attachments/assets/e03a6655-53f5-4988-bdc3-3484d17a1ff6)

**Comment by CubeTwo** [comment]
and its intended Alakarkinos wanders like 30+ blocks from home?

**Comment by CubeTwo** [comment]
After exit world and enter again Alakarkinos seems just run far away from home and dont do work
![2024-10-20_21 13 49](https://github.com/user-attachments/assets/35567f22-b331-4a17-920c-6fc744b4d763)

**Comment by baileyholl** [comment]
Thank you for the reports, the fix should be released later today.
