### ISSUE TITLE
[1.21.1] Bubble Glyph spell and Target Dummy

### ISSUE THREAD

**Issue by CubeTwo** [baileyholl/Ars-Nouveau#1450]
Bubble Glyph spell breaks Target Dummy and target Dummy item form drops. Sometimes spell take Target Dummy in bubble and after that brake it to item form. Its intended? or no way to see dmg on Target Dummy?
NeoForge 21.1.72
ars_nouveau-1.21.1-5.2.0-all
dummmmmmy-1.21-2.0.6-neoforge
![2024-10-20_23 48 09](https://github.com/user-attachments/assets/736f5b60-0001-4202-b2c0-4f11cd4500b1)
![2024-10-20_23 53 03](https://github.com/user-attachments/assets/e862041f-c0e0-4ea5-bd55-3ef4323ad93b)

**Comment by baileyholl** [comment]
This is not on our end, the dummy is converting itself to an item when it lifts off the ground.
