### ISSUE TITLE
Neo- forge ( 1.21.1) world crashing while trying to add the second drygmy to a henge

### ISSUE THREAD

**Issue by Kyassady** [baileyholl/Ars-Nouveau#1454]
i started a drygmy farm and used 1 Drygmy charm in a mossy stone, the henge was formed and the drygmy worked fine! when i tryied to add a second Drygmy my world crashed and i can't re-join. the console gave this entries:

[Server thread/INFO] [minecraft/ServerGamePacketListenerImpl]: lost connection: Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:set_entity_data'

versions:
MC-1.21.1 
Neoforge-21.1.72 
Ars versions-5.2.0
ars nouveau 5..0 
ars additions 1.21.0-21.0.2
ars ocultas 2.0.1
ars elemental 0.7.0.7

Modpack: Allthemods10

the full log is in https://mclo.gs/xnkWx3X

**Comment by heatwaveqc** [comment]
Also had this issue. On a server it kicked me but the server stayed up. 

[Error] [minecraft/EntityStorage]: An Entity type entity.ars_nouveau.drygmy has thrown an exception trying to write state. It will not persist. Report this to the mod author

lmk if you need more info.

**Comment by baileyholl** [comment]
A fix for this was released a few days ago. Please update to the latest.

**Comment by Kyassady** [comment]
thanks a lot
