### ISSUE TITLE
[1.21.1]Starbuncle charm save data after clearing

### ISSUE THREAD

**Issue by CubeTwo** [baileyholl/Ars-Nouveau#1458]
Starbuncle save points where he need put items after clearing task.
1. Set starbuncle to take items from chest or put in chest.
2. Clear task
3. Kill Starbuncle and get charm
4. Place Strabuncle and he have data of(step1.) not cleared from step2.
Neoforge 21.1.72
ars_nouveau-1.21.1-5.2.1-all
ars_elemental-1.21.0-0.7.0.7
ars_additions-1.21.1-21.1.1

**Comment by baileyholl** [comment]
I cannot reproduce this, I have placed one locally, bound from Chest -> Starbuncle and Starbuncle -> Chest and dispelled it. It returned as a blank charm with no data. Killing it is the same result. 

Is it a normal item transport starbuncle?

**Comment by baileyholl** [comment]
I did find a potential desync that was causing them to *not* save their tag data into the charm, it is possible this was caused by some order of chunk saving/loading that I couldn't find.
