### ISSUE TITLE
[1.21.1]Source jar have visual? bug of rendering how much source in jar

### ISSUE THREAD

**Issue by CubeTwo** [baileyholl/Ars-Nouveau#1459]
Source jar have visual? bug of rendering how much source in jar
Neoforge 21.1.72
ars_nouveau-1.21.1-5.2.1-all
ars_elemental-1.21.0-0.7.0.7
ars_additions-1.21.1-21.1.1
![2024-10-24_18 44 13](https://github.com/user-attachments/assets/eb15b493-81af-4408-bca4-34bf50a842c7)
![2024-10-24_17 55 49](https://github.com/user-attachments/assets/568508d8-90e2-4547-9a51-0caf1117a1ad)
![2024-10-23_15 51 31](https://github.com/user-attachments/assets/537fdddb-2942-4868-b2f2-7dd00bbeaa45)

**Comment by baileyholl** [comment]
Fixed in latest
