### ISSUE TITLE
Crash when using Whelp

### ISSUE THREAD

**Issue by EpicSquid** [baileyholl/Ars-Nouveau#146]
Crash Log: https://pastebin.com/EeQEbaeT

Still getting clarification from my server users as to what circumstances this occurred during. Running the latest version on 1.16.4 (1.11.1)

**Comment by baileyholl** [comment]
Some extra context would be super helpful, but I have added an extra check for now in case of a bad state.

**Comment by EpicSquid** [comment]
Thanks, if I get extra context from one of the players I'll let you know
