### ISSUE TITLE
Alakarkinos wont use clay or soul sand when Allthemodium is present

### ISSUE THREAD

**Issue by ChaosDogG** [baileyholl/Ars-Nouveau#1461]
i assumed since the new crab summon could pull archeology loot from base gravel or sand, since each has a sus version, that they would also do so from other blocks that were given sus forms by other mods, i.e. clay and soul sand from Allthemodium

**Comment by baileyholl** [comment]
Archaeology loot tables are not uniform or easily detectable like that, but alakarkinos uses custom recipes that allow packs to manually add them instead.

**Comment by ChaosDogG** [comment]
Oh, well alrighty then! Thanks for the quick response!

**Comment by ChaosDogG** [comment]
Also, love that he dances to jukeboxes! U know u did a crab mob right when they rave :3
