### ISSUE TITLE
Lighting issue with flashing archwood tree

### ISSUE THREAD

**Issue by Divotox** [baileyholl/Ars-Nouveau#1463]
ars_nouveau-1.19.2-3.23.0

Below I included an example. All of the archwood trees and their blocks appear to be fine except for the flashing. Just included the blazing, but the others are also fine. I am using Complimentary Shaders, but I noticed it happening in others also.

thanks :)

![2024-10-26_23 29 47](https://github.com/user-attachments/assets/8822f64b-ef12-40d9-bd36-55d1533f430d)
![2024-10-26_23 29 52](https://github.com/user-attachments/assets/21971822-17ce-49ff-bc5c-7970387d20d2)
![2024-10-26_23 34 00](https://github.com/user-attachments/assets/90d66f63-0a1b-4be6-8ef0-315f6d258bbf)
![2024-10-26_23 34 25](https://github.com/user-attachments/assets/925786bc-bece-46b2-86f8-0c276cf5cf63)

**Comment by Alexthw46** [comment]
The only difference would be that flashing logs produce a dim light, while the other don't emit light at all

**Comment by Divotox** [comment]
Thats probably it then. I'll just move the logs elsewhere to solve this. Love the mod though :) can't play without it.
