### ISSUE TITLE
Raid and Containment ritual in 1.21.1

### ISSUE THREAD

**Issue by uhloin** [baileyholl/Ars-Nouveau#1464]
I set items for containment ritual (a brazier, a jar with source, empty containment jars) provoked a raid and toggled ritual with redstone.
2 pillagers were trapped to jars. I released them and killed, but raid status is sticked in the state: "Raid - Raiders Remaning: 2"
Some time later raid status was changed to just "Raid" and progress bar is sticked somewhere in the middle.

After abort a raid (break all beds and set them again) I started a new raid. This time I didn't try start ritual and capture anybody. But after kill all pillagers from 1st wave I've got again status "Raid - Raiders Remaning: 2" as if some bug from previous raid is still in effect.

**Comment by uhloin** [comment]
May be it's not a bug, but effect from MonsterPlus mod, it may creates underground "undead" mobs after kill others.

**Comment by baileyholl** [comment]
The ritual removes them from the game which Raids account for on a timer, this is likely from another mod conflicting.
