### ISSUE TITLE
[1.21.1] Drygmy farm not pulling Gunmetal from Loot pool.

### ISSUE THREAD

**Issue by Hexblood** [baileyholl/Ars-Nouveau#1469]
Minecraft: 1.21.1
Neo-Forge: 21.1.72
Ars Nouveau: 5.2.2
Vic's Point Blank: 1.7.8

Vic's Point Blank adds a Gunmetal Nugget to drop from most mobs. However, The Drygmy mob farm does not seem to be catching it.

I am guessing he is doing something different to cause the drop since it is dropping from multiple mobs. 

I am not sure if there is something you can do so the Drygmys can get this drop as well. However, I would appreciate it if you could take a look at it.

**Comment by baileyholl** [comment]
The drygmy uses vanilla loot tables for this. If the mod is not adding a loot table and is instead using a mob death event or mixin or something else, it will not drop. 

There is not a fix for this, as boss drops also operate outside of the loot table intentionally. You can add this as a drop yourself with a loot table datapack, or report it to that author.
