### ISSUE TITLE
Cut spell won't shear leaves

### ISSUE THREAD

**Issue by Karthas077** [baileyholl/Ars-Nouveau#147]
Both Projectile>Cut and Touch>Cut play an unarmed "swing" sound but do not shear blocks. Adding AOE only increases the volume of the sound as it plays from each block which is trying to be affected. Spell shears entities as expected.

**Comment by baileyholl** [comment]
Cut only applies the right-click behaviors of shears, not the breaking parts of it. You can use Break + extract for the silktouch you are looking for.

**Comment by Karthas077** [comment]
Fair enough, that isn't especially clear from the in-game book. Is there anything to be done about no spells being able to pick up vines then? Because break+extract just goes straight through them.
