### ISSUE TITLE
Invalid Icon Types

### ISSUE THREAD

**Issue by itsdeadfrosty** [baileyholl/Ars-Nouveau#1479]
[latest.log](https://github.com/user-attachments/files/17606484/latest.log)

Error: Invalid icon item stack warnings, often for items like archmage_robes.
Impact: Missing or improperly registered icons, which may affect UI elements.
Potential Conflict: Typically standalone errors but may suggest missing assets or incomplete mod installation.

**Comment by baileyholl** [comment]
Have you actually seen this missing somewhere? The log is too generic to know where that is coming from.
