### ISSUE TITLE
Crash ars_nouveau-1.16.4-1.11.1.jar

### ISSUE THREAD

**Issue by HonestAngel** [baileyholl/Ars-Nouveau#148]
I am using 1.16.5-forge-36.0.1

software.bernie.geckolib3.geo.exception.GeoModelException: ars_nouveau:geo/spellbook_tier1closed.geo.json: Could not find model.
[crash-2021-01-21_12.35.26-client.txt](https://github.com/baileyholl/Ars-Nouveau/files/5852056/crash-2021-01-21_12.35.26-client.txt)

**Comment by baileyholl** [comment]
This has been potentially fixed in the latest version of geckolib, 3.0.1.
