### ISSUE TITLE
Transparent Blocks - Shader Incompatibility

### ISSUE THREAD

**Issue by SeriousAlarm** [baileyholl/Ars-Nouveau#1482]
When using any shaders, both the skyweave block and the warp portal block are transparent, seems to be an issue with the mod as it seems to be impossible to overwrite the inbuilt shaders. Even the inbuilt config to change the the portal to use the "simplified renderer" doesn't change the transparency issue
It would be nice if it would work like other blocks from other mods where the shaders can be made compatible such as dimensional doors which uses the same texture as the warp portal block

**Comment by baileyholl** [comment]
Which shader mods/shaders/versions?

**Comment by SeriousAlarm** [comment]
Any Iris shaders really, Im using Complimentary shaders & euphoria patches, ive tried other shaders and have the same result, the shader discord believes it is a modside rendering issue conflicting with shaders in general

**Comment by baileyholl** [comment]
Iris overwrites the end portal render entirely and does not even support the vanilla render types, which Ars Nouveau uses. I won't add custom integrations for iris, as the mod is slow to port and causes numerous conflicts. https://github.com/Asek3/Oculus/blob/da63951877b88427b3cd59da315ba07f2083c6fa/src/main/java/net/irisshaders/iris/mixin/MixinTheEndPortalRenderer.java#L52
