### ISSUE TITLE
Grow spell doesn't affect Dynamic Trees

### ISSUE THREAD

**Issue by Dominus-Sicarum** [baileyholl/Ars-Nouveau#1483]
Minecraft [1.20.1]
Forge [47.3.11]

Ars Nouveau [4.12.4]
[Dynamic Trees [1.20.1-1.3.4]](https://www.curseforge.com/minecraft/mc-mods/dynamictrees)

As per title, Grow does nothing to dynamic trees.

**Comment by baileyholl** [comment]
Grow is just bonemeal. If mods do not support bonemeal then it will not be supported.
