### ISSUE TITLE
Compatibility issue with Integrated Dynamics

### ISSUE THREAD

**Issue by uhloin** [baileyholl/Ars-Nouveau#1486]
Details and reproducing steps are here:

https://github.com/CyclopsMC/IntegratedCrafting/issues/114

Additional issue:

If set coordinates to warp scroll and put it to chest, you cannot get that scroll back via Storage Terminal (but can directly from chest).

There was (not sure, may be fixed) a similar issue with Books of spells.

Also see similar bugs here, in the most cases it was not issue of Integrated Dynamics, but some serialization bugs:
https://github.com/CyclopsMC/IntegratedTerminals/issues/130
https://github.com/CyclopsMC/IntegratedTerminals/issues/137

**Comment by Linguardium** [comment]
this issue also affects ars items inside occultism storage.
