### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by deuli** [baileyholl/Ars-Nouveau#1487]
Our Craftoria server has been crashing constantly and after some observations and tests, the issue is due to Ars Nouveau and the Relays, specifically when a chunk gets unloaded while source is being transported inside of it.

[crash-2024-11-04_21.52.19-server.txt](https://github.com/user-attachments/files/17624339/crash-2024-11-04_21.52.19-server.txt)

On the server, I could consistently replicate the crash by leaving the server right when source left my Splitter Relay and another player managed to crash it by doing /home right when source left the same Splitter.

In singleplayer (both in Craftoria 1.6.1 and a seperate 1.21.1 instance with only Ars Nouveau 5.2.2, NeoForge 21.1.74 and the dependencies), the game crashes consistently by
1. Going away from the spawn chunks (in my case, I went to x1000 z0 in a flatworld)
2. Placing two Creative Source Jars and a Relay with some distance in between them
3. Linking a Jar to the Relay and the Relay to the other Jar
4. Teleporting away right when the first source particle left the jar (I teleported back to x0 z0)
5. Game crashes

![2024-11-04_22 51 28](https://github.com/user-attachments/assets/b953e921-e89f-4aa2-a9cc-858584c2288f)

**Comment by baileyholl** [comment]
This should be fixed next version.
