### ISSUE TITLE
Ars Nouveau Break Spell breaks Waystones that are set to Unbreakable

### ISSUE THREAD

**Issue by Silverbolt666** [baileyholl/Ars-Nouveau#1493]
### Issue:
When waystones are set to be unbreakable in the mod config (see config below) Ars Nouveau Break Spell can still break it:

Tested:
- Projectile + Break
- Touch + Break

### Game Version:
**Forge:** 47.3.10
**Minecraft:** 1.20.1
**Ars Nouveau:** 4.12.4
**Waystones:** 14.1.6

### Waystones Config (in txt)
[waystones-common.txt](https://github.com/user-attachments/files/17667762/waystones-common.txt)

### Notes

Craftweaker is enabled in order to remove crafting capabilities
[waystones.txt](https://github.com/user-attachments/files/17667812/waystones.txt)

**Comment by baileyholl** [comment]
Ars fires events for other mods to cancel if something should not be broken, if the config is not listening to those events then I am not sure how else they would be able to prevent other mods.
