### ISSUE TITLE
Grates can move or destroy waterlogged blocks

### ISSUE THREAD

**Issue by YocyCraft** [baileyholl/Ars-Nouveau#1494]
If you put a waterlogable block on a grate, and the grate has air below it, then after you waterlog it, the block above will be moved under the grate with water. If you put a waterlogable block on a grate, and the grate has another waterlogable block below it,  then after you waterlog it, the block above will be destroyed.

https://github.com/user-attachments/assets/2e030f09-d2f3-4e31-b49c-d53d6379af43

**Comment by baileyholl** [comment]
Fixed in the next version
