### ISSUE TITLE
Enchanter's bow causes a crash

### ISSUE THREAD

**Issue by TechEpic** [baileyholl/Ars-Nouveau#150]
[Forge 35.1.37, mod version 1.11.1, CSP world]

Any attempt to use the enchanter's bow without a spell results in the game freezing, forcing me to kill it with task manager. As such, there is no crash log because it's just hanging indefinitely.

Update: I tried to put it in a scribe's table and got a crash log: https://hatebin.com/derujqlsno

**Comment by baileyholl** [comment]
That is a crash related to blood magic, please report it there.
