### ISSUE TITLE
New version of AN for 1.21.1 has broken Projectile glyph

### ISSUE THREAD

**Issue by uhloin** [baileyholl/Ars-Nouveau#1504]
ars_nouveau-1.21.1-5.2.4-all.jar 
curios-neoforge-9.0.15+1.21.1.jar
geckolib-neoforge-1.21.1-4.7.jar 

Set spell: Projectile + Conjure Mageblock + Amplify

Try cast it. If target block is far enough, then OK. But try to cast spell to very near block and projectile will fly in random direction.

**Comment by baileyholl** [comment]
5.2.5 has been uploaded with this fix, thanks
