### ISSUE TITLE
crashes after making the harvest glyph and cant start back up

### ISSUE THREAD

**Issue by thefirstromy** [baileyholl/Ars-Nouveau#1505]
so i recently started with ars nouveau and when i wanted to make the fist glyph the harvest glyph it crashed after i added the ho and the essence. ever sinds i havent been able to open the world up because it crashes right after it says it is done loading. i read the crash code and it was a tick error. i dont know what to do i have tried it 3 times and on two different launcers ( curse and prism) but the same thing happens. does someone know how to fix this?

**Comment by baileyholl** [comment]
Please post a crash log
