### ISSUE TITLE
Containment Jar, Spell Book trapped inside jar

### ISSUE THREAD

**Issue by SuperFurias** [baileyholl/Ars-Nouveau#1509]
ars_nouveau-1.19.2-3.23.0.jar

I am unable to retrieve my Spell Book from inside the Containment Jar without crafting another book to dispel the jar, please add something to retrieve the Spell Book from the Jar without the necessity of creating another book and dispel the jar

**Comment by muppetenergy** [comment]
not sure if it's the case in older version, but someone on my server had theirs get trapped too and we were able to just grab it with crouch+right click

**Comment by SuperFurias** [comment]
> not sure if it's the case in older version, but someone on my server had theirs get trapped too and we were able to just grab it with crouch+right click

tried everything i could, but i was unable to pick the book, maybe its really just something they didn't patch in the 1.19.2

**Comment by baileyholl** [comment]
1.19.2 is no longer updated, modern versions allow for interaction to remove items.
