### ISSUE TITLE
Right click with repeater on glyph press dupes repeater

### ISSUE THREAD

**Issue by kubix3009** [baileyholl/Ars-Nouveau#151]
As in the title:
When you right click with a repeater on the glyph press it places the repeater on the side of the press, but it doesn't remove it from your hand - when you break the repeater, it drops, hence you can copy them indefinitely.
Also, because of that I can't create one of the glyphs, delay, because it places repeater on the press instead of putting it inside. 
Modpack: Engimatica 6

**Comment by baileyholl** [comment]
This is a bug with another mod in that pack, see the Enigmatica Git Issues page, it is a known issue.
