### ISSUE TITLE
[Feature Request] Serene Seasons support for Plants/Crops/Saplings/Etc

### ISSUE THREAD

**Issue by v3xed-v0id** [baileyholl/Ars-Nouveau#1512]
hello, i love this mod, but it would be much better if it supported the [serene seasons mod](https://www.curseforge.com/minecraft/mc-mods/serene-seasons) for the respective crops/saplings/plants/etc this mod adds, please add support for this mod in ars nouveau, thank you for reading :)

**Comment by baileyholl** [comment]
Ive added plants to their respective tags
