### ISSUE TITLE
[1.21.1] Casting Projectile > Place Block deletes Spell Book

### ISSUE THREAD

**Issue by SolskaTCR** [baileyholl/Ars-Nouveau#1513]
Just as title describes - when casting any variation of Place Block with the Projectile glyph, it completely deletes the spell book from your inventory upon the spell's resolution (perhaps as if trying to "place" the spell book?)

Hoping this is fixed ASAP, very confusing.

**Comment by RainyJimbo** [comment]
This seems to be the case as well with casting Touch > Sensitive > Place Block. It seems to confuse the spell book as a block to place.

**Comment by baileyholl** [comment]
Update to the latest version, this has been fixed.
