### ISSUE TITLE
[Forge 1.20.1] Unable to find the blacklist config for confinement jar

### ISSUE THREAD

**Issue by DaftHunk** [baileyholl/Ars-Nouveau#1518]
Hello, we have problems with confinement jars on our modpacks with other mods. 
I've seen online we can blacklist entities to disable them being pickable (like cobblemon for exemple) in configs but I don't understand where.

Can you help me, please ? :)

**Comment by baileyholl** [comment]
You need to modify the jar_blacklist entity tag using kubejs or a vanilla datapack. It is not found in the configs.
