### ISSUE TITLE
weird crash

### ISSUE THREAD

**Issue by Vadewolf** [baileyholl/Ars-Nouveau#1520]
[crash-2024-11-21_20.29.20-client.txt](https://github.com/user-attachments/files/17877002/crash-2024-11-21_20.29.20-client.txt)
[crash-2024-11-22_16.16.00-client.txt](https://github.com/user-attachments/files/17877003/crash-2024-11-22_16.16.00-client.txt)

idk if this is on ars side or geckolib but it mentions both so

**Comment by Vadewolf** [comment]
[crash-2024-11-23_10.13.22-client.txt](https://github.com/user-attachments/files/17880436/crash-2024-11-23_10.13.22-client.txt)

same for hypercube mod

**Comment by Linguardium** [comment]
can you reproduce this issue without other mods?

**Comment by Vadewolf** [comment]
yes several mods that cause the same issue but no clue wat causes it

**Comment by Vadewolf** [comment]
[crash-2024-11-30_20.28.46-client.txt](https://github.com/user-attachments/files/17967618/crash-2024-11-30_20.28.46-client.txt)

from today fruits crate easy mob farm and doggy talents next
