### ISSUE TITLE
Opening Worn Notebook, opens it for other players too

### ISSUE THREAD

**Issue by thiefaine** [baileyholl/Ars-Nouveau#1522]
Hello,
Setup : minecraft 1.21 / Ars Nouveau 5.2.6 / modepack Craftoria 1.8.0

I host a LAN world and when other players open their Worn Notebook, it force opens it for me (even if I don't possess the book) and it also lock my mouse controls. It does not reproduce the other way (me opening it will not open it on the other players)
I can press ecape to close the book for me (it does not close it for the other players).

A workaround we found is to open it on a lectern, as it will not open it for me.

**Comment by baileyholl** [comment]
this should be fixed on the latest version
