### ISSUE TITLE
[1.21.1 Suggestion] The Worn Notebook should use the entry unlocking feature

### ISSUE THREAD

**Issue by vizthex123** [baileyholl/Ars-Nouveau#1523]
It's pretty overwhelming to open it and be met with 87 categories and 3,000 pages when you've never used the mod before - especially since it's not made clear where you should start due to the "Getting Started" category having a ton of pages that don't feel very relevant to the new player experience.

Applies to every version (as far as I know, at least - only used it on 1.21.1), but I'm not sure if old MC versions still get mod updates.

**Comment by baileyholl** [comment]
We are in the process of rewriting documentation from the ground up natively instead of using patchouli #1517 

that will also include advancement based progression with an option to unlock everything immediately.

**Comment by vizthex123** [comment]
Noice. I like custom guidebooks a lot more than patchouli, but do understand why most mods forego it.
