### ISSUE TITLE
Skyweave shader issue [ATM9 modpack]

### ISSUE THREAD

**Issue by gitreversefps** [baileyholl/Ars-Nouveau#1525]
The skyweave block doesn't seem to work with shaders but works as intended without in the All the mods 9 modpack.
When using the shaders the blocks around the placed skyweave block get darker/lighter depending on the time of the day but it doesn't show the sky as intended.
![2024-11-25_11 19 42](https://github.com/user-attachments/assets/843263b4-50b3-4b14-bdda-6dd5b48e517c)
![2024-11-25_11 21 30](https://github.com/user-attachments/assets/01d58afc-dc37-47e9-a242-10a8f341a0ec)

**Comment by baileyholl** [comment]
Custom shaders and modded shaders can't really run side by side, and I we don't intend of supporting a custom subset of shaders.
