### ISSUE TITLE
[1.21.1 NeoForge] Cannot read the array length because "<local3>" is null

### ISSUE THREAD

**Issue by Doctor-Duck** [baileyholl/Ars-Nouveau#1528]
I have been getting a crash with Ars Nouvea that happens when trying to create a new world in my own custom modpack. When I'm at the Loading Terrain screen, the game crashes with the: "java.lang.NullPointerException: Cannot read the array length because "< local3 >" is null". I've tested the latest version of Ars and the version I was using previously (which is the version present in the crash log), but every version still causes the crash. I have also disabled the Neruina mod, but the crash still persists.

Ars Nouveau version: 1.21.1-5.2.7+
NeoForge version: 21.1.83
Crash Report: https://mclo.gs/Lr4QmH1
Full latest.log: https://mclo.gs/oXFrzKE
Full debug.log: https://mclo.gs/hWgjGok

**Comment by Doctor-Duck** [comment]
I shouldn't be spawning in a custom dimension. I do have other mods that change the overworld with new biomes, structures, ores, plant, crops, and more. But to my knowledge, I haven't added any new mods that could have caused the issue, but an update with one of the mods in my modpack is whats causing the issue.

**Comment by baileyholl** [comment]
I added a check for it to prevent the crash, but something is definitely not right to remove that value from the overworld. Next release should be out here today or tomorrow.
