### ISSUE TITLE
Storage Lectern Search Bar Causing Game Crashes

### ISSUE THREAD

**Issue by ria4444** [baileyholl/Ars-Nouveau#1530]
I am using ars_nouveau-1.21.1-5.2.6-all.jar on a modded server on 1.21. Each time that I use the storage lectern search bar, my game immediately saves and crashes. No one else in the server experiences this issue when they are using my storage lectern search, and we have the same settings and mods. I can submit the crash report if needed, but so far it does not seem that the crash report provides any answers.

**Comment by baileyholl** [comment]
Please post the crash log

**Comment by Xannaeh** [comment]
here a crash report https://mclo.gs/Yr7ELhn
