### ISSUE TITLE
Ars Nouveau dont work properly with iris shaders

### ISSUE THREAD

**Issue by kontrola111** [baileyholl/Ars-Nouveau#1538]
Hello,
Using the mod elimination method I discovered that
Ars Nouveau dont work properly with iris shaders

https://youtu.be/dBXHmmHbe38
https://youtu.be/dulcEjhYBfE

**Comment by baileyholl** [comment]
Mods have to add custom integration to support shaders, as they do not allow basic vanilla shaders to work. Support won't be added.
