### ISSUE TITLE
NullPointerException in biomeLoad preventing server from starting

### ISSUE THREAD

**Issue by evhub** [baileyholl/Ars-Nouveau#154]
See [this log](https://gist.github.com/evhub/9247fa3e2f8e93c0e6fd69996b1c144c). Using Ars Nouveau 1.11.2 on Forge 1.16.4-35.1.36.

**Comment by evhub** [comment]
Nevermind—it looks like I still get a similar looking error even with Ars Nouveau disabled.

**Comment by baileyholl** [comment]
If you are getting this crash with Ars Nouveau disabled, then it is likely another mod messing with the feature registry. I would remove any performance mods, update forge to latest, and try to find the cause.
