### ISSUE TITLE
Crash inside Storage Lectern UI 

### ISSUE THREAD

**Issue by KDCheapCheap** [baileyholl/Ars-Nouveau#1549]
Happened whilst playing ATM10 version 2.6 which has mod version 5.3.5.

Built Storage Lectern, created one Wyrm, added 2 inventories (Sophisticated Storage barrels, one diamond, one gold)

I entered the UI, clicked the arrow to expand the items, when trying the collapse that, it crashed out with this error:

The game crashed whilst ticking screen
Error: java.lang.IndexOutOfBoundsException: Index 27 out of bounds for length 27

Any more info needed I'm happy to help :)

**Comment by baileyholl** [comment]
This was fixed in the latest version.
