### ISSUE TITLE
Enchanter's Bow causes crash when placed on the Scribe table

### ISSUE THREAD

**Issue by craft90** [baileyholl/Ars-Nouveau#156]
I tried out the new Enchanter's Bow on the DireWolf20 1.16 pack. However twice it crashed my game. Once when attempting to fire (after finished crafting) and secondly when attempting to inscribe a spell. The game crashed as I placed it on the Scribe's table. When logged back in it was in the table and could be removed without trouble. I'll attach the crash logs.

It appears to be some sort of ticking entity issue.

[crash-2021-01-27_17.27.00-server.txt](https://github.com/baileyholl/Ars-Nouveau/files/5881655/crash-2021-01-27_17.27.00-server.txt)
[crash-2021-01-27_17.35.29-client.txt](https://github.com/baileyholl/Ars-Nouveau/files/5881656/crash-2021-01-27_17.35.29-client.txt)

**Comment by craft90** [comment]
On a second look it seems to be an issue with Blood Magic strangle enough.

**Comment by WayofTime** [comment]
Blood Magic crash! Fixed it in my dev environment, and will be pushing a build soon.

**Comment by craft90** [comment]
That's good to hear. I was about to post a crash log to your Github too. Now I don't have to. :) Thank you for all your hard work.
