### ISSUE TITLE
carbuncle wont pick up items

### ISSUE THREAD

**Issue by SenCarryr** [baileyholl/Ars-Nouveau#157]
Trying to automate supremium production (mystical agriculture). Wixie picks up items, crafts, then tosses the items. The carbuncle right beside it will sometimes pick the items up and sometimes wont. The chest is 3 blocks away and not covered or blocked. Not sure if lag or pathfinding issue. In the provided image i created a box similar to the original issue, and the issue still occured.

**Comment by SenCarryr** [comment]
Or I guess no image, it wont upload.

**Comment by baileyholl** [comment]
Are the items stuck in partial blocks like fences?

**Comment by SenCarryr** [comment]
No, they just sit on the ground. If i pick them and throw them on the ground a few times the carbuncle will pick them, but that kinda defeats the purpose

**Comment by ZoMadeStuff** [comment]
I got the same issue. The carbundle just wont pick items from world or storages. I tried it with only vanilla items and chests to be sure this is an issue. It only sometimes decide to pick stuff very occasionally.

**Comment by baileyholl** [comment]
Hello, please try the latest version (1.11.4)
