### ISSUE TITLE
[Crash] Ticking block entity

### ISSUE THREAD

**Issue by Athena-AI** [baileyholl/Ars-Nouveau#161]
Updating from 0.3.6 to 0.3.9 causes my game to crash. The crash happens when I load into my world where everything is completely dark before it crashes and saves the world then exits to desktop.

The only modifications are optifine for shaders and a texture pack.
Crash Log: https://pastebin.com/ww6E6jrj

Edit: Removing Optifine fixed it.

**Comment by baileyholl** [comment]
This is a crash log about Create, not Ars Nouveau :)
