### ISSUE TITLE
[1.16.5] Crystallizer Output

### ISSUE THREAD

**Issue by NillerMedDild** [baileyholl/Ars-Nouveau#166]
\o

It would be really nice if we could change the output of the Crystallizer. 
In Enigmatica 6 we use our own mod for most ressources to keep a unified look, and to allow players to know which mod outputs should mostly stem from - 
The Crystallizer from AN can only produce AN Mana Gems, and we would like to change that to Emendatus Enigmatica Mana Gems. Would you perhaps consider making a config for changing output? :)

**Comment by baileyholl** [comment]
only if you put this mod in e6: https://www.curseforge.com/minecraft/mc-mods/physics-mod

**Comment by Ridanisaurus** [comment]
Wow, what a menace :D

**Comment by NillerMedDild** [comment]
Playing hardball eh. 

I mean, it does look cool... 😄

**Comment by Ridanisaurus** [comment]
Don't break my heart, Niller. I say we play even harder ball, and threaten to remove Ars Nouveau instead :P

**Comment by baileyholl** [comment]
Okay just for you.
