### ISSUE TITLE
Damage spells dont work on the Ender Dragon

### ISSUE THREAD

**Issue by BenOHedges** [baileyholl/Ars-Nouveau#168]
Playing with version "ars_nouveau-1.16.4-1.11.2" and tried fighting the Ender Dragon and my two damage spells when collided didnt do any damage but did work on the endermen (and normal mobs). 

2 Spells i used: 
- Proj + harm + amp x 2 + fortune x3
- Proj + freeze + cold snap +amp x 3 + fortune x3

Didnt tried the Enchanted bow to see if that would of worked, thought i mention that

**Comment by baileyholl** [comment]
Freeze + cold snap won't work as the dragon cannot be given a potion effect, but harm should work in the next update.
