### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by WenXin20** [baileyholl/Ars-Nouveau#17]
`Minecraft v1.15.2`
`Forge v31.2.36`
`Ars Nouveau v0.20.1`

My server crashed during load after updating to the new version.
[Crash Report](https://gist.github.com/WenXin20/bc86d15a0989f624ff82bbed1313bbe9)

**Comment by baileyholl** [comment]
Oh sorry about that, if you revert to 0.20 that should fix it for now.

**Comment by WenXin20** [comment]
Yep, already have for now.

**Comment by baileyholl** [comment]
I have released the fix here: https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3071984

**Comment by WenXin20** [comment]
Thanks!
