### ISSUE TITLE
Duplication Glitch

### ISSUE THREAD

**Issue by bronsonty** [baileyholl/Ars-Nouveau#173]
If you shift + right click using the break spell on a container it will first open the container then break it. This allows you to take items from said inventory which duplicates them.

**Comment by bronsonty** [comment]
To clarify This only works with containers that keep their inventory like shulkers.

**Comment by baileyholl** [comment]
Did you actually successfully duplicate an item? Are you on a server or single player? if you are on a server, is this a standard forge server or are you running plugins?

A mod list would also be helpful. Thank you

**Comment by bronsonty** [comment]
I am playing on a single player world using the Direwolf20 1.16.5 mod pack. After further testing it I have found that it is not an issue with vanilla minecraft containers. I have only been able to duplicate items so far by using Quantum Storage diamond storage crates. I will be testing other containers as well to see if it is specific to Quantum Storage or if it works with other mods as well.

**Comment by bronsonty** [comment]
So the mods that I have been able to successfully duplicate items with using this method are Quantum Storage, Quartz Chests and Krate.

**Comment by baileyholl** [comment]
This would be a bug with those mods, they will need to fix their validations on their containers, see a similar issue here: https://github.com/gigabit101/QuantumStorage/issues/239
