### ISSUE TITLE
Carbuncle AI gets stuck picking Mana Berries and crashes server [1.11.4]

### ISSUE THREAD

**Issue by Ozurian** [baileyholl/Ars-Nouveau#176]
Currently experiencing an occasional crash where the Carbuncle assigned to pick berries and store them to a chest will first appear to be stuck, sitting still in a berry bush and not doing anything anymore. Once I broke the bush eventually to try to get the little one to move again it took down the server with the attached error:

https://gist.github.com/Ozurian/339b4b77f71c32d64db1593d7b7a07c4

Possible related is that some of the bushes are right next to a fence

**Comment by baileyholl** [comment]
Will be fixed next update, for now, dispel them before you break any bushes just to be safe :)
