### ISSUE TITLE
Carbuncles get stuck on everything

### ISSUE THREAD

**Issue by Sleeclow** [baileyholl/Ars-Nouveau#177]
They always want to stand on top of the chest. and then get stuck on top of the chest and have to pushed off, also get stuck on stairs.

**Comment by sandalle** [comment]
They also seem to get stuck on Soulberry Bushes after harvesting or the Mana Blooms growing next to them in my garden.

**Comment by baileyholl** [comment]
Are you on the latest (1.11.4) @Sleeclow ?

**Comment by boneskull** [comment]
I have two carbuncles working a field, but they frequently run into each other and get stuck going opposite directions (v1.11.3). neither will budge

screenshot:

![image](https://user-images.githubusercontent.com/924465/107584705-cdbc8680-6bb1-11eb-8c44-3428d1136b3e.png)

**Comment by boneskull** [comment]
whoops,

![image](https://user-images.githubusercontent.com/924465/107585754-a36bc880-6bb3-11eb-8c3a-667a2533800d.png)

**Comment by Sleeclow** [comment]
> I have two carbuncles working a field, but they frequently run into each other and get stuck going opposite directions (v1.11.3). neither will budge
> 
> screenshot:
> 
> ![image](https://user-images.githubusercontent.com/924465/107584705-cdbc8680-6bb1-11eb-8c44-3428d1136b3e.png)

Yea had that happen a lot, ended up having to change my farm around to prevent that

**Comment by Sleeclow** [comment]
> Are you on the latest (1.11.4) @Sleeclow ?

1.11.3

**Comment by Sleeclow** [comment]
> Are you on the latest (1.11.4) @Sleeclow ?

Pack has updated, I am on the latest version now, this issue still persists

**Comment by baileyholl** [comment]
I have added some extra checks in 1.11.5 (https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3202644). Not sure if it will fix them getting stuck on eachother, but it should stop them from freezing permanently in a spot.
