### ISSUE TITLE
Problem with Armor

### ISSUE THREAD

**Issue by Vashta** [baileyholl/Ars-Nouveau#179]
ok so this is not so much a bug issue as a gameplay one i really really like the spells but i have the best armor for your mod yet my spells take massive chunks from my mana even though i have the ring of greater discount! i think you should add some enchantments to help assist with mana for example add an enchantment that increases your max mana. one that increases your mana regen and one that decreases spell cost! that way not only can you add enchantments to your mod armor but you can use other armor too and not be restricted to only your armor

**Comment by baileyholl** [comment]
There are already enchantments, Mana Boost and Mana Regen :) You also get max mana by learning new glyphs, so try to get them all.
