### ISSUE TITLE
Cost of Lightning glyph is disproportionate to effect

### ISSUE THREAD

**Issue by DerringersMods** [baileyholl/Ars-Nouveau#181]
A conduit is a real hassle to put together, mostly because of the rarity of nautilus shells, and lightning is sorely underpowered for a T3 effect, or even T2 in the absence of any effective augments. The only real use for it, besides showing off, seems to be triggering transformations in mobs that are sensitive to it.

**Comment by baileyholl** [comment]
Reworked now!
