### ISSUE TITLE
NullPointerException ,because "this.field_145850_b" is null.

### ISSUE THREAD

**Issue by FierceManul** [baileyholl/Ars-Nouveau#186]
mods:
ars_nouveau-1.16.4-1.11.2
curios-forge-1.16.4-4.0.3.3
forge-1.16.4-geckolib-3.0.0
Patchouli-1.16.4-48

server: arclight-1.16.5-1.0.12-SNAPSHOT-bcf3f33
crash when ManaCondenser get a crop grow.

[latest.log](https://github.com/baileyholl/Ars-Nouveau/files/6056311/latest.log)
[crash-2021-02-28_13.54.41-server.txt](https://github.com/baileyholl/Ars-Nouveau/files/6056312/crash-2021-02-28_13.54.41-server.txt)

**Comment by baileyholl** [comment]
World should not be null, that is likely a bug with the server/plugin software. I have added extra checks anyway.
