### ISSUE TITLE
Extensible means to control sylph interpretation of blocks/items

### ISSUE THREAD

**Issue by DerringersMods** [baileyholl/Ars-Nouveau#187]
Some mods, notably Mystical Agriculture, become far more powerful than intended when sylphs can propagate their plant seeds freely. Possibly this should extend to a tag system, and seeds as well as dirt should be an invalid reward by default. This would also help resolve the seeds-from-grass insanity.

**Comment by baileyholl** [comment]
What of this request is still outstanding after the PR?

**Comment by DerringersMods** [comment]
I think that's basically it.
