### ISSUE TITLE
Crash upon joining server, worn notebook item ID unknown

### ISSUE THREAD

**Issue by Noblejace** [baileyholl/Ars-Nouveau#190]
I've created a couple small modpacks using ars nouveau but they always crash upon me joining a server or private world. I'm using 1.16.5. Thanks!

![image](https://user-images.githubusercontent.com/80017294/109900851-406ece00-7c55-11eb-9a57-c6cf8189a5bb.png)

**Comment by Noblejace** [comment]
Also here's the full crash report.
[crash-2021-03-03_19.14.05-client.txt](https://github.com/baileyholl/Ars-Nouveau/files/6080457/crash-2021-03-03_19.14.05-client.txt)

**Comment by baileyholl** [comment]
I cannot reproduce this, have you tried with just Ars Nouveau and the dependencies?
