### ISSUE TITLE
Worn Notebook: Loading Error

### ISSUE THREAD

**Issue by Zakeyboy** [baileyholl/Ars-Nouveau#191]
Hello,

My Worn notebook suddenly lost most of its pages (they're now blank) and shows a Loading error on its front page, saying:

Error building entry ars_nouveau:spells/launch
Error while loading entry ars_nouveauLspells/launch page 1
Error setting up template processor
check your log for more info

I'm not sure what log it is referring to, but I'll attach the main game one.

I have tried re-installing the mod and remaking the book, not sure what else I could try atm. The version I am using is 1.11.5, but I did not change versions between having these pages and losing them, so I have no idea why they suddenly vanished.

Also, Is there any text file that might replicate what is in the notebook? I would like to get the reactive enchantments but without the page in the notebook I have zero information to go on.

Thanks,
Zake

**Comment by baileyholl** [comment]
What mod pack are you playing? This is typically due to an error with any recipe scripts that may exist in the pack.
