### ISSUE TITLE
Text and inventory icons disappear after reading the Codex Arcana for the first time [Optifine Shaders]

### ISSUE THREAD

**Issue by aivass** [baileyholl/Ars-Nouveau#192]
I'm running OptiFine_1.16.5_HD_U_G7. This issue occurs with any shaders enabled (including the "(internal)" setting. 
After reading the Codex Arcana for the first time inventory icons and text are no longer present, this effect continues even after leaving the game where the book has been read (main menu included).

--System Details--
https://pastebin.com/j8qAEYFH
![javaw_47fc3YhsKY](https://user-images.githubusercontent.com/25469916/110262954-19244380-7f6a-11eb-861d-9a319ba8fbbf.jpg)
![javaw_hwLv1Cq5si](https://user-images.githubusercontent.com/25469916/110262955-19bcda00-7f6a-11eb-9fbf-20ace8dd8e11.jpg)
![javaw_KccUB76St3](https://user-images.githubusercontent.com/25469916/110262956-19bcda00-7f6a-11eb-98c3-fbbe7b8215fc.jpg)

**Comment by baileyholl** [comment]
Codex Arcana is not from this mod :)
