### ISSUE TITLE
Projectile Grow does not work on Mana Bloom and Source Berry

### ISSUE THREAD

**Issue by dBHI-zz** [baileyholl/Ars-Nouveau#193]
The Spell Projectile->Grow does not work on Crops like Wheat, Source Berries or Mana Bloom Seeds, it only works on grass blocks. With the form "Touch" it works, but the Source Berry Bush does not grow but directly drop it's harvest, which may be intended.

**Comment by baileyholl** [comment]
Projectiles pass through non-movement blocking blocks, like grass. You will need to use touch :)
