### ISSUE TITLE
Had a crash, found this

### ISSUE THREAD

**Issue by SenCarryr** [baileyholl/Ars-Nouveau#194]
Im not sure if it was the cause of the crash, kinda doubt it actually, but found this in the log

[Worker-Main-12/ERROR] [net.minecraft.client.renderer.texture.AtlasTexture/]: Using missing texture, unable to load ars_nouveau:textures/blocks/archwood_oak_planks.png : java.io.FileNotFoundException: ars_nouveau:textures/blocks/archwood_oak_planks.png

I've not cut down any archwood trees, but this is the last error before the crash. A previous time i had a similar error with archwood signs

**Comment by baileyholl** [comment]
That would not cause any crashes, that is simply just a missing texture file, nothing that could cause instability.
