### ISSUE TITLE
Welps not performing actions/spells

### ISSUE THREAD

**Issue by maglore9900** [baileyholl/Ars-Nouveau#198]
I have a welp summoned above a summoning crystal, which sits on top of a single block. This is located adjacent to my garden. The welp has been given the harvest spell. There is a mana jar deployed next to him, which has mana. The welp is not casting the harvest spell on any fully grown plant.

**Comment by maglore9900** [comment]
Growth command not working on tilled soil, while simple-farming mod is installed. Harvest spell works when cast by player, may not work when being cast by whelp.

**Comment by baileyholl** [comment]
Try the latest version, some changes were made to whelps and grow as well.
