### ISSUE TITLE
Ars Nouvaeu spawning unregistered entity

### ISSUE THREAD

**Issue by VallenFrostweaver** [baileyholl/Ars-Nouveau#199]
Minecarft 1.16.5
Forge 36.0.48
AN 1.11.6

See console spam here as this is recognized by Darkhax mod Bad Mobs.
![image](https://user-images.githubusercontent.com/13642054/111040466-f642d500-842a-11eb-9c4c-bf433a8c756c.png)

**Comment by baileyholl** [comment]
I do not know what Bad Mobs is, but that entity is registered the exact same way as the rest of the mobs in the mod: https://github.com/baileyholl/Ars-Nouveau/blob/d9ad7de2b7814aaeacb82a6a398d4fb28fc9a55f/src/main/java/com/hollingsworth/arsnouveau/common/entity/ModEntities.java#L78

**Comment by VallenFrostweaver** [comment]
I've posted to a similar bug report on Bad Mobs in hopes of the two of you being able to figure out what/why it's happening. Find their issue report [HERE](https://github.com/Darkhax-Minecraft/BadMobs/issues/46)

**Comment by smmmadden** [comment]
I see the same issue with BadMobs entities.  BadMobs allows server owners to disable specific vanilla mobs from spawning.  So if I didn't want creepers or Ghasts, I could update the config file for BadMobs and chose to disable them.  Same issue reported in https://github.com/Darkhax-Minecraft/BadMobs/issues/46

**Comment by Darkhax** [comment]
Sorry for the issue. This was caused by a bad update to forge/badmobs. The config spec is being generated at the wrong time so all non-vanilla/properly registered modded mobs are being reported as being incorrectly registered. You can safely disregard this issue.

**Comment by VallenFrostweaver** [comment]
Thanks to Darkhax. It's unrelated to AN so I'm closing the issue
