### ISSUE TITLE
Balancing, glyph, and material suggestions

### ISSUE THREAD

**Issue by Thunder-Nova** [baileyholl/Ars-Nouveau#2]
**Balancing**
Spell book Tiers slot
Tier 1 will have at most 3 slots
Tier 2 will have no more then 5 slots
Tier 3 will have no more then 7 slots
Tier 4 will have 10 slots

Spells only work in their tier or above.

**Spell Glyphs**

Link (tier 2 - Augment) - When used on mob, effect will jump on another per link, on ore act as a veinminer more links more blocks (configuration on this should "Blocks per link", default=3) so 1 link will break 4 blocks, 5 links will break 16=(1+(5x3)).

Terrain (tier 3 - Augment) - Makes some spells affect the world, such as Freezing freeze water to ice, or amplified freezing turn lava to obsidian, puts snow on blocks, fire can smelt cobble to stone and so on.

Lingering (tier 2 - Augment) - similar to lingering potions, freeze cause slowness, harm causes damage (almost same as actual dragon breath), break causes mining fatigue, and so on.

Conversion (Tier 3 - Effect) - This will convert blocks or items to their magical counterpart.

**Materials (most require Conversion)**

Magical sapling: Crafted by any form of conversion on any sappling; Makes a magical tree, materials can be use for wands or/and other plans.

Star Totem: Crafted by throwing a nether star and totem of undying into a lingering conversion spell; part of the tier 4 spell book recipe; this totem acts as a totem of undying but will teleport player to bed as well.

Mirrored portal: build by placing a 2 wide by 3 high glass wall, and casting an 2 AOE + Conversion on the wall, to activate it, you throw a scroll with coordinates on it. Mirrored portal acts as a permanent teleport system by bumping into it.

**Comment by baileyholl** [comment]
These are all great suggestions! Leaving this open as a reference.
