### ISSUE TITLE
[loot table] 1.16.4-1.11.6 issue

### ISSUE THREAD

**Issue by TheLewtz** [baileyholl/Ars-Nouveau#200]
MC 1.16.5
Forge .46

Getting this error:

[net.minecraft.loot.LootTableManager/]: Couldn't parse loot table ars_nouveau:blocks/archwood_wall_sign
com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'ars_nouveau:archwood_wall_sign'

Is there anyway to remove this from trying to be put in loot tables I can do manually on server?  Or a fix for this?  Our server has a lot of loot table stuff and errors add up to issues.

for log
[https://pastebin.com/QrkY4Rja](https://pastebin.com/QrkY4Rja)

**Comment by baileyholl** [comment]
This is removed in the next update, but this particular one should be harmless.
