### ISSUE TITLE
Book 1.16.5

### ISSUE THREAD

**Issue by avescarelo** [baileyholl/Ars-Nouveau#203]
If giving book at login: true
Book gived an every connection player on the server
![image](https://user-images.githubusercontent.com/26678843/111893941-a7db9a80-8a17-11eb-93fe-efc71747583d.png)

Log: https://gist.github.com/pingvikin/5ecd1f7b03f7d2a80dc103f807fffb6c

**Comment by baileyholl** [comment]
This is an issue with some other unknown mod or server setup. You can disable this in the common config.
