### ISSUE TITLE
Crash when going in another dimension with config of the wildens to 0

### ISSUE THREAD

**Issue by SirDevil1213** [baileyholl/Ars-Nouveau#205]
I got a crash when I got in another dimension with the config for the spawn of the wildens to 0. I didn't want them to spawn(already got everything before the update with them) so I put 0 put every time I when to another dimension like the moon of Space Bosstools the server or if in solo the game crash.  I got the same crash in the overwolrd but that was in the mushroom island and sense the update no crash even with the config to 0 otherwise everything seem ok but I didn't test for the nether if that crash or not.
Crash report about going on the moon (other mod) : https://pastebin.com/KABxnxnA

Happen/tested in the version: ars_nouveau-1.16.4-1.12.1, ars_nouveau-1.16.4-1.12.4

Also I don't know if this is normal or not but the Wildens with the Xearo's minimap mod are show as passive mob not hostile and I'm pretty sure they're hostile not passive.

**Comment by SirDevil1213** [comment]
wrong place oopsy

**Comment by baileyholl** [comment]
Should now be fixed, as well as a new dimension blacklist in the config: https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3278608
