### ISSUE TITLE
[Enhancement] Immersive Portals Potential Compatability?

### ISSUE THREAD

**Issue by HockeyZman2000** [baileyholl/Ars-Nouveau#206]
I would really like to see the mana-powered portals from this mod be able to use the Immersive Portals rendering ability to seamlessly link them together if this would be possible. I believe the mod author has a link on their CurseForge page on how to do it. Set it as an optional dependency where it works when alongside Immersive Portals, but can also be turned off manually in configs?

Nice work on the mod by the way!

**Comment by baileyholl** [comment]
It does not look like that mod is really supported for forge anymore, so unfortunately I will likely not add compatibility for that.
