### ISSUE TITLE
[1.16.5] Some AN Projectiles can bypass FTB Chunks Claims

### ISSUE THREAD

**Issue by NillerMedDild** [baileyholl/Ars-Nouveau#211]
Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/1959

**Issue**

> Some of the Ars Nouveau spells can still take effect inside another player's protected chunks. Ones I've identified so far:
> 
>     * Ignite - creates flames
> 
>     * Intangible - makes blocks temporarily non-solid. Can break doors, mess up other connected blocks, and allow access to closed areas.
> 
>     * Conjure Water - 'nuf said
> 
>     * Phantom - creates temporary phantom blocks
> 
>     * Light - creates floating lights
> 
>     * Smelt - can smelt protected logs for infinite charcoal, ores for infinite ingots, and can transform stuff like sand into glass.
> 
>     * Gravity - causes blocks to be affected by gravity like sand. Can be combined with Light to steal blocks.
> 
>     * Interact - bypasses interaction protection, allowing full access to containers, machines, etc

### Versions
- Forge-1.16.5-36.1.0
- ars_nouveau-1.16.4-1.11.6

**Comment by NillerMedDild** [comment]
Edit: I've been informed that you can cast while inside a protected area, as well as into it from outside.

**Comment by baileyholl** [comment]
Fixed in latest

**Comment by NillerMedDild** [comment]
Thanks!
