### ISSUE TITLE
Crafting Recipe Error: ars_nouveau:glyph_dampen recipe missing

### ISSUE THREAD

**Issue by sciguyryan** [baileyholl/Ars-Nouveau#215]
Hi all!

I noticed the following error in my logs:

```[KubeJS Server/]: Error parsing recipe ars_nouveau:glyph_dampen[ars_nouveau:glyph_recipe]: {"type":"ars_nouveau:glyph_recipe","tier":"TWO","input":{"tag":"forge:ingots/nether_brick"},"output":"ars_nouveau:glyph_dampen"}: com.google.gson.JsonSyntaxException: Expected input to be an item, was an object ({"ta...k"})```

I have checked and the recipe for that glyph is indeed missing and the item cannot be crafted at all. I have gone through my scripts and checked that none of them are messing with the item, as far as I can see they should not be and none of them reference it at all.

I am not sure what, if anything, can be done to find and resolve this since I have no idea what is causing it to begin with. Hopefully you might have an idea or two I can test.

**Comment by baileyholl** [comment]
If you remove your scripts, does the book load?
There should be some kubejs commands, I think /kubejs error. Does that output anything helpful?

Any broken recipe can cause this to happen, not just ones that use the involved items.

**Comment by sciguyryan** [comment]
> 
> 
> If you remove your scripts, does the book load?
> There should be some kubejs commands, I think /kubejs error. Does that output anything helpful?
> 
> Any broken recipe can cause this to happen, not just ones that use the involved items.

Thanks for getting back to me. It is definitely a mod conflict of some kind as disabling the kubejs scripts does not impact this at all. I will track it down and report it to the maker of the other mod, and will close this issue as it is definitely not an issue with Ars Nouveau.
