### ISSUE TITLE
[Suggestion] "Chain reaction" augment

### ISSUE THREAD

**Issue by winsrp** [baileyholl/Ars-Nouveau#216]
Level 2 augment

Can be used to great effect, and works a bit more logical with many other spells, allows for friends to have different support spells, instead of everyone having the same ones.

chain reaction = finds a single target of the same type (e.g. wood blocks, iron blocks, enemies, players, etc), in a configured range. Adding another chain reaction, searches for another target in the range of the previous target, and so on.

For blocks, it will automatically search for 10 blocks, (each augment adds another 10 blocks)
for players, and mobs, it will search for up to 2 (each augment adds 1 more entity)

if applied on projectile, touch rune: it will start on the hit object, and use the range to fin another object on the same type from that point. 
if applied to self, it starts on the player, and moves, to find other players near by, (could also heal pets).

special examples:
 
break + chain reaction = breaks tree wood and set of ores, and shift+right click breaks sets of normal blocks, like clay, sand, etc. (can replace Fell spell, this makes more sense to me.)

Works on almost all Spells, applying the buffs, debuffs, damage or effects, to several targets in succession, except for the following ones that might be a bit weird, 

Craft,
Delay, 
Interact, item pickup (but it might), 
Light (doesn't makes sense when making light sources, the rest makes it great for going on groups of friends)
Phantom, place block (might work, but it will be weird)
Access Ender Inventory
Conjure water
Exchange
Fell (well, it might replace this one all together)
Summons

**Comment by HeavyDeception** [comment]
Was just thinking of this. For mining ore veins or large trees.  So I'm just going to support this idea.

**Comment by baileyholl** [comment]
This is actually added by an addon called Too Many Glyphs now :)
