### ISSUE TITLE
Crash while trying wixie Auto potion crafting 

### ISSUE THREAD

**Issue by FoxHound-s** [baileyholl/Ars-Nouveau#217]
I was Trying the potion crafting of wixies and get a ctd

log
https://pastebin.com/9zDcMGhE

**Comment by baileyholl** [comment]
Hello,
What type of potion did you try to craft?

**Comment by FoxHound-s** [comment]
awkward potion

**Comment by baileyholl** [comment]
Latest version fixes this: https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3278608
