### ISSUE TITLE
Reactive II | Recipe different in Worn Notebook

### ISSUE THREAD

**Issue by tweakbsd** [baileyholl/Ars-Nouveau#220]
In the Worn Notebook it is shown that 4 Blaze Powder ist needed for the Reactive II to be applied but it actually uses 4 times tag: **forge:rods/blaze** (this Blaze Rods). 2 Ways to fix it, either update the Worn Notebook or change the recipe to blaze poweder.

**Comment by baileyholl** [comment]
Good catch, fixed in the latest version.

Thanks!
