### ISSUE TITLE
Opening the Creative Spellbook once makes all spells cost very little 

### ISSUE THREAD

**Issue by GottJammern** [baileyholl/Ars-Nouveau#221]
As title.
Projectile-Harm on Novice spellbook consumes about 1/4 mana on new world.
Having Creative Spellbook in inventory does nothing to this cost. Opening the spellbook once, not even creating a spell in it, lowers that casting cost of that same Projectile-Harm spell to almost nothing.

Presumably, opening the Creative Spellbook unlocks all the glyphs so you can actually use them, but they do not show up when going back to use the Novice Spellbook.

Is there anyway to reset my glyph unlock progress, short of uninstalling then reinstalling?

**Comment by baileyholl** [comment]
If you are on 1.16, run /ars-reset.

If you are on 1.15, there is no command.
