### ISSUE TITLE
Wixies Forget potion recipes 

### ISSUE THREAD

**Issue by FoxHound-s** [baileyholl/Ars-Nouveau#223]
If you leave the wixies for a bit , they stop working on the potions even when they have materials and jars, and if you point at the cauldron it says ,  Crafting:air

**Comment by baileyholl** [comment]
I am having trouble recreating this one, is this happening for all potions? Any in specific?

**Comment by baileyholl** [comment]
Did you perhaps click with an empty hand on the jar? That would cause them delete their recipe on world restart, I have just discovered.

**Comment by FoxHound-s** [comment]
Sorry for the late response .I was making potion of fire ressistance and awkward potion ,


> Did you perhaps click with an empty hand on the jar? That would cause them delete their recipe on world restart, I have just discovered.

Dont remember , i will test it maybe thats the issue , i just notice that in the top left corner is a messege 
Crafting:air

**Comment by baileyholl** [comment]
Try 1.15.1, this issue should be fixed.
