### ISSUE TITLE
rebinding keys does not work with mouse buttons

### ISSUE THREAD

**Issue by Xigzagamer** [baileyholl/Ars-Nouveau#225]
I have a mouse with 2 extra buttons on the side of it and I tried to set them to let me cycle my spells for quick and easy access. Needless to say I was a bit confused when I realized I couldn't cycle my spells at all. Eventually I tried rebinding it to another key and it worked.

So for now I'll probably rebind the wheel to like q or something, but it would be nice if this issue could be fixed.

**Comment by baileyholl** [comment]
The keybinds are build directly on top of forge and minecraft. Are you able to assign those keys to any keybind at all?

**Comment by Xigzagamer** [comment]
Normally they work just fine, or at least partially work in the case of 1.12 which is the only version I've had issues with my mouse buttons not working. However, I can't use any mouse buttons at all as keybinds for this mod, when the side buttons didn't work I tried the scroll wheel which also didn't work for me.

I technically was running a bunch of other mods at once, but I don't know if that would impact my ability to bind keys to my mouse since I always do that. However, it is possible that some of the other mods (a few of which were in alpha) could of caused issues.

**Comment by baileyholl** [comment]
This should now be fixed on the latest version
