### ISSUE TITLE
I have a translation into Russian.

### ISSUE THREAD

**Issue by Tortoleto4ka** [baileyholl/Ars-Nouveau#229]
As I understand it, I translated most of the mod, but I didn't translate the articles in the book. How can i do this? I want a full translation of the mod to make it easier to play.

**Comment by baileyholl** [comment]
To translate the book, you will need to copy the book and its entries into a new category with that localization, like a folder ru_ru. An example of past book translations are found here:
https://github.com/baileyholl/Ars-Nouveau/tree/1.16.2/src/main/resources/data/ars_nouveau/patchouli_books/worn_notebook
