### ISSUE TITLE
interact can not open the chest or flip the lever

### ISSUE THREAD

**Issue by Vearmus** [baileyholl/Ars-Nouveau#237]
Combined with projectile, interact can not open the chest or flip the lever or even put an item into an item frame.The spell can only interact the machine of this mod.
And some other bug,smelt combined with fortune does not have multiple production.Cut combined with aoe does not shear multiple sheeps.Pierce does not work.

**Comment by DerringersMods** [comment]
This needs to be unpacked.

- Projectile has to strike something's collider, not its selection box, to trigger. Levers, crops, item frames, etc. may not have a collider.
- Fortune on smelt would be undefined behavior in the general case. For ores processed by break, the loot table for the ore itself controls how fortune processes it. No such preexisting description exists for how to handle ores and other smeltables.
- Augment interpretation (Pierce, AOE) is entirely up to the individual glyph modified.
