### ISSUE TITLE
Using a T3 glyph while holding T1 or T2 spellbook consumes the glyph without allowing you to cast it

### ISSUE THREAD

**Issue by dashkal16** [baileyholl/Ars-Nouveau#244]
While intended behaviour, this leads to the odd situation of being able to use a glyph and apparently "losing" it.

Using a glyph of higher tier than the spell book does work, but the glyph is hidden in the spell book's UI.  It will become available when the book is updated.

To mitigate this, I suggest two fixes:
- A tooltip on Glyph Items indicating what spell books can make use of them
- Displaying glyphs of too high a tier as faded out and unclickable in the spell book's glyph list, with a tooltip indicating why the player cannot add the glyph to the spell bar.

**Comment by DerringersMods** [comment]
For what it's worth, the glyph is actually recorded in the lower tier book; it just can't be added to a spell in that book's editor. Copying to a higher tier book or upgrading the book reveals the glyph.

**Comment by dashkal16** [comment]
This was partially addressed in 90d472317d04cb73f1c0a1e6aa6840e166190d23
Learned glyphs that were too high of a tier will display, with feedback to the player explaining why they cannot add the glyph to a spell.

**Comment by baileyholl** [comment]
Added tooltips to both, this looks mostly addressed.
