### ISSUE TITLE
[Suggestion] Config to disable certain machines or items

### ISSUE THREAD

**Issue by LTCatt** [baileyholl/Ars-Nouveau#245]
I need to disable some items to keep the overall consolidation balanced with other mods, but they can't be disabled in the configuration file...

**Comment by baileyholl** [comment]
Hello,
In 1.16, the best way to disable a block or item is to simply remove the recipe for it. You can do that with Crafttweaker, or with datapacks. To remove enchanting apparatus or glyph press recipes, see the existing recipes here, or the wiki.

**Comment by LTCatt** [comment]
Thanks for your reply!
In fact, I want to disable the mechanism of "throwing warp scroll at the portal to generate a permanent portal". I already have a well-designed teleportation mechanism in my modpack, so generating permanent teleportation portals breaks the overall balance.
As you said, I can delete the warp scroll or brick's recipe. But I want to keep them...
However, if I keep all of them, I have no way to prevent players from spawning portals, which makes me feel very tricky.
In addition, if an item is disabled by deleting the recipe, we also need to manually delete the related pages in the patchouli book, and then check one by one whether there are "related pages" at the end of the other pages that point to the items that have been deleted. This brings great inconvenience to rapid iteration...
Hope this mod can get better and better :D
