### ISSUE TITLE
1.17+ Overhauls

### ISSUE THREAD

**Issue by baileyholl** [baileyholl/Ars-Nouveau#249]
Some API or item breaking changes, some reserved for 1.17:

- Convert Spellbook, whelp, turrets, etc. to Spell API instead of List<SpellPart>
- Standardize API variable names
- Remove all extensions of Arrow Entity
- Convert Spellbook to implement ICasterTool and use SpellCaster
- Convert IToolTip to use TextComponent and not String
- ~~Delete IProxy~~
- Move events to a targetted class, i.e. snare listener to the snare spell.
- Remove Spell Resolver constructors that use List instead of Spell
- Change coldsnap to use Vanilla cold damage
- Convert spell parchment to a Caster Tool that stores color and name etc.
- Rename references of Volcanic Accumulator and Mana Condenser to their respective sourcelink

**Comment by MintTeaTx** [comment]
can we make 3rd party glyphs not scary again
