### ISSUE TITLE
Error with Sylphs 1.16.5

### ISSUE THREAD

**Issue by DatrixTHLK** [baileyholl/Ars-Nouveau#258]
Hi, 

I seem to be crashing because of the sylphs.  Am I suppose to download a coremod or some Library mod?

Crash Log: https://gist.github.com/DatrixTHLK/3043b5809b1cbf8016ae6787a282397d 

Minecraft 1.16.5
Forge 36.1.24
Ars Nouveau:  1.18

**Comment by baileyholl** [comment]
Hello,
This is a bug related to running Java 11, it actually relates to world gen, the sylph is just there along for the ride.
The MC bug is posted here: https://bugs.mojang.com/browse/MC-149777

**Comment by DatrixTHLK** [comment]
Oh ok thanks for pointing that out. I had no idea.
