### ISSUE TITLE
[server crash][infinite loop]Relics' Reflection Amulet does not play well with Ars Nouveau's Wilden Guardian

### ISSUE THREAD

**Issue by Twisted-Code** [baileyholl/Ars-Nouveau#269]
All relevant details I have at the moment (I'll add a log in the morning but my current one needs trimming) are posted on the other mod's tracker, in order to avoid redundancy.
https://github.com/SSKirillSS/relics/issues/17

**Comment by macks2008** [comment]
ah, ok. Yeah I figured it couldn't figure out who to apply the damage to. Presumably what Relics should do is break all three shields on the relic (one for each time that the damage bounced before exhausting the player's defense) and then apply the damage to the player. It sounds like the other dev is already on it, so I'll just leave the other issue open and hope for the best :-)
