### ISSUE TITLE
Projectile spell with freeze crashes the game when hit a Botania's spark

### ISSUE THREAD

**Issue by Vearmus** [baileyholl/Ars-Nouveau#274]
I tried many different kind of spell,only freeze causes the issue.And,combined with cold snap,freeze can also apply slowness to player himself if player is close to the target (this did not happen in the old version of the mod).
[crash-2021-06-12_20.22.01-server.txt](https://github.com/baileyholl/Ars-Nouveau/files/6642176/crash-2021-06-12_20.22.01-server.txt)
![QQ截图20210612203111](https://user-images.githubusercontent.com/47314691/121776237-482c0000-cbbe-11eb-99f1-138492012662.png)

**Comment by Vearmus** [comment]
Oh,and the corrent mod version I played is ars_nouveau-1.16.5-1.18.5

**Comment by baileyholl** [comment]
Fixed on the latest version: https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3349578
