### ISSUE TITLE
Enchantment levels don't depend on enchanting level

### ISSUE THREAD

**Issue by AwesomeSyd239** [baileyholl/Ars-Nouveau#279]
I was trying to calculate the total xp level of enchantments on a player, and noticed that the enchantments in this mod don't scale by level; Mana regen III has the same xp cost as mana regen I.

Current code:
`public int getMinCost(int enchantmentLevel) { return 20; }`
Suggestion:
`public int getMinCost(int enchantmentLevel) { return 1+11*(enchantmentLevel-1); }`
This^ is the scaling that vanilla protection enchant uses.

**Comment by baileyholl** [comment]
Sounds good, thanks!
