### ISSUE TITLE
Game/Server crash on startup with dimension blacklist in use

### ISSUE THREAD

**Issue by Watermalia** [baileyholl/Ars-Nouveau#285]
I currently have the dimension blacklist set as follows:

dimensionBlacklist = [atum:atum, theabyss:death, stacked_dimensions_warden:deeper_dark, twilightforest:skylight_forest, twilightforest:twilightforest, thebeginning:the_abyss_beginning_ground_lands, minecraft:the_end, theabyss:the_end_of_time, theabyss:the_end_of_time_2, minecraft:the_nether, theabyss:theabyssdim, thebeginning:theabyssdimbeginning, theabyss:theabyssdimiceworld, javd:void]

Basically, I only want them to spawn in the overworld.

I can't figure out the format that will make this work. I'm using the names directly given from '/forge dimensions'. I feel like somewhere there should be an example of a list of dimensions rather than just giving an example solely consisting of one dimension.

EDIT: Upon further testing, the following also don't work:

dimensionBlacklist = [minecraft:the_nether]

dimensionBlacklist = [atum:atum]

dimensionBlacklist = [atum:atum ]

dimensionBlacklist = [atum]

**Comment by baileyholl** [comment]
Hello,
Entries in an array require quotes. 
For example: dimensionBlacklist = ["minecraft:the_nether", "atum:atum"]
