### ISSUE TITLE
Revolver shoots on wild hunter cause the game crash

### ISSUE THREAD

**Issue by MasterIMLG** [baileyholl/Ars-Nouveau#288]
While shooting the wild hunter with Revolver from Immersive Engineering and the bullet hits the wild hunter, and the wild hunter summoned wolves.
Or, fire the Revolver around the wild hunter, the bullet didn't hit the wild hunter but attracted wild hunter's hatred and the wild hunter summoned wolves,
under these 2 circumstances the game crashed instantly.
This bug happened when player is at Creative Mode. I didn't test if Survival Mode will be the same.
Mod version is: ars_nouveau-1.16.5-1.18.6

Here's crash report:
[crash-2021-06-19_19.45.41-server.txt](https://github.com/baileyholl/Ars-Nouveau/files/6680605/crash-2021-06-19_19.45.41-server.txt)

**Comment by MasterIMLG** [comment]
By the way, this bug happened when player is at Creative Mode.

**Comment by baileyholl** [comment]
Hello, please try the latest version.
