### ISSUE TITLE
Nouveau wilden stalkers and hunters spawning everywhere.

### ISSUE THREAD

**Issue by Darkmega18** [baileyholl/Ars-Nouveau#289]
I have installed the Atum 2, and the wilden stalkers and hunters spawn all over it in dark areas clogging up the spawns in caves and such. Also, I've noticed that they have the ability to spawn despite having a void flatlands where nothing should be spawnable. Is there a way you could make them only spawn in designated biomes or just overworld locations and not ignore those kinds of things?

**Comment by Darkmega18** [comment]
oh, just noticed a blacklist you have in configs. but regardless, theres still the ability to spawn despite void unless mob spawns are manually turned right off.

**Comment by baileyholl** [comment]
Void has been removed from a valid spawn type in the latest version
