### ISSUE TITLE
Server Crash with Latest Ars Nouveau Version 1.16.5-1.18.8

### ISSUE THREAD

**Issue by TheWitherlord** [baileyholl/Ars-Nouveau#292]
1. Install latest version of the mod  https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3361314

2. Launch dedicated server

3. Game crashes

https://gist.github.com/TheWitherlord/7a6534287f45d8027ed36629396c515d#file-ars_nouveau-1-16-5-1-18-8-server-crash-L61

**Comment by baileyholl** [comment]
Hello, please try this jar once approved in a minute or so: https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3361496
