### ISSUE TITLE
Profiling the mod on a modded server shows interesting results!

### ISSUE THREAD

**Issue by Iacchus-sys** [baileyholl/Ars-Nouveau#295]
![Screenshot_2021-06-24_02-25-32](https://user-images.githubusercontent.com/81411139/123141577-7c8f9e00-d493-11eb-9dc4-a3834a853499.png)
Please check this image but i find it next level dumb that a single mob is eating 11% of a server thread that just seems bit high when ice and fire has dragons and doing half of your one mob!!

mod used to profile the server:https://www.curseforge.com/minecraft/mc-mods/spark

**Comment by baileyholl** [comment]
Can you post the actual profile instead of cherry picking an unhelpful screenshot?

**Comment by Iacchus-sys** [comment]
> Can you post the actual profile instead of cherry picking an unhelpful screenshot?

https://spark.lucko.me/RmrcsdcLgR

**Comment by baileyholl** [comment]
Can you do /forge entity list and show the list?

**Comment by Iacchus-sys** [comment]
![list](https://user-images.githubusercontent.com/81411139/123146034-6cc68880-d498-11eb-8ca0-74875715ebfb.png)
![list2](https://user-images.githubusercontent.com/81411139/123146041-6f28e280-d498-11eb-82d1-d5b7772dec5d.png)
![list3](https://user-images.githubusercontent.com/81411139/123146045-70f2a600-d498-11eb-98e6-95eb32859e2f.png)
![list4](https://user-images.githubusercontent.com/81411139/123146102-7d76fe80-d498-11eb-9a29-76b7d635de81.png)
![list5](https://user-images.githubusercontent.com/81411139/123146139-8962c080-d498-11eb-8b03-e673996bfffd.png)
here is the whole list

**Comment by Iacchus-sys** [comment]
> Can you do /forge entity list and show the list?

any updates?

**Comment by baileyholl** [comment]
There is nothing in this profiler that actually points to anything directly from this mod. 7% of that 11% are entirely vanilla bounding box calculations and movement, both of which use vanilla.

Are you actually having TPS issues? This profile is very strange and the numbers look massively inflated. 40% of the tick time is just in random chunk ticks, which would be concerning if this were a normal profile. 

If you are actually experiencing issues, I would try to take another longer profile playing the game you normally do. If you still find large processing time for wildens, please post it.

If you are not experiencing any issues and /forge tps gives you 20 tps, profiling is pointless.

**Comment by Iacchus-sys** [comment]
> There is nothing in this profiler that actually points to anything directly from this mod. 7% of that 11% are entirely vanilla bounding box calculations and movement, both of which use vanilla.
> 
> Are you actually having TPS issues? This profile is very strange and the numbers look massively inflated. 40% of the tick time is just in random chunk ticks, which would be concerning if this were a normal profile.
> 
> If you are actually experiencing issues, I would try to take another longer profile playing the game you normally do. If you still find large processing time for wildens, please post it.
> 
> If you are not experiencing any issues and /forge tps gives you 20 tps, profiling is pointless.

I will keep looking in to it and update when i can

**Comment by Iacchus-sys** [comment]
> There is nothing in this profiler that actually points to anything directly from this mod. 7% of that 11% are entirely vanilla bounding box calculations and movement, both of which use vanilla.
> 
> Are you actually having TPS issues? This profile is very strange and the numbers look massively inflated. 40% of the tick time is just in random chunk ticks, which would be concerning if this were a normal profile.
> 
> If you are actually experiencing issues, I would try to take another longer profile playing the game you normally do. If you still find large processing time for wildens, please post it.
> 
> If you are not experiencing any issues and /forge tps gives you 20 tps, profiling is pointless.

Update seems like wildern mobs just spawn way to much cause i did a profile with 2 of us on and found that there are 30+ between 2 of wildern mobs so looks like we should just be able to drop the weight of them spawn and solve the issue still want to keep an eye on this tho
