### ISSUE TITLE
[1.16.5] crash on loading world

### ISSUE THREAD

**Issue by Altrath** [baileyholl/Ars-Nouveau#299]
- Running:
1.16.5 forge 36.1.25
ars nouveau 1.18.11

- The modpack is mostly enigmatica 6 with some additions

- The game crashes on loading a world or creating a new one

- Crash report: https://pastebin.com/2hj0uSLj

**Comment by baileyholl** [comment]
PMMOBridge has not been updated to the latest version of the mod, it will need to update to be compatible on current versions.
@MintTeaTx
