### ISSUE TITLE
no ore generation

### ISSUE THREAD

**Issue by jackg2527** [baileyholl/Ars-Nouveau#3]
Hello, I'm excited about trying out this mod, but have strange issue: when I add Ars Nouvaux (AN), no ore generation of any kind is happening (vanilla or modded, I searched for a long time). If I take AN out, rejoin the same world and tp 10,000 blocks away, vanilla ore gen is fine (coal, iron, etc).

I'm on 1.16.2 with Forge 33.0.59 and latest version of your mod. No crash report but I attached log files with AN (no ores) and after removing AN (vanilla ores are back). Also below is a list of the other mods I'm using.

Any help would be appreciated. Thanks in advance!

	Mod List: 
		forge-1.16.2-33.0.59-client.jar Minecraft {minecraft@1.16.2 DONE}
		mcw-bridges-1.0.4-mc1.16.2.jar Macaw's Bridges {mcwbridges@1.0.4 DONE}
		useful_backpacks-1.16.2-1.11.4.80.jar Useful Backpacks {usefulbackpacks@1.11.4.80 DONE}
		repurposed_structures-1.16.2-2.1.3.jar Repurposed Structures {repurposed_structures@1.16.2-2.1.3 DONE}
		AmbientSounds_v3.0.21_mc1.16.2.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
		teleportmod_1.16.2-1.1.2.jar Teleports++ {teleportmod@1.1.2 DONE}
		NetherPortalFix_1.16.2-7.1.0.jar NetherPortalFix {netherportalfix@7.1.0 DONE}
		CreativeCore_v2.0.7_mc1.16.2.jar CreativeCore {creativecore@2.0.0 DONE}
		RingOfGrowth-1.16.2-1.2.1.jar Ring of Growth {ring_of_growth@1.2.1 DONE}
		mcw-trapdors-1.0.0fix-mc1.16.2.jar Macaw's Trapdoors {mcwtrpdoors@1.0.0 DONE}
		platforms-1.16-1.7.3.jar Platforms {platforms@1.7.3 DONE}
		jei-1.16.2-7.3.2.25.jar Just Enough Items {jei@7.3.2.25 DONE}
		movingelevators-1.2.20-mc1.16.2.jar Moving Elevators {movingelevators@1.2.20 DONE}
		gates-1.6.2.jar Gates {gates@1.6.2 DONE}
		mcw-windows-1.0.2-mc1.16.2.jar Macaw's Windows {mcwwindows@1.0.2 DONE}
		curios-forge-1.16.2-4.0.0.1.jar Curios API {curios@1.16.2-4.0.0.1 DONE}
		Patchouli-1.16-42.jar Patchouli {patchouli@1.16-42 DONE}
		BetterCaves-1.16.2-1.0.1.jar YUNG's Better Caves {bettercaves@1.16.2-1.0.1 DONE}
		Waystones_1.16.2-7.2.0.jar Waystones {waystones@7.2.0 DONE}
		RingOfRepair-1.16.2-1.2.2.jar Ring of Repair {ring_of_repair@1.2.2 DONE}
		RingOfMiner-1.16.2-1.2.1.jar Ring of Miner {ring_of_miner@1.2.1 DONE}
		Placebo-1.16.2-4.2.0.jar Placebo {placebo@4.2.0 DONE}
		fakeblocks-1.16.2-1.0.2.jar Fake Blocks {fakeblocks@1.16.2-1.0.2 DONE}
		enderchests-1.16-1.7.1.jar EnderChests {enderchests@1.7.1 DONE}
		WitherSkeletonTweaks-1.16.2-5.1.0.jar Wither Skeleton Tweaks {wstweaks@5.1.0 DONE}
		worldedit-forge-mc1.16.2-7.2.0-beta-04.jar WorldEdit {worldedit@7.2.0-beta-04+98f71a3 DONE}
		u_team_core-1.16.2-3.1.8.179.jar U Team Core {uteamcore@3.1.8.179 DONE}
		increasemobcap-forge-1.16.2-1.0.1.jar Increase Mob Cap {increasemobcap@1.0.1 DONE}
		FastFurnace-1.16.2-4.2.0.jar FastFurnace {fastfurnace@4.2.0 DONE}
		mcws-roofs-1.16.2-v2.0.0.jar Macaw's Roofs {mcwroofs@2.0.0 DONE}
		Apotheosis-1.16.2-4.2.1.jar Apotheosis {apotheosis@4.2.1 DONE}
		mcw-doors-1.0.0-mc1.16.2.jar Macaw's Doors {mcwdoors@1.0.0 DONE}
		grapple_hooks-1.2.0-29.jar Grapple Hooks {grapple_hooks@1.2.0-29 DONE}
		AI-Improvements-1.16.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 DONE}
		mahoutsukai-1.16.2-v1.23.1.jar Mahou Tsukai {mahoutsukai@1.16.2-v1.23.1 DONE}
		Hwyla-forge-1.10.11-B78_1.16.2.jar Waila {waila@1.10.11-B78_1.16.2 DONE}
		ItemPhysic_v1.4.6_mc1.16.2.jar ItemPhysic {itemphysic@1.6.0 DONE}
		forgemod_VoxelMap-1.10.10_for_1.16.2.jar VoxelMap {voxelmap@1.10.10 DONE}
		forge-1.16.2-33.0.59-universal.jar Forge {forge@33.0.59 DONE}
		goprone-1.16.2-1.3.4.jar GoProne {goprone@1.16.2-1.3.4 DONE}
		shetiphiancore-1.16-3.8.1.jar ShetiPhian-Core {shetiphiancore@3.8.1 DONE}
		CleanView-1.16.2-v1.jar CleanView {cleanview@1.16.2-v1 DONE}
		SoundFilters-0.14_for_1.16.2.jar Sound Filters {soundfilters@0.14_for_1.16.2 DONE}
		corpse-1.16.2-1.0.8.jar Corpse {corpse@1.16.2-1.0.8 DONE}
[latest_with AN.log](https://github.com/baileyholl/Ars-Nouveau/files/5213704/latest_with.AN.log)
[latest_remove AN.log](https://github.com/baileyholl/Ars-Nouveau/files/5213705/latest_remove.AN.log)

**Comment by baileyholl** [comment]
Hello,
I am not quite sure why that would be happening, Ars Nouveau with Curios and Patchouli alone has no issue. Another user was able to fix this by removing Optifine. I would try removing performance improving/core mods and see if that fixes it. Otherwise, the ore generation should be fixed in the next update as Forge has added official support for biome features.

Sorry about that!

**Comment by jackg2527** [comment]
Thanks for the reply. Thought maybe the logs would reveal something (I'm not fluent in reading these things).

Glad to hear someone was able to resolve same issue by removing other mod(s). I'll try your suggestions.

Cheers!

**Comment by jackg2527** [comment]
Good news: just installed Forge 34.0.9 and your latest file. Ore gen all good, modded and vanilla. Thanks again.
