### ISSUE TITLE
[Suggestion] Mana powered tick accelerator

### ISSUE THREAD

**Issue by Hiranus** [baileyholl/Ars-Nouveau#300]
Since Ars Nouveau is magical mod it could be good idea to add tick acceleration.
Block that uses mana to accelerate single tile entity in 5x5x5 centered on it. Acceleration speed could rely on amount of Amplify glyphs/acceleration tablets. It could be also ritual that is powered by mana from jars.z
Edit:
It would be also good if we had ability to control it with redstone.

**Comment by baileyholl** [comment]
A tick accelerator is not currently being considered at this time.
