### ISSUE TITLE
[Suggestion] Compound shapes

### ISSUE THREAD

**Issue by jojyjoj** [baileyholl/Ars-Nouveau#302]
Everyone's asking for multiple shapes in the same spell, but I had an idea of how to make it work. There would be three types of shapes; normal ones as they are now, target shapes, and sub-shapes. For example, target projectile plus sub-rune would cast a projectile that has no effect other than to make a rune where it hits, and target underfoot plus sub-rune would leave a rune right beneath you. With the small selection of shapes at the moment, rune would be the only one worth making a sub-shape version of, but the system would be quite useful if a burst, zone, starstrike, or storm type sub-shape was added. This also leaves room for other target shapes, like a projectile that activates on a short timer, instead of just on contact. This would let you attack with bursts at a set distance, being better for crowd control than one that can miss.

A bit more ambitiously, maybe rune could be a trigger and sub-shape, casting a sub-shape when activated instead of directly effecting whoever steps on it.

**Comment by baileyholl** [comment]
This is sort of a thing now with rune becoming an effect, and lingering with the same behavior.
