### ISSUE TITLE
3rd Person rendering broken

### ISSUE THREAD

**Issue by tweakbsd** [baileyholl/Ars-Nouveau#305]
Hi Bailey ! I'm having a weird rendering glitch that I can't figure out myself how to resolve, maybe you got an idea where 
to look in the code.  

When I'm using an Item from Ars Nouveau like my Mage Book or the Enchanters Sword / Bow my face gets a part
of the items texture rendered as overlay in 3rd person.

![2021-06-27_08 38 36](https://user-images.githubusercontent.com/11926641/124591030-196f1580-de5c-11eb-8e22-09190655ecd1.png)

It's also true when in off hand. My Mod list is very long but the main one to interfere here is I think 
Cosmetic Armor Reworked. But if I turn off Cosmetic Armor in the inventory the weird rendering still happens.

My list of mods is very long, so I understand if you don't put much work in this issue. But I'm trying to fix it since Ars 1.11 I think and it makes me go nuts sometimes that this beautiful mod, one of my all time favourites, does not work properly :-(

The mods names ending with MODNAME-tweakbsd.jar are custom version of the mods with little changes from me to fit my 
needs like changing a recipe or disabling a feature. Nothing crazy. 

alexsmobs-1.11.1-tweakbsd.jar
abnormals_core-1.16.4-3.0.6.jar
angelring-1.16.3-1.3.3.jar
Apotheosis-1.16.4-4.5.0-tweakbsd.jar
AppleSkin-mc1.16.2-forge-1.0.14.jar
ars_nouveau-1.16.5-1.18.6.jar
Artifacts-1.16.5-2.9.3.jar
astralsorcery-1.16-1.16.5-1.13.12.jar
AttributeFix-1.16.5-10.1.2.jar
Atum-2.2.5-tweakbsd.jar
AutoRegLib-1.6-49.jar
backpacked-1.7.0-1.16.3.jar
backpacker-1.3.1-1.16.3.jar
bedspreads-forge-1.16.5-5.1.0.2.jar
Botania-1.16.5-417.jar
BotaniaAdditionsMC1.16.3-1.0.4-tweakbsd.jar
Bountiful+Baubles+FORGE-1.16.3-0.0.2.jar
buzzier_bees-1.16.3-3.0.1-tweakbsd.jar
caelus-forge-1.16.5-2.1.3.0.jar
citadel-1.7.1-1.16.5.jar
ClientTweaks_1.16.3-5.3.0.jar
colytra-forge-1.16.5-5.1.1.1.jar
comforts-forge-1.16.4-4.0.1.0.jar
CosmeticArmorReworked-1.16.5-v3a.jar
curioofundying-forge-1.16.4-5.1.0.0.jar
curios-forge-1.16.5-4.0.5.1.jar
curious_shulkerboxes-fixed.jar

customizableelytra-1.16.4-1.5.0.jar
expandability-2.0.1-forge.jar
extraboats-1.16.5-2.1.0.jar
forbidden_arcanus-1.16.3-1.0.4.jar
geckolib-forge-1.16.5-3.0.41.jar
guardvillagers-1.16.5.1.2.4.jar
Hwyla-forge-1.10.11-B78_1.16.2.jar
iceandfire-2.1.8-1.16.5.jar
iChunUtil-1.16.5-10.2.0.jar
ironchest-1.16.4-11.2.10.jar
ironfurnaces-1.16.3-tweakbsd-2.4.0.jar
ironshulkerboxes-1.16.4-5.1.9.jar
itemzoom-tweakbsd-1.16.3-2.3.0.jar
jei-1.16.5-7.7.0.106.jar
JustEnoughResources-1.16.5-0.12.1.121.jar
Kiwi-1.16.3-3.4.1.jar
metalbarrels-3.3a.jar
MmmMmmMmmMmm-1.16.5-1.2.0.jar
MutantBeasts-1.16.4-1.1.3.jar
NaturesCompass-1.16.5-1.8.6.jar
observerlib-1.16.5-1.5.3.jar
occultism-1.16.4-1.5.5-tweakbsd.jar
OptiFine_1.16.5_HD_U_G8.jar
overloadedarmorbar-5.1.0.jar
Patchouli-1.16.4-52-tweakbsd.jar
performant-1.16.2-5-3.66m.jar
personality-1.16.5-1.0.2.jar
Placebo-1.16.4-4.4.5.jar
polymorph-forge-1.16.4-0.18.jar
Quark-r2.4-315-tweakbsd.jar
QuarkOddities-1.16.3.jar
ravageandcabbage-0.1.4-tweakbsd.jar
ruby-1.6.2.jar
save-my-stronghold-1.16.3.jar
scuba-gear-1.16.5-1.0.3.jar
shutupexperimentalsettings-1.0.3.jar
SpartanShields-1.16.5-2.1.2.jar
SpartanWeaponry-1.16.4-2.1.0-beta-4.jar
strawgolem-1.16.3-1.9-tweakbsd.jar
titanium-1.16.3-3.1.0.jar
toughnessbar-tweakbsd.jar
Waddles-1.16.5-0.8.12.jar
xptome-1.16.5-v2.1.jar

**Comment by baileyholl** [comment]
Hello,
Is this reproducible with optifine removed?
