### ISSUE TITLE
Crash with on start with Forge 1.16.5-36.1.61

### ISSUE THREAD

**Issue by Dunkmania101** [baileyholl/Ars-Nouveau#309]
Hello!

That change to the lightning entity that you merged into Forge seems to break a mixin in this mod.

Here's my log file:
[latest.log](https://gist.github.com/Dunkmania101/7c365a3bae6960e31c3dcd62778ce91f)

**Comment by baileyholl** [comment]
This version should fix that: https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3391901
