### ISSUE TITLE
Inferium farmind particles going to a random block, not just the mana condensor

### ISSUE THREAD

**Issue by jbrewer516** [baileyholl/Ars-Nouveau#310]
One of my players is doing some farming and the pink particles are mostly shooting up into the mana condensor but some are going to a random block on the ground and we can't figure out why/now to stop it. 
![Uploading 20210717_144455.jpg…]()

**Comment by baileyholl** [comment]
This is a known bug with the mana condenser when it is broken and moved. 
It will be fixed sometime soon in the future, but for now it is to my knowledge harmless. It should fix itself if you restart the server.

**Comment by baileyholl** [comment]
Fixed in 1.21.
