### ISSUE TITLE
Spell Kills Don't Count as Player Kills

### ISSUE THREAD

**Issue by Icosahunter** [baileyholl/Ars-Nouveau#312]
Just found out that Blazes killed using spells appear to not drop Blaze Rods. [Presumably this is because it is not counting it as a kill by a player](https://minecraft.fandom.com/wiki/Blaze#Drops). The specific spell I used was alternating harm and delay glyphs in a novice spell book.

**Comment by baileyholl** [comment]
I cannot reproduce this, blazes are dropping rods for me using Harm. Are you on 1.16 on a relatively newish version?

**Comment by Icosahunter** [comment]
I was on new versions of everything but I had other mods on so it's possible there were some issues because of that. I'll test it later with just Ars Nouveau and see what I can find. If I get more details on this should I make a new issue or comment it here?

**Comment by baileyholl** [comment]
Feel free to make another issue. Do note, potions inherently do not count as player damage, so killing something without dealing direct damage will not count as a player kill. If you are using wither or poison, make sure you include a direct damage spell somewhere in there.

**Comment by Icosahunter** [comment]
Ok, I'll keep that in mind and make a new issue if I find anything buggy!
