### ISSUE TITLE
Must you update to latest forge?

### ISSUE THREAD

**Issue by Darkmega18** [baileyholl/Ars-Nouveau#313]
This is just a concern. But in my modpack currently I've been playing it on forge 36.1.24. My game is only moderately loaded, at just under 190 mods. and all was fine, until I updated ars nouveau today and was forced to go to 36.1.61. I have a feeling a number of mods have maybe ignored going to that later versions because latest builds can sometimes be buggy and such?

For what the changelog made out to be quite a small update, it made my pack unplayable due to the forge update. when I backdated to ars 1.19.6 all was fine again.

now I'm not blaming you for breaking my game, but this kind of error that produces no error other than a lack of existence is hard to troubleshoot and forcing later updates of your mod to require very new forge versions for something seemingly small feels maybe a touch... reckless, maybe?

unless you potentially have an idea or a strong hunch on who could be causing this issue from this list so I can go report to them?
https://cdn.discordapp.com/attachments/747181991010500690/866302803626819594/unknown.png

**Comment by Darkmega18** [comment]
Ah. it seems to be quite potentially related to sodium, found a similar issue on their github already after I realized what you needed the update for vs what sodium does. :V

**Comment by baileyholl** [comment]
New forge versions are never required unless previous versions of the mod no longer work on latest forge. In this case, all versions before 1.19.6 are broken past Forge 36.1.61. Because of this, 1.19.6 fixes this incompatibility and now requires all newer mod versions to be on this newer forge version.

My hands are tied.
