### ISSUE TITLE
mod breaks my game

### ISSUE THREAD

**Issue by Backis981** [baileyholl/Ars-Nouveau#317]
hello!

today i was gonna play minecraft with mods and one of them was Ars Nouveau and i never had a problem playing with the mod before but all of sudden the game refuses to start. what happens is when i start the game it then loads up and forge doing its thing, but some weird things happens like the loading par fades away when the mojang logo appears but then it comes back but the logo fades while the counter of how mutch MB is useing to load everything up glitches so you cant see the numbers and when its allmoste finished it binks the main menu with the text being replaced with the squre symble, the one where it dosent know what text should be there and resort to those squares and back to the loading screen before it crashes with no error message

i got confjust and wonders what mod was causing this so i removed all the mods to see if i can start the game normaly without any mods
that i can do

after that i put in all the tools needed for all the mods to work
works just fine

after that i put one mod after the other and test which mod did not work
i found out it was Ars

i thout mabye its conflicting with a mod, so i removed all the mods exept for Ars and the other mods it need to work
same thing happend, i couldent get past the loading screen

i then tryed to updated it along with the rest of everything
still dident wanna work

i have no idé what happend to cause this and if i mabye did something as last time i was playing normaly without problem and could boot up and the game and shut it down without problem and then this happend next day

**Comment by baileyholl** [comment]
You likely need to upgrade forge to the latest version, but without a log, I cannot tell what the issue is.

**Comment by Backis981** [comment]
> You likely need to upgrade forge to the latest version, but without a log, I cannot tell what the issue is.

i did upgrade forge aswell but still nothing, i dont know where i can find the log ether if there is one because i dont even get a message that my game crached and the error code for it

**Comment by Backis981** [comment]
i looked it up to find the log to see where it should be and then i to start minecraft again, the game crashes but there is no log thats created in the minecraft folder, absolutly nothing happens

**Comment by Backis981** [comment]
[crash-2021-07-28_10.13.11-client.txt](https://github.com/baileyholl/Ars-Nouveau/files/6891642/crash-2021-07-28_10.13.11-client.txt)

**Comment by baileyholl** [comment]
It appears that somehow your configs have been corrupted. Delete the Ars Nouveau config, as well as all of the configs in the config/ars_nouveau folder.

**Comment by Backis981** [comment]
i deleted the whole folder and the game now works, thank you for the help
