### ISSUE TITLE
[Suggestion] Aim augment for projectile/orbit

### ISSUE THREAD

**Issue by Fabizocker456** [baileyholl/Ars-Nouveau#318]
This would greatly enhance turrets turret-like ability as well as make projectile better at distance and orbit for fast-moving entities. Possibly tier 3, made with bow/skeleton skull? Projectiles should home towards players/entities/blocks, orbiting projectiles could move 1 block (?) up, down, forward and backward as well as increasing and decreasing speed.

**Comment by baileyholl** [comment]
Some addons add this now, like Too Many Glyphs or Ars Elemental.
