### ISSUE TITLE
Worn Notebook won't add to Akashic Tome 

### ISSUE THREAD

**Issue by Seth0067** [baileyholl/Ars-Nouveau#319]
version ars_nouveau-1.16.5-1.20.1.jar

Greetings - on a personal pack , noting that I can not add the worn notebook to an Askashic Tome - either natively or if I whitelist it in that mods config. 

Have added this bug to Akashic Tome, but wanted to double it over here in case its something that can be fixed on your end.

**Comment by baileyholl** [comment]
Hello,
Enigmatica 6 has the worn notebook working with Askashic Tome. 

The worn notebook is actually a patchouli book, I will unfortunately have to point you either to patchouli or to the Tome mod for more information. Are you sure your config is correct?

**Comment by MuteTiefling** [comment]
If you care to take a gander at our whitelist, it may help you figure out what's gone wrong here: 

https://github.com/NillerMedDild/Enigmatica6/blob/master/config/akashictome-common.toml
