### ISSUE TITLE
Minecraft lists dependant mod as not installed

### ISSUE THREAD

**Issue by NachtfaIter** [baileyholl/Ars-Nouveau#320]
I am installing the mod on 1.15.2 and as you know, Ars Nouveau has three dependencies Curios, Patchouli, and Geckolib 2.0. I installed the three mods as listed, and launched my Minecraft as usual but "Geckolib" was listed as not installed. I made sure that I have installed all three mods. I tried uninstalling the mods, restarting my pc but nothing seemed to work out. I am still facing the issue of not being able to launch Minecraft because of Geckolib being listed as not installed.
![Screenshot_735](https://user-images.githubusercontent.com/88140805/127477331-1256715f-a0aa-4cfc-9ba6-df5dde816e5f.png)
[latest.log](https://github.com/baileyholl/Ars-Nouveau/files/6899862/latest.log)

**Comment by baileyholl** [comment]
1.15 requires geckolib 2.0, mod launchers automatically install 3.0. You will need to manually download 2.0.
