### ISSUE TITLE
Generating chunks may crush the game when Biomes O' Plenty is installed

### ISSUE THREAD

**Issue by LTCatt** [baileyholl/Ars-Nouveau#321]
Generating chunks may crush the game when Biomes O' Plenty is installed.
And after deleting Ars from my mods folder, the issue doesn't appear anymore.

![image](https://user-images.githubusercontent.com/40348278/126887708-88e4e72d-79ad-4b4e-b7d4-195426eb1ddf.png)

You can find a crash report in the end of this log file: [latest.log](https://github.com/Glitchfiend/BiomesOPlenty/files/6873373/latest.log)
(in this log was not the latest version, but I was able to reproduce the problem after updating to the latest version 1.20.1)

Related stacks:
> Error executing task on Chunk source main thread executor for minecraft:overworld
> java.util.concurrent.CompletionException: net.minecraft.crash.ReportedException: Exception generating new chunk
> ...........
> Caused by: java.lang.IllegalArgumentException
> at net.minecraft.util.WeightedRandom.func_76273_a(SourceFile:20) ~[?:?]
> at net.minecraft.util.WeightedRandom.func_76271_a(SourceFile:39) ~[?:?]
> at net.minecraft.world.spawner.WorldEntitySpawner.func_77191_a(WorldEntitySpawner.java:334) ~[?:?]
> at net.minecraft.world.gen.NoiseChunkGenerator.func_230354_a_(NoiseChunkGenerator.java:623) ~[?:?]

<br></br>
Reply from BOP's author:
> Some other mod is likely adding an entity spawn with presumably invalid values for the min/max group size (Or the spawn frequency), and you're having the crash happen more frequently because of it spawning in our biomes or whatever.
> Reference: https://github.com/Glitchfiend/BiomesOPlenty/issues/1884

<br></br>
This issue can appear randomly while creating a new world. There is a high probability that it will happen, and five attempts will almost certainly trigger it.
I think this is probably due to the fact that I adjusted some spawn weights in the config file, so here is my config file: [ars_nouveau-common.zip](https://github.com/baileyholl/Ars-Nouveau/files/6909225/ars_nouveau-common.zip)
BOP's config file if you need it: [biomesoplenty.zip](https://github.com/Glitchfiend/BiomesOPlenty/files/6873379/biomesoplenty.zip)

<br></br>
Thanks!

**Comment by baileyholl** [comment]
I am not 100% sure, but I suspect it is because you have set some mob weights to 0. I have added a fix for that now, but in the meantime you should probably set them to 1 if you do not want to crash.

**Comment by TelepathicGrunt** [comment]
@LTCatt, try putting on the mod called Blame and get the crash to happen. Then share the latest.log here. Blame can find and report which entity is the one with invalid weights
https://www.curseforge.com/minecraft/mc-mods/blame

**Comment by LTCatt** [comment]
[07����2021 22:08:44.417] [Worker-Main-30/ERROR] [com.telepathicgrunt.blame.Blame/]: 
****************** Blame Report Mob Weights 1.16.5-3.2.5-forge ******************
  Detected total weight of mob list is 0 or negative which will crash the game! 
  See info below to find which mob is the problem and where it is attempting to spawn at.
 World Registry Name : minecraft:overworld
 Biome Registry Name : minecraft:river
 Classification of entity being spawned : creature
 Entity position :  chunk 6 8
 Weighted list of mobs to spawn : 
    [ars_nouveau:drygmy*(1-1):0]


It seems like because I have set some mob weights to 0.

**Comment by baileyholl** [comment]
Upgrading to 1.21 will let you set the weights to 0 without crashing.
