### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Index: -1, on latest.log (invalid molang)

### ISSUE THREAD

**Issue by aburone** [baileyholl/Ars-Nouveau#323]
This doesn't seem critical or anything but quite annoying
https://pastebin.pl/view/7beb75a3

Ars Noveau is the only mod in my pack who uses geckolib.
I reported this to geckolib and they said:
"you need to contact whichever mod author is using geckolib in your pack. They have invalid molang" 

https://github.com/bernie-g/geckolib/issues/163

**Comment by Sakata-MC** [comment]
Friend of mine just sent me a similar crash. Was just walking around in the game and crashed out with same error:
forge-1.16.5-36.2.2
ars_nouveau-1.16.5-1.20.1
geckolib-forge-1.16.5-3.0.43
gist: https://gist.github.com/Sakata-MC/ec910878a6acb703fb25b3032186d3b4
