### ISSUE TITLE
[1.20.1] Server crash using glyph grow on byg overgrown stone

### ISSUE THREAD

**Issue by radiomike** [baileyholl/Ars-Nouveau#329]
Initially noticed in ATM6-1.7.7 modpack.
Also tested with minimal single player install with

- Forge-36.2.2
- Ars Nouveau 1.20.1 plus dependencies
- BYG 1.3.0 

Crash Report for single player:
[crash-2021-08-14_12.17.14-server.txt](https://github.com/baileyholl/Ars-Nouveau/files/6986369/crash-2021-08-14_12.17.14-server.txt)

**Comment by baileyholl** [comment]
Does it crash if you use normal bonemeal on it?

**Comment by radiomike** [comment]
No, it doesn't

**Comment by radiomike** [comment]
Also, just to note, the bonemeal effect itself does appear to work.

**Comment by tyler489** [comment]
Confused why this is closed? It is still an issue
