### ISSUE TITLE
Extend Time Does Not Seem to Work on Light

### ISSUE THREAD

**Issue by RobuxShooters** [baileyholl/Ars-Nouveau#332]
Extend Time does not seem to augment the duration of night vision and glowing although it is an accepted augment by the Light spell. For instance, Self -> Light gives 30 seconds of night vision while Self -> Light -> Extend Time also gives 30 seconds of night vision, potentially wasting some Source. The same thing happens when casting Light on other entities - they receive 30 seconds of night vision and glowing whether or not an Extend Time augment is used.

**Comment by baileyholl** [comment]
Fixed on the latest version.
