### ISSUE TITLE
Latest update caught by antivirus?

### ISSUE THREAD

**Issue by hacktheplanet86** [baileyholl/Ars-Nouveau#334]
Just tried to update to the latest release and my Windows Defender instantly removes it.  I am not using any files anywhere other than the curseforge app.  There are no crashlogs or anything I can provide as it instantly gets removed and curseforge gives only an I/O error with no explaination.  Installing the release from 8/18 works perfectly fine for now.

    By the way I love your mod.  Carbuncles are the best.

**Comment by baileyholl** [comment]
Windows Defender has been flagging many curseforge mods lately, it is a known issue. Feel free to do an additional file scan on it elsewhere, or build the jar yourself, but it is just a false warning.
