### ISSUE TITLE
[Feature Request] [Suggestion] - Revert the Volcanic Sourcelink Passive Generation.

### ISSUE THREAD

**Issue by nokturnihs** [baileyholl/Ars-Nouveau#337]
It's on the Tin. Been playing on an Enigmatica 6 Server and have lava all over the place and those volcanic accumulators/sourcelinks. Loved it and was building this wizard tower build and made the whole base themed around this mod. But.... You've made them coal generators that are more annoying to work with - passive mana generation doesn't need to be as strong as it was but SOMETHING besides just a decorative (and largely useless) coal generator to produce mana would be nice.... especially since connecting pipes to these things kind of defeats the point. Either that or setup some way for them to magically suck coal out of nearby containers. You have passive generation via the death generators and the crop blossom buggers too. Dunno why the change was made other than they produced a LOT of mana pretty quickly.

**Comment by baileyholl** [comment]
Pedestal support has been added to the volcanic and mycelial sourcelinks.
