### ISSUE TITLE
Familiars may be sucked into PneumaticCraft Vacuum Traps

### ISSUE THREAD

**Issue by MuteTiefling** [baileyholl/Ars-Nouveau#338]
Familiars may be sucked into PneumaticCraft Vacuum Traps and subsequently duped. 

I haven't actually duped them to see what would happen, and I intend to blacklist them in e6, but I thought I'd let you know you can fix this by default simply enough by tagging them as Tamed creatures. 

Any tamed pet is automatically excluded from the vacuum trap.

**Comment by baileyholl** [comment]
Is there a tag like a json file to add? Or are you saying just tamed creatures in general

**Comment by MuteTiefling** [comment]
Just tamed creatures in general are excluded. Like you can suck up a wolf, but not a tamed dog.
