### ISSUE TITLE
Glyph press accepts more than 1 clay

### ISSUE THREAD

**Issue by kill05** [baileyholl/Ars-Nouveau#348]
Hello, while trying to automate some glyphs, i noticed that if you insert magical clay into a glyph press with a pipe/hopper that transfers more than an item per operation, the press will accept and use all the clay into it to make a single glyph, resulting in a clay waste.
Ex. if i have an hopper that moves 4 items per operation, 4 clay will end up into the press and when you insert the other item needed to finish the craft, you will get the glyph but there will be no more clay left.

**Comment by baileyholl** [comment]
Thanks, should be fixed now.
