### ISSUE TITLE
[Issue] Arcane Bricks do not form Warp Portal

### ISSUE THREAD

**Issue by Griese009** [baileyholl/Ars-Nouveau#349]
The default Arcane Brick (which is made out of 4 Arcane Stone) does not form the Warp Portal if a Warp Scroll is thrown into it.
It could be that the Source jar is too empty or too far away, but it did not form when i placed one next to it (either normal filled up or creative one). 

As in the Viedeo Shown below, only the normal arcane bricks are affected!

https://www.youtube.com/watch?v=3Q6Kz5zu-zs

Initial Details:
Modpack: FTB University 1.16
MC-Version: 1.16.5
Ars Nouveau: 1.16,5-1.23.1
Forge: 36.2.2

**Comment by baileyholl** [comment]
This has been fixed in the latest version, the pack will need to update.
