### ISSUE TITLE
[Request] Allow regular 'crafting' recipes in the Enchanting Apparatus to use mana

### ISSUE THREAD

**Issue by MuteTiefling** [baileyholl/Ars-Nouveau#351]
Would be nice to be able to include mana as an optional requirement for certain crafts when making custom recipes. 

Naturally, the JEI recipe would need to differentiate between recipes that do and don't need mana. Don't think it needs to show exact values, but something or people will be very confused when a craft won't start.

**Comment by MuteTiefling** [comment]
Much excite!!!

**Comment by Ridanisaurus** [comment]
Bailey is love.
