### ISSUE TITLE
Bug: Wilden Chimera and Compact Machines.

### ISSUE THREAD

**Issue by Jophire** [baileyholl/Ars-Nouveau#356]
As the title says, I ran into a bug involving Wilden Chimeras being able to break the walls of compact machines.
Not sure if this is an issue of blocks not tagged properly as indestructible or the chimera not respecting modded indestructible blocks.
![Wilden Damage](https://user-images.githubusercontent.com/36978900/132937275-c19ebf15-6e55-443f-b8e8-aca87f66baab.PNG)

**Comment by baileyholl** [comment]
Fixed in the latest version.
