### ISSUE TITLE
Minor visual bug involving Scrying Ritual.

### ISSUE THREAD

**Issue by Cinderheart** [baileyholl/Ars-Nouveau#357]
The ritual works, but the description says that the lights should be changing colour based on distance. Instead, the lights appear multicoloured but primarily white, and their colour does not change at all with distance.

**Comment by baileyholl** [comment]
Were you scrying for things further than 30 blocks? 
They will change to green and blue at 30ish and 50ish blocks, this is more noticeable on the surface when scrying for something like diamonds.

**Comment by Cinderheart** [comment]
I was testing in a superflat world. As I backed up it just turned off.

Could it be that it was because I still had line of sight, rather than having blocks in the way?

**Comment by baileyholl** [comment]
It is mostly for blocks beneath you, the actual scrying radius around you is smaller than your view distance for performance reasons.
