### ISSUE TITLE
Even if PVP is disabled, some AOE can damage other players

### ISSUE THREAD

**Issue by LTCatt** [baileyholl/Ars-Nouveau#363]
Even if PVP is disabled, some AOE can damage other players. Eg. Explosion.
Also, "Freeze" also slows other players down.
Is it possible to make the negative effects of these glyphs only apply to yourself and not to other players? This allows you to simply kill other players on servers that forbid PVP...

**Comment by JMBarber** [comment]
Projectile-Hex-Harm-ExtendTime is capable of killing players outright while PVP is disabled.  We found this out because that exact spell spawned as dungeon loot.

**Comment by LTCatt** [comment]
so is there any plan on this issue?

**Comment by baileyholl** [comment]
This was fixed in a recent 1.19 version.
