### ISSUE TITLE
Textures-related crash ?

### ISSUE THREAD

**Issue by HugoBelotDeloro** [baileyholl/Ars-Nouveau#365]
Hello, I have an Ars Nouveau-related crash on All The Mods 6 v.1.8.3 and 1.8.4 with Ars Nouveau v.1.23.10 and 1.23.11 after upgrading from 1.21.3. On loading a world with some Ars blocks and entities the textures apparently fail to load, crashing the game.

I could not however reproduce this bug in a creative world.

Here's the [log](https://pastebin.com/6XgpjrZV) for one such crash.

**Comment by baileyholl** [comment]
This is an obscure bug with OpenJDK. Not fix is available for this.
