### ISSUE TITLE
[1.15.2 and 1.16.5]Ars Noveeau Client Crash

### ISSUE THREAD

**Issue by NBZion** [baileyholl/Ars-Nouveau#367]
Crashes when installed on server(LATEST 1.15.2), it seems to also happen in 1.16.5. Prevents me from connecting and crashes on join
MODS:
ars_nouveau-1.15.2-1.3.0.jar 
curios-FORGE-1.15.2-2.0.2.7.jar 
[latest.log](https://github.com/baileyholl/Ars-Nouveau/files/7270976/latest.log)
forge-1.15.2-geckolib-2.0.0.jar
Patchouli-1.15.2-1.2-35.jar

**Comment by baileyholl** [comment]
This is a log for 1.15.2, which is no longer supported. Do you have a crash log for 1.16?
