### ISSUE TITLE
It's possible to extract items from the enchanting apparatus while it's in operation, duping them. 

### ISSUE THREAD

**Issue by MuteTiefling** [baileyholl/Ars-Nouveau#368]
Mod Version: ars_nouveau-1.16.5-1.23.11
Forge Version: 36.2.4

Video: https://streamable.com/jmnlh6

Steps to reproduce: 

1. Setup anything to extract from the Enchanting Apparatus
2. Begin crafting
3. The item in the apparatus will be continuously extracted, but not removed, until the craft completes. 

Have confirmed this with Mek pipes and Pretty Pipes. 

https://github.com/NillerMedDild/Enigmatica6/issues/3392

**Comment by Naheulf** [comment]
Also able to reproduce with
- Ars_nouveau 1.23.11 and PneumaticCraft: Repressurised 2.14.4-258
- Ars_nouceau 1.23.11 and Translocators 2.6.0.82

**Comment by MuteTiefling** [comment]
Woot!
