### ISSUE TITLE
Translate to french

### ISSUE THREAD

**Issue by njeudy** [baileyholl/Ars-Nouveau#370]
hello, I would like too translate your module to french .. And I can find .po file to translate ?
Can you indicate me how I have to do ?

thanks for tour dev :)

**Comment by HollishKid** [comment]
I would love to see a french translation also!
@njeudy there are json language files [here](https://github.com/baileyholl/Ars-Nouveau/tree/1.16.2/src/main/resources/assets/ars_nouveau/lang).
Maybe you could create a Pull request with translation?

**Comment by baileyholl** [comment]
PRs are accepted for translation files, there is a patchouli book and a lang book.
