### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by Delsharath** [baileyholl/Ars-Nouveau#371]
I was using my test world to see how my new project will work for my livestream series on twitch and youtube, but when i started to use the spellbook from this mod the game crashed on a harm spell, i sent the crash report to the Curseforge people and they think that this mod was conflicting with another, i have no idea how to fix this or how this problem arose and would like some help with fixing the mod since i want to use this mod alongside others. the crash report is attached
[latest.log](https://github.com/baileyholl/Ars-Nouveau/files/7324534/latest.log)

**Comment by baileyholl** [comment]
You need to update tome of blood.
