### ISSUE TITLE
Crash with Carbuncle

### ISSUE THREAD

**Issue by jaz000** [baileyholl/Ars-Nouveau#372]
I'm sorry it all went a bit wrong

with ars_nouveau-1.16.5-1.23.11
(Medieval Minecraft modpack v31)

Right clicking with dominion wand on carbuncle and then on crystallizer (to link them) and it crashed :-(

hopefully there's a clue in here
https://pastebin.com/CKp00EGR

**Comment by baileyholl** [comment]
This is a rare bug with OpenJDK unfortunately. I added a few extra checks, but any real fix isnt really possible.
