### ISSUE TITLE
Wylden hitbox is too big

### ISSUE THREAD

**Issue by Insane96** [baileyholl/Ars-Nouveau#373]
Compared to mobs of the same size (Zombies) they have way to large hitbox

**Comment by baileyholl** [comment]
Not sure what you mean, the hitboxes are pretty close to their actual model.

**Comment by Insane96** [comment]
![2021-11-20_12 13 38](https://user-images.githubusercontent.com/7185104/142724251-6e3e481e-673d-43b4-8889-5f1f279f7147.png)
Way too big
