### ISSUE TITLE
Crippling Spell lag when breaking AOE, and  especially building AOE.

### ISSUE THREAD

**Issue by spdkils** [baileyholl/Ars-Nouveau#375]
Casting a spell with Underfoot, Conjure Mageblock, AOE x 6 causes server crippling lag. Same lag with place block.

https://spark.lucko.me/YUxvMzbwtT?hl=38,33

This was in the Monsters and Mineshafts pack, I'm going to also confirm it happens solo.

**Comment by spdkils** [comment]
Upon a bit more thought, it shouldn't be creating a fake player when a player casts the spells... This way protection mods will work with who is casting the spell etc. In addition, it should probably only initialize the fake player once per session as the spell turret loads, or when server starts.... Seems like making fake players should be rare.

Maybe I'm not understanding how fake players are supposed to work, but I wouldn't think that a player casting a spell, should ever have a fake player, since the player is the one whom took the action.

However spell turrets it makes sense.

**Comment by baileyholl** [comment]
While there is more that can be done, the bulk of this lag should now be fixed here: https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3575085
