### ISSUE TITLE
Biome ID Error when generating single biome world in 1.16.5

### ISSUE THREAD

**Issue by malice936** [baileyholl/Ars-Nouveau#377]
While working on a personal pack I was attempting to generate single biome worlds in order to configure spawns for those biomes, however whenever I would attempt this for the Archwood Forest, the game would generate terrain then freeze. In order to isolate this issue I attempted several other worlds with different biomes, including modded ones. In order to rule out mod conflicts, I then created a new 1.16.5 instance which only contains Ars Nouveau and it's depencies, and attempted to generate a new single biome world with Archwood Forest, and encountered the same issue.

While I would typically attach a log, the specific error spams the log so rapidly it generates hundreds of thousands of lines of the same error.

"[Render thread/WARN] [net.minecraft.world.biome.BiomeContainer/]: Received invalid biome id: -1"

This error despite my attempts causes the log file to reach a 26MB+ file size which I believe is causing GitHub to reject my upload.

**Comment by baileyholl** [comment]
Hello,
This is an MC bug for 1.16.5. https://bugs.mojang.com/browse/MC-197616
You can fix this by not using a single biome world setting, but by using a configured datapack that utilizes a single biome.
[single_biome_datapack (1).zip](https://github.com/baileyholl/Ars-Nouveau/files/7610174/single_biome_datapack.1.zip)

This is not something I can fix, but that datapack should get you sorted!
