### ISSUE TITLE
Sylph particle render performance is awful (broken particle spawner)

### ISSUE THREAD

**Issue by Kaleidio** [baileyholl/Ars-Nouveau#379]
1.16.5
ars nouveau 1.23.11

Render performance with a sylph on screen stays around normal until a few seconds.  then this tanks render performance all the way down 500% until the entity is off screen.

my 250 mod pack goes from 400 fps down to 70 fps with just one sylph

**Comment by Kaleidio** [comment]
The false spawner is caused by Optifine.  something is wrong with the render code that Optifine doesn't like.  sad to say but this might never get fixed :c

**Comment by Kaleidio** [comment]
It's not optifine, I checked twice

the false spawner appears most often after you pause the client then resume

**Comment by baileyholl** [comment]
If this is an optifine only error, I will not be fixing this, sorry.

**Comment by Kaleidio** [comment]
If I do further testing to check again that Optifine is required, and it results in it not being optifine at fault, would you fix it?

**Comment by Kaleidio** [comment]
retested, please reopen the issue, Optifine is not actually required.

screenshot of proof
![2021-11-22_22 49 51](https://user-images.githubusercontent.com/82226641/142946733-5f3d8451-132c-493f-8351-858170d84bd1.jpg)
:

**Comment by baileyholl** [comment]
Okay, I will look more into it. It appears that the particles are stacking up and never expiring inside their model?

**Comment by Kaleidio** [comment]
actually this looks more like a spawner that is residue of grabbing position data of the entity itself, but that spawner is spitting out so many particles it's insane on the gpu

**Comment by Kaleidio** [comment]
the spawner tends to stick itself in the very far corner of the entity's model "box".

**Comment by Kaleidio** [comment]
the specific pattern the spawner is outputting is in large planar square shapes but rapidly, cascading downward into a pyramid shape.

however if you pause the game, the particles build up even though the client is paused, so after unpausing they make a super bright output.  this might be true for all particle systems, i did not check, but it results in thousands of particles being rendered just after unpausing the game.

**Comment by Kaleidio** [comment]
latest testing seems to have seen it fixed.  closing issue, thanks for the help!

**Comment by Kaleidio** [comment]
reopening as issue is actually still present

**Comment by baileyholl** [comment]
Related to carbuncle animations, these are performed by the Geckolib library. This likely isnt the particles.
