### ISSUE TITLE
Drygmy does not get modded drops from Wither Skeletons

### ISSUE THREAD

**Issue by NillerMedDild** [baileyholl/Ars-Nouveau#382]
I'm not sure whether this is on your side or [Wither Skeleton Tweaks](https://www.curseforge.com/minecraft/mc-mods/wither-skeleton-tweaks), but the Drygmy is unable to get skull fragments from Wither Skeletons.

Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/3565

Version: ars_nouveau-1.16.5-1.23.11

**Comment by baileyholl** [comment]
The drygmy can only pull items from loot tables, other methods would introduce potential dupes from held items, or unintended farms like Wither Stars, another special drop.

**Comment by NillerMedDild** [comment]
Roger, thanks 👍
