### ISSUE TITLE
Feature Request:  Remove the check for Augment Cap

### ISSUE THREAD

**Issue by Boolyman** [baileyholl/Ars-Nouveau#385]
As a pack developer I would like to allow the player to only build spells with X number of augments, but also be able to find Casting Wands, Enchanter's Bows/Swords that I have added to loot tables as special loot that are pre-built with spells that exceed that limit. 

For example. A player may only be able to build a Harm spell of their own with 3x Amplify augments.  But when they fight the Ender Dragon, he drops a special Casting Wand I have added to his loot table, which has a built in Harm-> 5x Amplify augments.  

To do this, I was going to build the wands/bows/swords with the increased augments myself, so they save the NBT data.  Then I would add them to the loot table with that NBT data.  Then I would reduce the augment cap in the config file, so _players_ of my pack could only build their own spells with the normal augment amount.  Unfortunately, you have a "check" in place that prevents any premade items from being used if they contain more augments than the config permits.

If you could add a config option to disable this "check", I would greatly appreciate it.

**Comment by Boolyman** [comment]
Is there any chance you will consider this?  I have been avoiding developing that section of my modpack until I find out if this could be a possibility.

**Comment by baileyholl** [comment]
Added in 1.24.3

**Comment by Boolyman** [comment]
Thanks a ton!
