### ISSUE TITLE
Negative damage?

### ISSUE THREAD

**Issue by BvLiemt** [baileyholl/Ars-Nouveau#387]
Im playing on a server running the modpack 'Enigmatica 6', and was experimenting with some spells. I found that certain spells would deal negative damage, according to a target dummy.

Against other mobs it didnt seem to deal damage at all (it doesnt seem to heal them either) but when I used it against my friend who was wearing mekanism power armour, the server crashed:
[Stack_trace.txt](https://github.com/baileyholl/Ars-Nouveau/files/7523193/Stack_trace.txt)
I dont expect this particular crash report to be useful to you, as the error seems to be thrown by mekanism. Negative damage still seems odd and potentially damage.

We are running ars_nouveau-1.16.5-1.23.11.jar

The spell in question was projectile + fangs + dampen x~5 (idk exactly how many dampens, but a bunch)
Other damaging components (like harm, flare or cold snap) dont seem to have this issue.
This isnt the biggest deal, since why would anyone use a spell with that many dampens, but hey whatever.

**Comment by baileyholl** [comment]
I can't reproduce on the latest version, as there is already a check in place when hitting a living target AND the damage is less or equal to 0. I modified it to not deal damage if it hits a non-living entity as well, but I am not sure how you caused a crash hitting your friend.
