### ISSUE TITLE
Incompatibility with Ars_Nouveau-1.16.5-1.23.11 & JustEnoughResources-1.16.5-0.12.1.128 on mc-1.16.5 Java 15 Multimc

### ISSUE THREAD

**Issue by BLACKBERREST3** [baileyholl/Ars-Nouveau#388]
On the 12th page of mob loot, the client crashes.

**Comment by baileyholl** [comment]
I would need a crash log.

**Comment by BLACKBERREST3** [comment]
[crash-2021-11-14_18.10.48-client.txt](https://github.com/baileyholl/Ars-Nouveau/files/7534893/crash-2021-11-14_18.10.48-client.txt)

ars_nouveau:familiar_jabberwog is the problem.

**Comment by baileyholl** [comment]
This should be reported to JER as this is something they should be checking for.
