### ISSUE TITLE
1.16.5 - Config File ignoring baseMax and glyphMax value changes

### ISSUE THREAD

**Issue by Boolyman** [baileyholl/Ars-Nouveau#397]
The mana usage does not seem to take the config file changes into account.  

I have a wand that is :projectile: :accelerate: :harm: :amplify: :amplify: :amplify: :amplify: :amplify: :amplify: 

My configs are set with the following mana costs:
:projectile: = 5 Mana
:accelerate: = 5 Mana
:harm: = 20 Mana
:amplify: = 10 Mana

The spell should cost 90 Mana.

**My config for player mana is set as follows:**

*#Max mana bonus for tier of book*
tierMax = 50

*#Base max mana*
baseMax = 200

*#Max mana bonus per glyph*
glyphMax = 15

I am using an Archmage Spellbook with 26 Glyphs Unlocked.  I should have well over 400 mana available (IF the config file is working).  However, when I cast that spell that should cost 90 mana, my mana bar drops down to roughly 25% mana left.  Indicating a mana usage of closer to 300 for the spell (assuming my mana bar is at least 400).  I have tested this with multiple other spells that only cost 110 mana, and getting "Not enough mana" errors.  So it seems the config is completely ignoring the baseMax and glyphMax value adjustments.  I have increased baseMax all the way up to 400 and it is having ZERO effect on the player's mana pool.

**Comment by Boolyman** [comment]
After even more testing, and using /data get entity @p ForgeCaps to get my mana totals, the config is applying the baseMax and glyphMax changes, but the spell seems to be costing 3x the amount it should.

**Comment by Boolyman** [comment]
Is there any chance this is actually going to get fixed any time soon?  Spells not actually costing the appropriate amount of mana seems like a pretty critical part of the mod.

**Comment by baileyholl** [comment]
I attempted to contact you via discord.
I cannot reproduce this issue, I have tested the max mana before casting, the calculated spell cost, and the remaining mana after, and all add up correctly. Have you run the data command, cast the spell, and run it again to verify the numbers? A video or series of screenshots would be helpful.

If you have changed the configs, also check that they did not corrupt and regenerate themselves. This can happen with forge configs, and you may find multiple glyph configs in the folder as backups when this happens.

**Comment by Boolyman** [comment]
I am going to have to go through and redo all my ars-nouveau configs again, I will try to get videos.  I didn't know what else I could provide, so I reset them all back to default and just started working on other parts of the pack after I provided all the data and screenshots in your discord.
