### ISSUE TITLE
1.16.5 React Enchantment

### ISSUE THREAD

**Issue by Smartin-b** [baileyholl/Ars-Nouveau#398]
Setting a React Enchantment in an Armor slot via spell parchment in the enchanting Table became impossible, it just says there is no recipie.

**Comment by baileyholl** [comment]
Do you have the previous version of reactive on it? A reactive 2 enchant requires reactive 1 already on the item.

**Comment by Smartin-b** [comment]
I was only refering to having the React enchantment on an armor piece and setting the spell via the enchanting Table. This was possible in previous versions and the patchnotes didnt mention a change.

**Comment by Smartin-b** [comment]
This seems to extend to all enchanting related Recipies.
![grafik](https://user-images.githubusercontent.com/67115074/145732800-ce368436-8c4d-48ff-a09b-ebd613460909.png)
****

**Comment by Smartin-b** [comment]
I also fixed the bug where setting a spell just returned an error, check the PR for details.

**Comment by Smartin-b** [comment]
It should be noted its not quickly fixed by just doing something like:
![grafik](https://user-images.githubusercontent.com/67115074/145860639-d340c5e1-54cf-40fd-8e6f-e03247c70cb9.png)
because this does not include the subclasses e.g. the Reactive and Spellwrite classes and their functionality.
I think thesubclasses lack the proper registration, but i dont know forge that well.

**Comment by baileyholl** [comment]
These should be fixed here: https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3565827
