### ISSUE TITLE
[1.15.2] Disconnect from server when trying to make a glyph without enough mana.

### ISSUE THREAD

**Issue by SuicidalSteve** [baileyholl/Ars-Nouveau#4]
I was trying to make a glyph on a server, and just as I was about to put the TNT in the glyph press for what I vaguely recall was the explosion glyph I shortly saw the message about not having enough mana pop up in the chat, after which it disconnected me. I have been unable to join the server since.

The server didn't crash so there are no crash logs, the client logs don't seem to show anything related to what may have caused the disconnect.
Server console output at time of disconnection:
https://pastebin.com/v8bBJpjb

Versions:
- Forge 31.2.30
- Ars Nouveau 1.15.2 - 0.17.1
- astralsorcery-1.15.2-1.12.9

Edit: Astral Sorcery version added to the list, as it showed up in the server console output.

**Comment by baileyholl** [comment]
Resolved in next update
