### ISSUE TITLE
Craft fiber problem

### ISSUE THREAD

**Issue by TheComputerHead** [baileyholl/Ars-Nouveau#400]
Hi, i'm in 1.16.5 and i don't know why but 2 craft are making a conflict so i can't craft MageBloom Fiber
![image](https://user-images.githubusercontent.com/90097802/145806779-d50ebe01-047a-4c4c-bf54-3e15855dd947.png)

**Comment by baileyholl** [comment]
This has been fixed here: https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3565827
