### ISSUE TITLE
1.16.5-1.24.7 Worn Notebook added to player inventory on every login

### ISSUE THREAD

**Issue by jkwphysics** [baileyholl/Ars-Nouveau#401]
Currently all players on my private server have the notebook added to their inventory on every single login. I've done it several times logging out and in again and am generating a book each time. I've tried making all subjects marked as read, which doesn't affect it.

Notable output from the server during login:
`Server thread/ [minecraft/TrackedEntity]: Fetching packet for removed entity ItemEntity['Worn Notebook'/18704, l='ServerLevel[world]', x=-2913.10, y=103.00, z=2497.40]`

This doesn't print out every time (not most of the time actually).  I can also note that it happens even if you keep the previous notebook in your inventory.

**Comment by baileyholl** [comment]
The fix for this at the moment is to disable the option in the config. This is an unknown mod conflict that is breaking the player data saving for the book.
