### ISSUE TITLE
Magebloom unable to craft magebloom fiber

### ISSUE THREAD

**Issue by 7Slade7** [baileyholl/Ars-Nouveau#403]
Idk if I need to use the apparatus but I am unable to craft any magebloom fibers since putting the magebloom on the crafting table only makes pink dyes.

**Comment by 7Slade7** [comment]
Fyi I have a bunch of mods rn and I'm now checking if any of them are conflict with this.

**Comment by baileyholl** [comment]
This is fixed in the latest version.

**Comment by 7Slade7** [comment]
Ah I should have checked first. Thank you and sorry for the trouble.
