### ISSUE TITLE
Fell spell on a spell turret won't cut a tree down

### ISSUE THREAD

**Issue by DanMenk** [baileyholl/Ars-Nouveau#408]
Tried using an enchanted spell turret and a timer spell turret to cut a tree down. I tried using oak, acacia, and spruce for the tree, but the spell turret couldn't even break the base of the tree, much less cut down a whole tree. 

Originally, I tried touch > fell > AOE x2 with the spell parchment onto the turret but it didn't work, so I tried increasing the AOE to x8 and it still didn't work.

I tried casting touch > fell > AOE x2 and touch > fell > AOE x8 spells from my spell book and it worked just fine.

**Comment by DanMenk** [comment]
minecraft version 1.16.5

ars nouveau version 1.23.11

**Comment by baileyholl** [comment]
This is likely because you are on a claimed chunk of some kind, either FTB or Minecolonies. You need to add Minecraft and potentially ArsNouveau as an ally to those in order to allow turrets to break blocks.
