### ISSUE TITLE
1.18 Bugs

### ISSUE THREAD

**Issue by Sarenor** [baileyholl/Ars-Nouveau#411]
I rushed through the 1.18 port yesterday (thanks for the quick update, by the way!) and stumbled upon a few minor bugs.
If you want to continue focusing on the improvements laid out in the release-notes, please ignore this issue!

Found issues:

- Guidebook does not have a recipe for the Glyph-Crafting of Aquatic, Heal and Intangible
- Lesser Ring of Discount Recipe and Bookwyrm Charm Recipes do not work
- Scribe-Table drops 2 Scribe-Tables upon destruction

I have never done Minecraft Modding before, but I am technically a Java-Dev.
If I can help in any way I'd at least try.

(I'm currently using All The Mods 7 and Forge 39.0.9)

**Comment by baileyholl** [comment]
These have been fixed here: https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3586355
The glyph recipes will come later as they are being reworked.
