### ISSUE TITLE
Starbunkle pathfinding testing visuals are seen in normal play

### ISSUE THREAD

**Issue by Len777** [baileyholl/Ars-Nouveau#412]
Starbunkle's pathfinding areas are visible in black squares surrounding it to show its pathfinding. This is likely a bug, so I'm putting it here.
![image](https://user-images.githubusercontent.com/96889428/147786520-999a43de-a1fd-4352-867b-bb1d37e4583a.png)

**Comment by baileyholl** [comment]
I think a setting was flipped, that is not on be default.
