### ISSUE TITLE
Timer Turret, Projectile, Touch, And Redstone For Free

### ISSUE THREAD

**Issue by imakunee** [baileyholl/Ars-Nouveau#417]
ars_nouveau-1.18.1-2.0.2.jar
Forge 39.0.9

The book describes Timer Turrets as not using source to cast Projectile, Touch, and Redstone. A Timer Turret using Touch -> Place Block and another using Touch -> Smelt are consuming source. Dunno if the description is misleading me or if the turrets are bugged. Ty for your work!

**Comment by baileyholl** [comment]
It just means that touch, projectile, and redstone individually are free, not the entire spell.
