### ISSUE TITLE
Crash when launching the game

### ISSUE THREAD

**Issue by mouse0270** [baileyholl/Ars-Nouveau#420]
After updating to 1.18.1-2.0.2 I get the following crashing when trying to launch minecraft `java.lang.NoSuchFieldException: WATER_ESSENCE`

[crash-2022-01-04_17.34.43-client.txt](https://github.com/baileyholl/Ars-Nouveau/files/7810806/crash-2022-01-04_17.34.43-client.txt)

**Comment by baileyholl** [comment]
Hello,
Can you please post the entire log file, and also attempt to launch without optifine?

**Comment by mouse0270** [comment]
Actually, I think it was curse forge client being stupid. It wasn't deleting the 2.0.1 version of the mod when I upgraded. I manually deleted the old version, and I was able to launch the game.
