### ISSUE TITLE
[1.18.1] Weird items in lootr chests

### ISSUE THREAD

**Issue by itsdinkd** [baileyholl/Ars-Nouveau#429]
IS there any way to disable tomes such as in the screen from being found in Lootr chests (or even regular chests)
![image](https://user-images.githubusercontent.com/35115304/148853627-134c270b-f5c0-462a-81c8-d2e3f4c1d2ab.png)
 

or even items that are supposed to be only obtained by killing certain mobs, or trading certain things from being placed in Lootr chests / chest loot? 

Would love for control over this as currently these items spawning in chests make it easy to progress in Ars or gain a crazy tome book

**Comment by baileyholl** [comment]
https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3757209
