### ISSUE TITLE
1.16.5 Enchanter's Bow and Shield not craftable via Enchanter's Apparatus

### ISSUE THREAD

**Issue by rxg6009** [baileyholl/Ars-Nouveau#432]
Tried at first in Enigmatica 6 modpack (1.16.5, version 1.24.6), when trying to make enchanter's bow (top left pedestal had block of source gems, top middle block had block of gold, and top right block had glyph of projectile all as detailed in JEI and the worn notebook), "no recipe found" message given when enchanting apparatus was right clicked with bow. Tried again with latest release of 1.16.5 (version 1.24.14) and same result

**Comment by baileyholl** [comment]
This was a bug with the modpack itself, and I believe has been fixed. I would update the pack if you can, try again, and report back to them if you still cannot craft the items.
