### ISSUE TITLE
1.16.5 Add awkward potion variants of custom potion recipes

### ISSUE THREAD

**Issue by djmattyg007** [baileyholl/Ars-Nouveau#433]
In this file, some custom brewing recipes have been defined that let you make existing potions with water, rather than awkward potions.

The thing is, I already have some very nifty automation set up for potions based on awkward potions, and it would be easier for me to re-use that automation than set up a brand new line of machines just for these potions.

Would you accept a PR to add variants of these custom recipes that use awkward potions as the base?

**Comment by baileyholl** [comment]
I would not be opposed to it, the only tricky question would be wixie automation. Wixies craft water based recipes for free - would adding these new recipes with the same potion output cause her to consume awkward potions now? There is no special case for her to favor water based potions as it stands. 

Maybe the potions themselves should be slightly modified so the wixie can make them distinct, by either increasing the level of the potion or the time of it.
