### ISSUE TITLE
[1.18.1] Missing textures and inconsistencies

### ISSUE THREAD

**Issue by T3sT3ro** [baileyholl/Ars-Nouveau#434]
Missing/incorrect block textures:
- bookwyrm lectern - missing break particle texture
- * sourcelink - break particle resolution too high (probably)
- * spellturret - break particle resolution too high (probably)
- archwood chest - break texture should be archwood plank (as in vanilla chest). Resolution too high, uses including alpha
- spell prism - break particles resolution too high, uses some weird break texture with alpha
- whirlspring blossom - has alpha in break particles
- Agronomic Sourcelink - break particles include alpha, res too high
- Source Jar - break particles are purple
- Glyph Press - missing break particle textures
- Enchanting apparatus - missing break particles
- Arcane pedestal - break particle res too high, includes alpha
- Scribe's Table - break particles too high res, includes alpha
- Source Relay * - break particles too high res, includes alpha
- Rune - missing texture in creative EQ, break particles include alpha (OK but they could spawn letters from galactic alphabet)
- Imbuement chamber - missing break particle textures
- Arcane core - break particles too high res, includes alpha
- Lava Lilly - break particles include alpha
- Creative Source Jar - break particles are purple
- Wixie Caludron - break particles too high res, includes alpha
- Ritual Blazier - break particle missing texture
- Potion Jar - break texture is blue
- Potion Melder - break texture resolution too high, includes alpha
- Drygmy Henge - break texture resolution too high

What I mean by "break particles includes alpha and resolution is too high":
![image](https://user-images.githubusercontent.com/5300963/149818747-e84abee1-fc14-46e3-88a1-918a5d6abd12.png)
particles sample block's texture randomly and select parts, where alpha is 0, making some particles semi-transparent and of irregular shape. Sometimes it's OK to include alpha (lilly, leaves and generally things with 16x16 texture)

Also while I'm at it I think some attention should also be given to sounds:
- Whirlspring blossom has placing/breaking sound of a stone
- *jars and Mender could use glass texture and sound for breaking.

**Comment by spectrumTF** [comment]
My game actually constantly crashes because of this mod's textures so yeah... Pls fix.
