### ISSUE TITLE
[1.16.5] drop fps

### ISSUE THREAD

**Issue by dayd21git** [baileyholl/Ars-Nouveau#435]
**Mod:** [ars_nouveau-1.16.5-1.24.14](https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3598702)
**Screen:** [day-d.ru/logs/ars-nouveau/issues-435/scr0001.jpg](https://day-d.ru/logs/ars-nouveau/issues-435/scr0001.jpg)
**Forge:** 36.2.22

**Comment by baileyholl** [comment]
Are you using an AMD cpu?

**Comment by dayd21git** [comment]
> Are you using an AMD cpu?

Yes

**Comment by baileyholl** [comment]
How much memory are you allocating? Are you seeing spikes from the garbage collector?

Either way, animations on mobs are made using Geckolib. Several users have reported this issue, but it seems to be hardware specific, and is not something I will likely be able to fix.

**Comment by dayd21git** [comment]
> How much memory are you allocating? Are you seeing spikes from the garbage collector?
> 
> Either way, animations on mobs are made using Geckolib. Several users have reported this issue, but it seems to be hardware specific, and is not something I will likely be able to fix.

It is very profitable to connect third-party libraries and blame the authors of these libraries for the problems, right? Try to write your mod without using third-party libraries, or contact the author of GECKOLIB and figure out this problem. The quality of your mod depends on it.

P.S. Google translate

**Comment by baileyholl** [comment]
Yes I am very much profiting from my $2 a day in Curseforge points. I am sorry you are upset with your purchase of this entirely free, publicly available, and buildable from source product - I will be sure to include this feedback in my yearly review for this job.
