### ISSUE TITLE
[1.18.1] crash when place scribes table

### ISSUE THREAD

**Issue by LeoBeliik** [baileyholl/Ars-Nouveau#436]
## versions:
 ars_nouveau-1.18.1-2.1.0
 curios-forge-1.18.1-5.0.6.0
 geckolib-1.18-forge-3.0.7
 jei-1.18.1-9.2.3.78
 forge-39.0.59

## crash report
https://gist.github.com/LeoBeliik/d80d7a1d6288844cf7de1adf50f3f9b3

## description
it chashes as soon as I place the scribes table in the world.
tested on a new world on survival and creative.

**Comment by baileyholl** [comment]
Fixed here: https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3619899
