### ISSUE TITLE
Rune + blink crashes game

### ISSUE THREAD

**Issue by Zeta314** [baileyholl/Ars-Nouveau#44]
Applying the rune on the ground with the blink effect, it crashes the game. 
Everytime you load the world it keeps crashing it.
You might want to teleport the player to the location he's looking at, or to a location defined by the caster.

**Comment by baileyholl** [comment]
Hello,
Is this on the latest version? Some changes to runes have been made to make them more stable.

**Comment by Zeta314** [comment]
I'm using the 1.2.4 version. It's the latest one for 1.16.3.

**Comment by baileyholl** [comment]
Fixed in the latest version!
