### ISSUE TITLE
Crash Looking at item in jei

### ISSUE THREAD

**Issue by Tyrius1** [baileyholl/Ars-Nouveau#440]
Title says it all. Was looking through JEI on my server and scrolled to the ars nouveau page. Once i hovered over an item the client crashed. 
Minecraft 1.18.1
Forge 39.0.59
Ars 2.1.1

https://pastebin.com/ET5cjaGs

Crashed again this time it crashed the moment it was supposed to load the ars nouveau page.

**Comment by Raidobw2** [comment]
I got the same error, seems to have happened when I updated to `geckolib-1.18-forge-3.0.10.jar`. Same stacktrace as well.

**Comment by C0rn3j** [comment]
Downgrading to `geckolib-1.18-forge-3.0.9.jar` works around the issue.

**Comment by Raidobw2** [comment]
Hi, the implemented fix works with `geckolib-1.18-forge-3.0.11.jar` as well. Thanks for the amazing service!

**Comment by baileyholl** [comment]
Fixed on the latest version.
