### ISSUE TITLE
[1.16.5] [client-side crash] Geckolib 3.0.64 causes JEI item render crash

### ISSUE THREAD

**Issue by Kzeroko** [baileyholl/Ars-Nouveau#442]
[crash-2022-01-29_04.01.00-client.txt](https://github.com/baileyholl/Ars-Nouveau/files/7963035/crash-2022-01-29_04.01.00-client.txt)

Here's the crash report.

How to reproduce: scroll multiple JEI pages at once.

Version: ars_nouveau-1.16.5-1.24.14

**Comment by TheWitherlord** [comment]
Ok yeah same issue here.

**Comment by Kzeroko** [comment]
Tests have been made, and it seems that the new version of Geckolib (3.0.64) broke some of the item rendering.(?)
Downgraded Geckolib to 3.0.63, everything works fine now.

**Comment by C0rn3j** [comment]
Dupe of https://github.com/baileyholl/Ars-Nouveau/issues/442 I think.

**Comment by baileyholl** [comment]
Fixed on the latest version.
