### ISSUE TITLE
[1.18.1] Agronomic Sourcelink not producing source when other Sourcelink(s) are not chunkloaded in server

### ISSUE THREAD

**Issue by ChickenMobile** [baileyholl/Ars-Nouveau#447]
Whenever myself and another player are online: source collects normally when crops grow. However when either myself or they are offline or all Agronomic Sourcelinks aren't chunkloaded in the server at once: they do not collect any source.
My base has 1 Agronomic Sourcelink with a Source Jar immediately on top. They have multiple Agronomic Sourcelinks with jars within 5 blocks of them. 
We did not test with any other types of Sourcelinks, but it may produce the same bug.

This was on a server with Ars v1.18.1-2.0.4, ATM7 modpack v7-0.2.20, using forge v39.0.10.

**Comment by baileyholl** [comment]
This is a known bug with that version. You need to upgrade the mod.
