### ISSUE TITLE
Crash Report: com.hollingsworth.arsnouveau.client.renderer.item.SpellBookRenderer.getRenderColor

### ISSUE THREAD

**Issue by Composed67** [baileyholl/Ars-Nouveau#450]
[crash-2022-02-04_12.42.12-client.txt](https://github.com/baileyholl/Ars-Nouveau/files/8005487/crash-2022-02-04_12.42.12-client.txt)

**Comment by EightBlade** [comment]
I had the same issue.

https://pastebin.com/1c9k6jzx

**Comment by baileyholl** [comment]
Upgrade Ars Nouveau and geckolib to the latest versions.
