### ISSUE TITLE
here's a new Wilden Hunter model if you want it.

### ISSUE THREAD

**Issue by HarroldSaxon** [baileyholl/Ars-Nouveau#451]
Thanks for using Geko lib! It's amazing that it supports custom models in texture packs! I made a new Wilden Hunter model for my server's modpack, and just thought I'd offer it up if you wanted to do something with it. It is still a bit rough, and is pretty lazily fit to the texture, but I thought it might be useful. It's just always bugged me how much they look like players >.<
![Hunter](https://user-images.githubusercontent.com/16321509/152655851-9aea6845-29c9-4e53-b090-787b1192fec4.png)

[wilden_hunter.geo.zip](https://github.com/baileyholl/Ars-Nouveau/files/8008745/wilden_hunter.geo.zip)

**Comment by baileyholl** [comment]
No thank you,
but it looks really cool!
