### ISSUE TITLE
tree generation config bug

### ISSUE THREAD

**Issue by StoneScone** [baileyholl/Ars-Nouveau#452]
when changing tree generation in the config I don't notice a difference, even when I change it to zero trees still spawn. This maybe a bug ore intentional but the option of disabling archtrees maybe useful for modpack developers in the future.

**Comment by baileyholl** [comment]
This is now fixed here, and the config has a new name. https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3647553
