### ISSUE TITLE
Spell damage potion not working

### ISSUE THREAD

**Issue by MauroVanHoutte** [baileyholl/Ars-Nouveau#455]
Spell damage II is not affecting fangs and lightning glyphs, some other glyphs i tested do seem to work

**Comment by MauroVanHoutte** [comment]
after more testing the spell damage potion actually reduces the damage of my lightning spells somehow

**Comment by baileyholl** [comment]
What version?

**Comment by baileyholl** [comment]
Fixed here: https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3675568
