### ISSUE TITLE
Enchanting Apparatus dupe on extract

### ISSUE THREAD

**Issue by MuteTiefling** [baileyholl/Ars-Nouveau#456]
Mod Version: ars_nouveau-1.16.5-1.24.14

Enchanting Apparatus recipes with two or more outputs lead to dupes if extracting with xNet (probably others) if the extraction is done at a rate of one item at a time. 

For example, if a recipe should give 2 clay and xnet is used to pull the item at the end of the craft, you can end up with 3 clay if xnet is pulling a stack size of 1.

More info and a video in our issue tracker: 

https://github.com/EnigmaticaModpacks/Enigmatica6/issues/4212

**Comment by baileyholl** [comment]
fixed here: https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3648653

**Comment by MuteTiefling** [comment]
<3 thanks!
