### ISSUE TITLE
Summon Decoy Glyph crashes on 1.18.1 server when using Radium

### ISSUE THREAD

**Issue by Kuusotare** [baileyholl/Ars-Nouveau#465]
https://pastebin.com/5BH0zkeg

**Comment by baileyholl** [comment]
This should be reported to Radium :)

**Comment by BookerCatch** [comment]
Adding the following lines to the radium.properties file in the config folder will prevent crashes for the meantime, albeit at the cost of the disabled optimizations.

mixin.entity.collisions=false
mixin.entity.data_tracker=false
mixin.entity.data_tracker.no_locks=false
