### ISSUE TITLE
Description: Ticking entity (wixie) 

### ISSUE THREAD

**Issue by namuistree00** [baileyholl/Ars-Nouveau#466]
When wixie is activated, the game crashes.

crash reports is here
https://pastebin.com/fXSZ9v12

This is the version I use
minecraft 1.18.1
ars_nouveau-1.18.1-2.2.5
forge 39.0.76

windows 10
NVIDIA GeForce GTX 1060

**Comment by baileyholl** [comment]
What inventories do you have near the wixie?

**Comment by namuistree00** [comment]
> wixie 근처에 어떤 인벤토리가 있습니까?

Barrel was on the block right next to it.

**Comment by baileyholl** [comment]
This has been fixed here: https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3654291
