### ISSUE TITLE
[1.16] Wilden Hunter/Stalker not falling through fence gates

### ISSUE THREAD

**Issue by johtoRegion** [baileyholl/Ars-Nouveau#468]
This is a small issue, but the Wilden mobs take up enough space in width to not fall through fence gates, which are stalling out my mob grinder. Originally, I thought that the one-block hole was not enough, but after expanding it to 3x3, I found out that it was the fence gates themselves that were keeping them from dropping down.

**Comment by baileyholl** [comment]
Fixed here: https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3675568
