### ISSUE TITLE
[1.18.1] Dynamic Lighting from 2.2.6 cross mod interaction with Lucent mod

### ISSUE THREAD

**Issue by Raidobw2** [baileyholl/Ars-Nouveau#471]
Hello, between update 2.2.5 and 2.2.6 something seems to have changed in the mod causing the Lucent mod (a dynamic lighting mod https://www.curseforge.com/minecraft/mc-mods/lucent) to no longer work on blocks. Entities still glow in the light's area of effect as well as the player hand and the torch item. However, light from Lucent is no longer propagated onto blocks.
Turning on or off the option for dynamic lighting in the ars nouveau client config does not solve this.

Using `lucent-1.18.1-1.2.0.jar` and `ars_nouveau-1.18.1-2.2.5.jar` and holding a torch at night will light up surrounding blocks.

Using `lucent-1.18.1-1.2.0.jar` and `ars_nouveau-1.18.1-2.2.6.jar` and holding a torch at night will however not light up the nearby blocks, but will light up entities, the player hand and held items by the player.

I saw in patch notes that ars nouveau's dynamic lighting is still experimental so that's to be expected. But if I were to turn off the dynamic lighting in the future in the ars nouveau config, perhaps it would be a plus if the mod still played nice with other dynamic lighting mods, allowing for further customization.
Thanks for checking it out if you've got the time!

**Comment by baileyholl** [comment]
Is this with Ars Nouveau dynamic lighting on or off?

**Comment by Raidobw2** [comment]
Yes this is for both cases, with ars nouveau dynamic lighting set to false, and on a second test set to true. Thanks for the reply!

**Comment by baileyholl** [comment]
Please try this version and let me know if it works as expected now when the lighting setting is turned off: https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3658370

**Comment by Raidobw2** [comment]
Hello, tested with Lucent and the new 2.2.7 update. It works perfectly with the setting turned off now. Thanks you very much and I wish you good development!
![lightsEnabled_false](https://user-images.githubusercontent.com/17010632/155268474-4a294128-4747-449c-876c-c0897e0fffa1.gif)
