### ISSUE TITLE
Enchanting apparatus is not using any source

### ISSUE THREAD

**Issue by pafeuu** [baileyholl/Ars-Nouveau#472]
I dont know if it was changed  but the book says it should still be using source.

**Comment by baileyholl** [comment]
Only certain recipes use source like enchantments, listed in JEI if so.

**Comment by pafeuu** [comment]
Well the enchantments recipes are not listed in JEI at all. Also there is still animation for source coming from jars into enchanting apparatus even if it doesnt use any.
