### ISSUE TITLE
Spellbook radial menu offset by 1

### ISSUE THREAD

**Issue by SzczurekYT** [baileyholl/Ars-Nouveau#474]
Hello.

I just updated Ars Noiveau to latest version and I noticed a bag with spell book radial menu. When I open it and press 1 it selects seconds speel, when I press 2 it selects thrid spell, when I press 0 it selects eleven spell. By that I can't select first spell with my keyborad and I'm able to select eleven spell by pressing 0. Basically every key gets a spell offset by 1.
I hope you understand what I'm talking about.
![image](https://user-images.githubusercontent.com/67533827/155602599-f5a4b5d7-cff2-44cb-89a6-491da7880122.png)

Edit: Misspelled word

**Comment by SzczurekYT** [comment]
Not sure but setting int i = 0 in https://github.com/baileyholl/Ars-Nouveau/blob/b553de1c76209603374ea4f9af0da7deeb7a0fb5/src/main/java/com/hollingsworth/arsnouveau/common/items/SpellBook.java#L167 might fix that.

**Comment by SzczurekYT** [comment]
Tried, it isn't that.

**Comment by baileyholl** [comment]
Fixed in this commit: https://github.com/baileyholl/Ars-Nouveau/commit/2a5725f546a98e90e3d545abb0e48c9478054a2a
