### ISSUE TITLE
[1.18.1] missing the source gem and the Glyph Press with everything related to it (clays)

### ISSUE THREAD

**Issue by patipati1** [baileyholl/Ars-Nouveau#476]
There really isn't much to say, I wish they would fix this bug because it covers 50 or 60 percent of the mod

I hope you take care of this to be able to fix it as soon as possible

**Comment by baileyholl** [comment]
Progression was changed in 1.18, glyph crafting does not use a glyph press or clays anymore. It now uses the scribes table. Please check the Worn Notebook documentation again for the new process.
