### ISSUE TITLE
enforceCapOnCast Config not working

### ISSUE THREAD

**Issue by Boolyman** [baileyholl/Ars-Nouveau#478]
You guys added that awesome bypass for devs to put stronger weapons in the loot, than what the player can make themselves.  But its not working.  I put "legendary" wands into the loot table, that have 5x amplify augments on them (the player is capped at crafting wands with up to 3).  But when the player finds one of my legendary wands, it tells them that the wand has too many amplify augments.  I have the config set to "false", so it should not be enforcing the cap when they try to cast.... only when they try to craft the wand themselves.

This is on 1.16.5

**Comment by baileyholl** [comment]
Hello,
Please try this version: https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3675568
