### ISSUE TITLE
Crash when creating new world (NullPointerException: mouseClicked event handler)

### ISSUE THREAD

**Issue by alexblaauw** [baileyholl/Ars-Nouveau#479]
When clicking on "Create New World" in the singleplayer world selector, the game crashes instantly. I suspect this has something to do with Ars Nouveau being incompatible with certain biome mods.
Here is the crash log: [https://crashy.net/FEdRZf1BA84waLWjelUm](https://crashy.net/FEdRZf1BA84waLWjelUm)

From my experience this happens on all versions of ars nouveau 1.18 starting with 2.2.3
The forge version I'm using is 39.1.0

**Comment by alexblaauw** [comment]
Never mind, this was due to my version of Terrablender not being up to date.

**Comment by baileyholl** [comment]
Is this with the archwood tree config set to 0?

**Comment by baileyholl** [comment]
Please try this version: https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3675983

**Comment by alexblaauw** [comment]
Ah, it was with archwood trees set to like 0.000001
I didn't think the game would consider this the same as 0
Thanks for the hotfix though!
