### ISSUE TITLE
Warp Scrolls don't work well with different dimensions

### ISSUE THREAD

**Issue by jgross-hardt** [baileyholl/Ars-Nouveau#480]
When storing coordinates in a Warp Scroll then switching dimensions and teleporting you teleport to coordinates you stored in the first dimension but in the second dimension. This is a problem because it can't be guaranteed that the player would have been able to reach the position they end up in, in any other way. Apart from the fact that this behavior is unintuitive and might cause a player trying to escape a dangerous situation in a nether fortress by attempting to teleport to their house in the overworld, to fall into lava (if this seems oddly specific, that's because that's exactly what happened to me) this allows travelling to the world border by storing coordinates in the overworld and teleporting there in the nether repeatedly (starting 1000 blocks away from the origin this would take about log_8_(30 000 000 / 1 000) ~= 5 Warp Scrolls and 40 Obsidian), as well as making reaching the outer end islands without defeating the ender dragon trivial. With other mods installed this causes issues with any kind of "pocket dimensions" (depending on implementation) like the ones created by Compact Machines and Applied Energistics for Spatial Storage. Two possible fixes: 1. Warp Scrolls only work in the dimension their coordinates were stored in. 2. Warp Scrolls teleport players across dimensions. Looking at the NBT data Warp Scrolls already seem to store some kind of dimension information, so the current behavior might not even be the intended one. (Tested in both direwolf20 1.13.2 (ars nouveau version 1.24.14) and ars nouveau 2.2.9 on it's own)

**Comment by baileyholl** [comment]
added in 1.19
