### ISSUE TITLE
[1.18.1] Invisible Particles

### ISSUE THREAD

**Issue by achaeus** [baileyholl/Ars-Nouveau#483]
When using the [Oculus](https://www.curseforge.com/minecraft/mc-mods/oculus) mod with shaders enabled, particles become invisible.

### Reproduction Steps
1. install [Rubidium](https://www.curseforge.com/minecraft/mc-mods/rubidium) and [Oculus](https://www.curseforge.com/minecraft/mc-mods/oculus)
2. enable any shader
3. use any spells from the book that produces a particle

### Screenshots
![2022-03-08_11 37 47](https://user-images.githubusercontent.com/14109675/157161573-088b8bc7-1a65-4cbb-bc51-d862eaa2216a.png)
![2022-03-08_11 37 57](https://user-images.githubusercontent.com/14109675/157161575-bef38d92-fcae-4d19-b4e5-2a140ede53bc.png)

### Mod Version
1.18.1-2.2.10

**Comment by baileyholl** [comment]
Hello,
It isn't possible to support shader or performance mods, you should report this to those mods and see if they are interested in a compatibility.

Malum and Eidolon also use very similar particles, I suspect those mods won't appear for you either.

**Comment by coderbot16** [comment]
@baileyholl I think you just need to revert this and then the particles will work again, custom core shaders do not work properly with Oculus and Iris and this one appears to not serve any purpose: https://github.com/baileyholl/Ars-Nouveau/commit/b52e77e0a81d7ed77d19b82348376f8f7971d4ca

**Comment by baileyholl** [comment]
@coderbot16 
Ive deleted that unused shader for this version: https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3800858

**Comment by coderbot16** [comment]
Nice! I don't actually use or develop Forge mods but I maintain Iris for Fabric and just happened to notice while looking around on the Oculus fork repository.
