### ISSUE TITLE
1.19 Breaking API Changes

### ISSUE THREAD

**Issue by baileyholl** [baileyholl/Ars-Nouveau#485]
Fix Spell Casters being 1 indexed, and subsequently the radial menu
Store Spell as a compound tag
Store ParticleColor as a tag
Register glyphs with Resource Locations
Remove Spell Parchment recipe, create when scribing
Make cast methods in AbstractCastMethod return booleans for successful cast or fail

**Comment by dkmk100** [comment]
rituals also with resource locations?
