### ISSUE TITLE
[1.16.5] SkinsRestorer plugin + Mohist

### ISSUE THREAD

**Issue by HacksLua** [baileyholl/Ars-Nouveau#487]
I'am install ars nouveau(last and prev) in mohist (last and prev), server online-mode=false, install skinsrestorer.
Accessories not work
i'am delete skinsrestorer
Accessories work...
in online-mode=true Accesiries work
\o/ 
Another plugins for fix skin in unofficial server give the same effect

In 1.18.1 everything works fine

(online-mode=true)
![L6K7OH13l3M](https://user-images.githubusercontent.com/20579067/158438728-eb5ade3b-5c1b-4e1e-aa93-29a5bb74b4db.jpg)

**Comment by baileyholl** [comment]
Hello,
Mohist is not supported for this mod.
If you are referring to accessories as that tab, that is the mod Curios, not Ars Nouveau. I don't expect Curious to support Mohist either though.
