### ISSUE TITLE
Failure message: Mod ars_nouveau requires geckolib forge-1.16.2 or above after its new update yesterday

### ISSUE THREAD

**Issue by BedrockLegends** [baileyholl/Ars-Nouveau#49]
[crash-2020-10-30_18.59.26-fml.txt](https://github.com/baileyholl/Ars-Nouveau/files/5468266/crash-2020-10-30_18.59.26-fml.txt)

**Comment by baileyholl** [comment]
The latest geckolib is not supported. Please try this version: https://www.curseforge.com/minecraft/mc-mods/geckolib/files/3071704
