### ISSUE TITLE
Bookwyrm charm duplication

### ISSUE THREAD

**Issue by northstar462** [baileyholl/Ars-Nouveau#491]
When breaking a bookwyrm lectern, it drops the bookwyrm lectern as well as a bookwyrm charm. If the bookwyrm lectern is placed back down, it re-summons the bookwyrm and you're still left with the charm. In this way you can create infinite bookwyrm charms. The lectern should either revert to a regular lectern when broken, or not drop the charm.

**Comment by baileyholl** [comment]
This has been fixed in the latest version.
