### ISSUE TITLE
[1.16.2][1.18] Add-on glyph configurations duplicated to config/ars_nouveau

### ISSUE THREAD

**Issue by DerringersMods** [baileyholl/Ars-Nouveau#495]
You might want to ensure that add-on glyphs don't get picked up when AN builds glyph configurations. My add-on glyphs have not-so-functional configurations created in config/ars_nouveau, but if I rely on that then users sometimes end up with [crashes](https://github.com/DerringersMods/TooManyGlyphs/issues/1).

**Comment by dkmk100** [comment]
I don't understand what the actual issue is here. What in the configs doesn't work right with addons?

**Comment by DerringersMods** [comment]
Core AN nondeterministically may or my not create configs for add-on glyphs under its own folder. If it does, they appear to take precedence over the mod's own folder.

**Comment by dkmk100** [comment]
Context: Glyph Configs for addon-provided glyphs only show up non-deterministically.
The suggested fix is for AN to register its configs for addon-contributed glyphs immediately when the glyphs are registered. Which is confirmed safe by the fact that you may declare configuration right at mod construction.
