### ISSUE TITLE
Can craft any glyph with any recipe (Ex. tier 2 glyph using only a crafting table)

### ISSUE THREAD

**Issue by K-Fitzpatrick** [baileyholl/Ars-Nouveau#496]
## Reproduction
1. Open catalog by using Novice Spell Book on Scribe's Table
2. Choose "Craft" glyph, click Select
3. Throw Crafting Table (the only ingredient) onto Scribe's Table
4. Quickly, before the animation is complete:
    1. Use Novice Spell Book on Scribe's Table again
    2. Click any other glyph (Ex. "Flare") and click Select (make sure you have enough EXP)

## Current result
**Once the animation completes, the newly selected glyph is created (Flare), not the glyph you gave the ingredients for (Craft)**

## Expected result
Either the first craft cancels, or the correct (first) glyph is created. Should not get the second selected glyph using the ingredients of the first glyph.

## System info
Current version: ars_nouveau-1.18.1-2.3.0
Other mods: Using [Another Quality Modpack 3](https://www.curseforge.com/minecraft/modpacks/another-quality-modpack-3/files), version AQM3-1.8

**Comment by baileyholl** [comment]
https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3757209
