### ISSUE TITLE
enforceCapOnCast Config STILL not working

### ISSUE THREAD

**Issue by Boolyman** [baileyholl/Ars-Nouveau#498]
This is still broken.  The config is still being ignored.
![2022-04-05 01_10_41-Greenshot](https://user-images.githubusercontent.com/24765883/161690572-d1de4062-1250-47ef-8f0c-9b44d529a21d.png)

**Comment by Boolyman** [comment]
This is on 1.16.5 ars version 1.24.21

**Comment by Boolyman** [comment]
Does anyone read these?

**Comment by baileyholl** [comment]
https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3757167
