### ISSUE TITLE
[1.16.5] Source Jars only visually show source from top and bottom but not the sides

### ISSUE THREAD

**Issue by Kaligraphy22** [baileyholl/Ars-Nouveau#500]
Hello there. As the title says, source jars be a bit odd. Nothing game breaking though. I'm using "ars_nouveau-1.16.5-1.24.21" and "geckolib-forge-1.16.5-3.0.65", Patchouli as well but I doubt that's affecting this small issue. Potion Jar and Potion Melder do not have this issue. I still get info in the upper left corner about how full it is so no problems there. Here's two pictures:

![2022-04-10_11 59 35](https://user-images.githubusercontent.com/72703227/162630965-44174c94-2072-4b86-9b93-590bc75b177e.png)
![2022-04-10_11 59 43](https://user-images.githubusercontent.com/72703227/162630974-333cd799-e7b4-403c-9e03-fa0f916ee7f7.png)

**Comment by baileyholl** [comment]
This is common with mods that change rendering. Optifine, magnesium, etc. Are you using any of those?

**Comment by Kaligraphy22** [comment]
Yep, using magnesium. Can I mess with some settings in magnesium to fix this? If not and I have to remove magnesium to fix this, then I'll just ignore the odd rendering. Magnesium has been an actual boon for me for higher and smoother fps, unlike Optifine.

**Comment by baileyholl** [comment]
I am not sure of any setting within Magnesium, but it has been a common issue.
