### ISSUE TITLE
Config Options for "Treasure" Spells

### ISSUE THREAD

**Issue by Chubblezap** [baileyholl/Ars-Nouveau#501]
There doesn't currently seem to be any way to configure these, and it would be nice if there was a way to modify how these work or disable/enable specific ones for balance concerns. In particular the "Takeoff!" spell feels extremely strong to find early on and as an occasional pack maker I'd like a way to tone that down without barring people from making their own flight spells once they hit tier 3.

**Comment by baileyholl** [comment]
Added to both 1.18 and 1.16 now https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3757209

**Comment by Proxwian** [comment]
That's just a joke... player can use this trash spell books even with 1 max mana cap
