### ISSUE TITLE
1.16.5 Keybind Capture Conflict.

### ISSUE THREAD

**Issue by Splutty** [baileyholl/Ars-Nouveau#506]
The keybind for "(Spell Book) Toggle Selection HUD" gets captured without having an actual spell book in your hand.

This causes other mods that use the same key as a keybind to fail to ever get that event (presumably when later in the loading list).

Specific situation: Same key for "Toggle Selection HUD" (Ars) and "Construction Mode" (Dank Storage), since I have that key for "Select" on all mods that have it.

Pack this happens in: E6E, but I'm fairly sure that's irrelevant for this issue. Yell if it's not or not reproduceable.

**Comment by baileyholl** [comment]
Let me know if this version fixes it: https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3765287
