### ISSUE TITLE
Crash while looking through jei

### ISSUE THREAD

**Issue by Sazra** [baileyholl/Ars-Nouveau#507]
My game crashes while trying to look through jei.
Tried geckolib 3.0.67 and 3.0.68, both with the same problem. If downgrading helps which version should I use?
[crash-2022-04-18_19.59.53-client.txt](https://github.com/baileyholl/Ars-Nouveau/files/8507257/crash-2022-04-18_19.59.53-client.txt)
[crash-2022-04-18_19.47.57-client.txt](https://github.com/baileyholl/Ars-Nouveau/files/8507259/crash-2022-04-18_19.47.57-client.txt)

**Comment by baileyholl** [comment]
Hello,
You are on a very old version of the mod. You need to upgrade.
