### ISSUE TITLE
Break spell crashes game when used on Refined Storage Exporter

### ISSUE THREAD

**Issue by jbruce4390** [baileyholl/Ars-Nouveau#508]
If you attempt to use break on a Refined Storage exporter the game crashes. All other Refined Storage blocks seem to be fine just crashes on the exporter.
Using Modpack FTB Direwolf20 1.16

**Comment by JonasDoe** [comment]
I'ld like to add - this even brings down a server. I'm experiencing it atm with Enigmatica 6 Expert.

**Comment by baileyholl** [comment]
Fixed next version
