### ISSUE TITLE
[1.18.2] Scribe Table Enchanter's Sword Duplication

### ISSUE THREAD

**Issue by pooniomoment** [baileyholl/Ars-Nouveau#512]
i put crafting on a sword and took it out of the table, then broke the table and a copy of the sword dropped, despite the table being empty
the sword is the exact same as the other one but now has crafting AND amplify, which can't even be created
i am unable to reproduce this, i don't even know what caused it

**Comment by baileyholl** [comment]
Cannot reproduce, but may have been due to a previous issue with data saving.
