### ISSUE TITLE
[Suggestion] Carbuncles can harvest Magebloom too?

### ISSUE THREAD

**Issue by ryantancock** [baileyholl/Ars-Nouveau#515]
I did not realize until too late that Carbuncles only harvest nearby Sourceberries, and do not harvest Magebloom the same way. 

I'm not sure if this is intentional or not, but I think it would be nice to allow Carbuncles to harvest nearby Magebloom as well.

I read the manual after troubleshooting for a while, and they indeed are only listed as harvesting Sourceberries, which is not super intuitive to someone new to this mod. While I don't expect them to be harvest *all* crops, I thought that the two Ars-Nouveau crops would be harvestable by them. Thanks!

**Comment by baileyholl** [comment]
They are intended not to, as there are several other farming options in the mod :)
