### ISSUE TITLE
[Bug 1.18.2] CTD with Rubidium Dynamic Lights and Ars Noveau

### ISSUE THREAD

**Issue by XaosKitsune** [baileyholl/Ars-Nouveau#516]
When creating a world, or joining an existing one, with both mods active, the game crashes to desktop.

I was able to consistently recreate the issue using only Rubidium(0.5.2a), Rubidium Extras(v1.3.1), Rubidium Dynamic Lights(v1.3.1), and Ars Noveau(2.4.0)+dependencies.

I also tried turning the 'dynamic lights' setting on and off for both mods, but the crash still occurred.

[crash-2022-04-29_14.27.14-client.txt](https://github.com/baileyholl/Ars-Nouveau/files/8593056/crash-2022-04-29_14.27.14-client.txt)

I have also posted this issue on the Rubidium Dynamic Lights page, as someone experienced a similar crash involving the ATM 7 mod pack.

**Comment by CrispyMerchant** [comment]
I'm experiencing the same issue on one of my custom packs with dynamiclightsreforged(v1.3.1) + rubidium_extras(v1.3.1). The crashes stop occurring whenever I disable Ars_Noveau(v2.4.1) + dependencies. 

Here are my crash log if it helps at all:
[crash-2022-05-16_02.43.19-client.txt](https://github.com/baileyholl/Ars-Nouveau/files/8698530/crash-2022-05-16_02.43.19-client.txt)

**Comment by baileyholl** [comment]
This is a change they will need to make, or PR for. In the meantime, this version and 1.19 now support full dynamic lights when using /ars-light on. It is an identical implementation to that mod. You can add new sources via the client config.
https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3888205
