### ISSUE TITLE
Crash when attempting to use Grow function in incorrectly bonemealable plants

### ISSUE THREAD

**Issue by Reshy** [baileyholl/Ars-Nouveau#517]
https://github.com/AOCAWOL/BYG/issues/723#issuecomment-1113245154

As mentioned here, some mods have incorrect implementations for "bonemealable" and when called with Grow they cause a hard crash.

https://pastebin.com/CqPCKBMm

Example log.

**Comment by baileyholl** [comment]
Hello,
Looks like from that thread it is a known issue with BYG. They will need to fix it on their end when they have time.
