### ISSUE TITLE
[1.18.2] Ars incompatibility with Wildfire's Gender Mod

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [baileyholl/Ars-Nouveau#519]
# Info
**Reproduceable:** Always
**Version:** latest release for all.

# The bug:
Basically, whenever I change values within [Wildfire's Gender Mod](https://github.com/WildfireRomeo/WildfireFemaleGenderMod) the values reset.

# Reproduction:
1. Install ars and it's dependencies as-well as the Gender mod (latest release)
2. Open Minecraft
3. Press "G" to open the menu and choose to adjust character
4. Mess with the values
5. Close menu
6. Open menu again and see that the values haven't changed.

# Expected behaviour:
1. Install ars and it's dependencies as-well as the Gender mod (latest release)
2. Open Minecraft
3. Press "G" to open the menu and choose to adjust character
4. Mess with the values
5. Close menu
6. Open menu again and see that the values have changed and saved properly to the config.

# Misc:
I tested well over 250 mods and ars is the only one this happens one so I'm confident in saying that ars can add a compat to ensure this doesn't happen.

If more info is needed I'm happy to supply them.

**Comment by baileyholl** [comment]
Fixed in next release from this mod or if this PR is merged: https://github.com/WildfireRomeo/WildfireFemaleGenderMod/pull/61
