### ISSUE TITLE
[1.18.1] Description: Exception in server tick loop

### ISSUE THREAD

**Issue by OposDev** [baileyholl/Ars-Nouveau#523]
**Error:** 
`Description: Exception in server tick loop` 
`java.lang.NoSuchFieldError: DIRT`

**Versions:**
Minecraft: `1.18.1`
Mod: `ars_nouveau-1.18.1-2.3.0 & ars_nouveau-1.18.1-2.3.1`

**Game:** Singleplayer and Multiplayer

**Replicate:** Right clicking on the `Earth Essence` item crashes the game

**Crash Log:**
[crash-2022-05-06_01.28.28-server.txt](https://github.com/baileyholl/Ars-Nouveau/files/8637783/crash-2022-05-06_01.28.28-server.txt)

**Comment by baileyholl** [comment]
Hello,
That version of forge is incompatible with the mod, as they removed the DIRT tag at one point in 1.18.1. As 1.18.1 is no longer receiving updates, you would need to try an older version of forge, or attempt to upgrade to 1.18.2. 
Sorry about that.
