### ISSUE TITLE
Issue with Item Pickup Glyph

### ISSUE THREAD

**Issue by auroralovecraft** [baileyholl/Ars-Nouveau#524]
Playing on Medieval Minecraft 1.16.5 on a server with my friends, I made him a copy of my own using the scribed table, and we've had no issue until now. When modifying Touch - Break with Item Pickup, we found the things he was breaking showing up in my inventory. Perhaps because I created the book? I tried logging out to see if that would affect anything, and the things broken with the spell stopped appearing in either of our inventories. We resolved the issue by clearing the spell entirely and re-doing it, and things returned to normal. To clarify, items I broke with Touch - Break - Pickup did not appear in his inventory, only his appeared in mine, until I relogged and it broke altogether.

**Comment by baileyholl** [comment]
Are you playing on LAN, or a modified server?

**Comment by auroralovecraft** [comment]
it's just a server my friend is running. I know it's not on LAN, but I'm not sure what 'modified' would mean in this instance. We made some changes to various mod configs for other mods, but nothing to Ars Nouveau.
