### ISSUE TITLE
[1.16.3] [1.3.1] Server Console Spam

### ISSUE THREAD

**Issue by Kris1432** [baileyholl/Ars-Nouveau#53]
Getting the below spammed in the console, like 5 or 6 lines per second!

>.... [12:21:57] [Server thread/INFO] [STDOUT/]: [com.hollingsworth.arsnouveau.api.spell.SpellResolver:wouldAllEffectsDoWork:157]: no work
>.... [12:21:57] [Server thread/INFO] [STDOUT/]: [com.hollingsworth.arsnouveau.api.spell.SpellResolver:wouldAllEffectsDoWork:157]: no work
>.... [12:21:57] [Server thread/INFO] [STDOUT/]: [com.hollingsworth.arsnouveau.api.spell.SpellResolver:wouldAllEffectsDoWork:157]: no work
>.... [12:21:57] [Server thread/INFO] [STDOUT/]: [com.hollingsworth.arsnouveau.api.spell.SpellResolver:wouldAllEffectsDoWork:157]: no work

**Comment by Kris1432** [comment]
Updated the title as I updated the mod but still get the error

**Comment by allout58** [comment]
https://github.com/baileyholl/Ars-Nouveau/blob/afbb602351d743b5875aca7346c0326eee93a560/src/main/java/com/hollingsworth/arsnouveau/api/spell/SpellResolver.java#L157

**Comment by baileyholl** [comment]
Resolved in the latest issue.
