### ISSUE TITLE
Jar of Light - Render Issue

### ISSUE THREAD

**Issue by AetheriMC** [baileyholl/Ars-Nouveau#530]
Minecraft v1.18.2
Forge v40.1.0
Ars Nouveau v1.18.2-2.4.1
Mods that may be affecting: Dynamic Lights v1.18.6

Issue: The jar of light will render light around a player when on the player's hotbar or held, but will not render light for other players viewing that player if the jar is not being held.

To be clear, the issue is not with the light being visible when the jar is on the hotbar, just that other players cannot see it.

Much appreciation.

**Comment by baileyholl** [comment]
Hello,
Other players would need to have dynamic lighting enabled in Ars Nouveau to see it. It is off by default.

Other dynamic lighting mods can cause a conflict, but I don't know about this specific case.

**Comment by AetheriMC** [comment]
Hi there,

I think I should clarify. The issue is that when the Jar of Light is in your main hand, both I and other people on the server are able to see the light source around me as generated by dynamic lights, but if I remove the jar from my mainhand (leaving it on the hotbar), only I will see a light source from the jar. Every other player just sees darkness. This is with Dynamic Lights activated for all involved via the configs.

Dynamic lights seems to be detecting the jar of light on the hotbar and is appropriately summoning a light source for the possessing player to see but unless it's also being held, it's failing to generate a corresponding light source for other players.

**Comment by baileyholl** [comment]
Ah makes sense, other clients do not know the contents of other players inventories besides their held items.

**Comment by AetheriMC** [comment]
Very inconvenient! :D 

The Jar of Light already has an on/off setting for the decorative (i.e. optional) light orb that follows you around. Would it be possible to somehow signal to dynamic lights that a light source need be present for other clients if the jar has been switched on? I suppose at that point the decorative light source would have to be less optional, otherwise other players will still be unable to see your light unless you've opted to turn the orb on, but half the fun of having a magic item is showing it off anyway lol.

This is probably not a large issue for most people. We run a RP server that includes player classes and are worried about the immersion-breaking aspect of having the equivalent of an "invisible" torch. Either way, I'm appreciating the response.

**Comment by baileyholl** [comment]
Hello,
This should now be fixed in this version: https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3814106
