### ISSUE TITLE
Projectile not rendering

### ISSUE THREAD

**Issue by AefRal** [baileyholl/Ars-Nouveau#534]
The simple spell of projectile+harm does not render.
There's a noise, and entities are damaged at range.
Lucent's dynamic lights work too.
So I see the ground light up as it flies towards its target, but no actually projectile is visible.

Also noticed an Ars Nouveau mage casting lightning on husks. I could see a feint glowing outline of lightning, but the bolt itself did not render.

I'm playing FragmentCraft, 
Which has
Ars_elemental-1.18.2-0.3.1.2
Ars_instrumentum-1.18.2-2.2.0
Ars_nouveau-1.18.2-2.4.0
ArsOmega-2.1.0

I added
Lucent-1.18.2-1.2.2
Rubidium-0.5.2a

Realized there's was already a mod called
DynamicLights-1.18.6, but I didn't get a conflict message and the dynamic lighting works.

I've looked through other posts, nothing really regarding this bug.

Thanks in advance.

**Comment by baileyholl** [comment]
Hello,
Please try this version, and make sure your particles are enabled (not set to minimal).
https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3800858
Thank you

**Comment by AefRal** [comment]
I'll try that version.

Also, I always play with full particles, couldn't stand it otherwise.

**Comment by baileyholl** [comment]
Ive had some people confirm that this appears to be fixed in the latest version, going to close this for now
