### ISSUE TITLE
broken dependency on geckolib

### ISSUE THREAD

**Issue by LlubNek** [baileyholl/Ars-Nouveau#54]
Looks like you're using the wrong version number for geckolib in the META-INF/mods.toml
you're currently using "[FORGE-1.16.2,)"
geckolib is currently 3.0.0-beta.2 according to META-INF/MANIFEST.MF (there's no mods.toml)

minecraft 1.16.3
forge 34.1.42
ars_nouveau-1.16.3-1.3.1.jar
forge-1.16.3-geckolib-3.0.0-beta.2.jar

![image](https://user-images.githubusercontent.com/313762/98057733-027dac80-1e11-11eb-882d-9caac4275e3a.png)

**Comment by baileyholl** [comment]
Geckolib 3.0 is not supported at this moment, and the TOML cannot be adjusted as geckolib 3.0 is not a mod, yet. You will need to use 2.0.
