### ISSUE TITLE
Conflict of receipts in Enchanting Apparatus

### ISSUE THREAD

**Issue by uhloin** [baileyholl/Ars-Nouveau#543]
Receipts for "Depth Strider I" and "Respiration I" are equal and as result "Respiration I" cannot be created.

May be not bug: receipt for Mending is forgotten. Looks like this is because mage robes have auto-mending. But at some stage of game non-robes armor is better. For example after Nether but before End the diamond armor with enchant mana regen/boost is better than robes of tier 2. But diamond armor needs a mending.

Feature request: belt of levitation is very like to elytras but firework rocket does not work with it. Could you add such function?

**Comment by uhloin** [comment]
Also Sharpness I and Sharpness II have the same receipt. May be I should use less resources than II?

**Comment by uhloin** [comment]
I could not find way for stable reproduction but sometimes with belt of levitation spiral particles stay infinite time while effect is worn out long time ago. Need to jump/sneak several times to remove particles. May be this is result of incompatibility with mod Gobber2 and item "Ring of Ascent". Ring of Ascent is also for levitation (start by right mouse button, stop by sneak button).

**Comment by baileyholl** [comment]
Fixed here: https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3814106

**Comment by uhloin** [comment]
Thank you for wonderful mod! :)
