### ISSUE TITLE
Conflict between levitation items in Ars-Noveau and Gobber2 mods

### ISSUE THREAD

**Issue by uhloin** [baileyholl/Ars-Nouveau#544]
I find way for stable reproduction it.
Need "Ring of Ascent" from Gobber2 in inventory slot 3.
Need "Ring of Acceleration" from Gobber2 in inventory slot 4.
Need "Belt of Levitation" from Ars-Nouveau in Belt-slot.
Press and release '3' to switch to Ring of Ascent, press right mouse button to levitate, release mouse button.
Press and release '4' to switch to Ring of Acceleration, look down, press and hold right mouse button until touch ground. Do not release right button.
Press 'Sneak' button, release it and only then release right mouse button.
Spiral particles appeared and flying infinite time until press 'Jump'+'Sneak'.
I do not know where problem is in Ars or in Gobber and will report the same issue to Gobber.

**Comment by uhloin** [comment]
P.S.
I used this version of Gobber:
https://www.curseforge.com/minecraft/mc-mods/gobber/files/3769229
And this version of Ars:
https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3800858

**Comment by baileyholl** [comment]
The belt of levitation alternates adding levitation and slowfall to the player based on their distance from the ground. If you combine that with other items, you will get some weird interactions. Doesn't really seem like there is anything to fix here.
