### ISSUE TITLE
1.18.2 You can steal parchment off the scribe's table while it writes and still get the glyph

### ISSUE THREAD

**Issue by border999** [baileyholl/Ars-Nouveau#557]

**Comment by dkmk100** [comment]
... I don't think parchment is used to make glyphs...

**Comment by border999** [comment]
Pardon me the. Is it simply that I have the mistaken belief that there needs to be blank parchment on the scribe's table in order to start the process of glyph creation?

**Comment by baileyholl** [comment]
Parchment is not required, it is just a visual effect.
