### ISSUE TITLE
(not bug) Counterintuitive key binds

### ISSUE THREAD

**Issue by uhloin** [baileyholl/Ars-Nouveau#558]
Hello, sir! Could you make key binds a bit more useable and intuitive? When book is in your right hand you can hold shield but cannot block because right mouse click is already used for spell cast. In the same time left key is useless and does not make sense (hit hard things by book?) 

I propose some changes for key binds or make them as option. May be it is already possible in some settings?
It would be better if main hand will always use left click and left hand use right one:

1. When book is in main hand and shield is in left hand then cast spell with left mouse button, block with shield with right mouse button.

2. (keep as now) When sword is in main hand and book is in left hand then hit by sword with left  mouse button, cast spell with right mouse button.

3. "Toggle Selection HUD" does not work if spell book is in left hand and sword is in main hand. Should work.

4. "Open book" should work even if book is not active slot. Book should be selected with priority:
- main hand
- left hand
- inventory slot nearest to active slot

**Comment by baileyholl** [comment]
Fixed next update
