### ISSUE TITLE
Bookwyrm potential issue

### ISSUE THREAD

**Issue by Frost1234567898** [baileyholl/Ars-Nouveau#559]
The Bookwyrm is unable to cast a projectile-fell-amplifyx4 spell on blazing archwood trees on my tree farm. I have plenty of source jars for it to draw from. The other wyrms are casting their spells fine just not the one with the fell spell. mod version is 1.16.5-1.24.19
![2022-06-07_21 49 45](https://user-images.githubusercontent.com/107092698/172526403-b473fa39-917d-4a66-8278-ac49fe0b36e9.png)

**Comment by baileyholl** [comment]
Hello,
This is likely due to chunk claims. You need to add Ars Nouveau and Minecraft as allys to your chunk claim, or enable Fake Players.

**Comment by scotty9090** [comment]
I'm having the exact same issue.  I have Fake Players enabled and in my test world where I'm trying this, I haven't claimed any chunks.  Grow and pickup work fine, but Fell refuses to work.
