### ISSUE TITLE
Whirlisprigs (and similar) can produce unbounded numbers of particles when not provided with source

### ISSUE THREAD

**Issue by bheisler** [baileyholl/Ars-Nouveau#565]
If a Whirlisprig or Drygmy is placed in a surroundings with appropriate gatherable blocks/animals but _not_ provided with a supply of source, it seems to generate more and more particles without limit. I've verified this by checking the source code - in the WhirlisprigTile, progress is allowed to increase without limit as long as the tile has no access to Source - the `progress` variable is only reset when retrieving Source succeeds. Particles are generated by `progress/20` (or `progress/2` for Drygmy's). If progress can't be reset due to a lack of Source, it can spawn enormous numbers of particles, which can cause other particles to disappear or client/server lag.

**Comment by baileyholl** [comment]
Hello,
I have added a fix for Whirlisprigs. I don't believe drygmys have the same uncapped particle behavior, as the progress is limited to the max amount.
Have you found otherwise?

**Comment by bheisler** [comment]
Ah, you're right, I checked Whirlisprigs and assumed Drygmy's worked the same way. Looking at their code they shouldn't have this problem.

**Comment by baileyholl** [comment]
Fixed here: https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3837696
