### ISSUE TITLE
Item multiplication with spell turret in 1.18.2

### ISSUE THREAD

**Issue by Raidobw2** [baileyholl/Ars-Nouveau#567]
The interaction between an Ars Nouveau Spell Turret and a Storage Drawer drawer allows for infinite duplication of any block. This includes duplicating a Better Crates crate with any item inside. When the turret is set to pull from a Storage Drawer, it does not use up an item when pulling and instead spawns a duplicate.

How to reproduce:
1. Place an Ars Nouveau Spell Turret, provide it with Source, and give it the spell Touch -> Place Block -> Break -> Extract.
2. Place a Storage Drawer next to the turret.
3. Add any block into the Storage Drawer.
4. Give the Spell Turret a redstone signal.

Versions:
Minecraft: `1.18.2`
Forge: `40.1.31`
Modpack: `FTB Plexiglass Mountain 1.0.2`
Ars Nouveau: `ars_nouveau-1.18.2-2.5.0.jar` (not the latest, latest is 2.5.1)
GeckoLib: `geckolib-1.18-forge-3.0.20.jar`
Better Crates: `BetterCrates-1.18.2-1.0.0.jar` https://www.curseforge.com/minecraft/mc-mods/better-crates
Storage Drawers: `StorageDrawers-1.18.2-10.2.1.jar` https://www.curseforge.com/minecraft/mc-mods/storage-drawers

Relayed from https://github.com/FTBTeam/FTB-Modpack-Issues/issues/971, thank you in advance!
P.S. Ars Nouveau v2.5.1 does not have a mention of this problem in its changelog, so I'm assuming it is still happening v2.5.1+

**Comment by baileyholl** [comment]
Fixed in latest version
