### ISSUE TITLE
Spell Book Crafting Mode 

### ISSUE THREAD

**Issue by Bronaya** [baileyholl/Ars-Nouveau#572]
Right Clicking with a new Spell doesn't open Crafting mode instead it shows the text "Invalid Spell". Pressing V shows and empty set of spell slots. 

Crafting glyphs with the scribes table uses up the crafting mode phase

**Comment by baileyholl** [comment]
'c' is the default book menu open. You may need to rebind it. Right click to open crafting does not exist anymore.
