### ISSUE TITLE
Crash upon hitting Play

### ISSUE THREAD

**Issue by skytheraiders** [baileyholl/Ars-Nouveau#58]
Everytime I hit the Play button to start the game, it instantly crashes with the "Exit Code: 0". 
Forge Version: 1.16.4-Forge-35.0.7
Ars Nouveau Version: 1.16.3-3.0.0-1
Patchouli Version: 1.16.2-47
Courios Version: 1.16.3-4.0.2.0
I can't get a crash report to produce.
I tried removing all the mods and slowly adding them in one at a time and Ars is the one that is causing the crash. Even with just the dependencies for the mod and not the mod itself allows the game to load. 
If you have any questions, please contact me.

**Comment by baileyholl** [comment]
Are you using Geckolib 2.0?

**Comment by skytheraiders** [comment]
I'm using Geckolib 3.0 because that is the only file that is on the
curseforge page for 1.16.4

**Comment by baileyholl** [comment]
Geckolib 3 is not supported, 1.16.3 version for 2.0 should work just fine.
