### ISSUE TITLE
Incompatibility with Rubidium (Sodium?)

### ISSUE THREAD

**Issue by uhloin** [baileyholl/Ars-Nouveau#582]
Do not know is it bug in Sodium, Rubidium (port of Sodium from Fabric to Forge) or Ars Nouveau.

If I use Forge + OptiFine + Ars Nouveau then mana level in Mana Jar is visible.

If I use Forge + Rubidium + Ars Nouveau then mana level in Mana Jar becomes invisible.

All components are updated to last versions for Minecraft 1.18.2. Forge is 40.1.51.

**Comment by baileyholl** [comment]
This is a bug in Rubidium.
