### ISSUE TITLE
[1.18 Suggestion] Duplicate Effects

### ISSUE THREAD

**Issue by GreenLEDPlugins** [baileyholl/Ars-Nouveau#587]
Currently the mod doesn't allow for compatibility with status effect mods such as [_Stylish Effects_](https://www.curseforge.com/minecraft/mc-mods/stylish-effects). I did some troubleshooting and think _Ars Nouveau_ re-enables the potion effect HUD? 

I was wondering if there could be a config option to turn on and off the potion effects HUD allowing greater compatibility.

[_Picture of Issue_](https://i.imgur.com/l9F7ta4.png)

**Comment by baileyholl** [comment]
This is now fixed in 1.19, but I will likely not spend the time to fix it on 1.18 as it is not a simple fix without the new forge support.
