### ISSUE TITLE
Wixie Cauldron Server Crash

### ISSUE THREAD

**Issue by WenXin20** [baileyholl/Ars-Nouveau#59]
`Minecraft v1.15.2`
`Forge v31.2.45`
`Ars Nouveau v1.3.0`

Filling a Wixie Cauldron using a Mana Bucket while on a server will crash the server.
[Crash Report](https://gist.github.com/WenXin20/177dc79387b2770f58dbabe2f3a143fe)

**Comment by baileyholl** [comment]
Unreleased feature
