### ISSUE TITLE
Wilden spawning in the overworld regardless of light level

### ISSUE THREAD

**Issue by atlgeek007** [baileyholl/Ars-Nouveau#597]
I have a fairly flat basse (9 chunks x 9 chunks) that I've entirely lit up, but with Ars Nouveau 2.6.1 (ATM7) Wilden Stalkers and Pack Hunters spawn here regardless of light level.

Rolling back to Ars 2.6.0 fixes this.

**Comment by baileyholl** [comment]
Hello,
Please try this version: https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3860816
