### ISSUE TITLE
Bookwyrm constantly drains source

### ISSUE THREAD

**Issue by fivecolorgoodstuff** [baileyholl/Ars-Nouveau#598]
For context, this is within the Medieval Minecraft modpack, but appears to be contained entirely within Ars Nouveau.

The bookwyrm appears to be constantly spamming its spell, even though documentation says that it will only cast spells when there is something that they will work on. I was attempting to make an automated source farm using sourceberries and a variety of other food items. The bookwyrm immediately started draining source even though nothing in its range was ready to harvest. I had it equipped with a projectile\harvest\fortunex4\item pickup spell. Additionally, the harvest spell doesn't appear to function with the sourceberry bush. This constant drain seems to make this method of source generation virtually impossible. I could not make the system become net positive despite several hours of tinkering and following several tutorials from experienced players.

**Comment by baileyholl** [comment]
The logic for when to cast only works for touch, as the bookwyrm knows what the spell with hit, it does not know with projectile. Switch it to touch.

Also, berries require interact, or you can use a Starbunc;e which will harvest them for you.
