### ISSUE TITLE
Magic Tree!

### ISSUE THREAD

**Issue by Divineaspect** [baileyholl/Ars-Nouveau#6]
Magic Tree

Logs:
Burning Wood for World Mana Generation
Magic Wood for Staffs and Wands as per #5

Vines:
with an Art Nouveau pattern which provide early game magical fiber for entry tier/pre enchanter-infuser thingie. This allows you to move the magic seeds back one level, and use the nether ingredients for them directly instead of splicing them into the fiber.

Fruit:
For Mana recovery, because presently that needs to be nerfed and/or shifted to being player based.

Magic Clay:
Their nature transmutes the soil under them into magical clay blocks when part of worldgen, or when fed world mana.

Sites of Power in Worldgen
This is also a good way to mark sites of power in worldgen for discussed magic locations.

**Comment by baileyholl** [comment]
added in 3.2
