### ISSUE TITLE
Incompatibility / Crash on Forge 41.0.64+

### ISSUE THREAD

**Issue by ibarnstormer** [baileyholl/Ars-Nouveau#603]
Due to numerous internal rewrites in this and succeeding versions of Forge, many mods that were written for versions 41.0.63- no longer work. As of this moment, all dependencies that this mod requires seem to have updated to address this so updating this mod to the newer versions should now be possible. 

Mod Version: 3.0.8 for 1.19

Relevant crash report: [crash-2022-07-10_13.01.22-fml.txt](https://github.com/baileyholl/Ars-Nouveau/files/9079518/crash-2022-07-10_13.01.22-fml.txt)

**Comment by baileyholl** [comment]
https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3877666
