### ISSUE TITLE
[1.16] Unable to extract potions from jars with flasks automatically

### ISSUE THREAD

**Issue by MuteTiefling** [baileyholl/Ars-Nouveau#611]
As discussed on [Discord](https://discord.com/channels/743298050222587978/771080006306365470/997313618444042312) fake players seem incapable of interacting with a potion jar using a flask unless that flask has previously been in a player's inventory. 

Forge: 36.2.34
Ars: ars_nouveau-1.16.5-1.25.1

Video: https://streamable.com/fxowg6

**Comment by baileyholl** [comment]
Try this version, unsure if it will work though https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3877734

**Comment by MuteTiefling** [comment]
Looks like this worked, thanks a million!
