### ISSUE TITLE
[1.16.5]After updating to 1.25.3, I can't start minecraft

### ISSUE THREAD

**Issue by DoctorSigma** [baileyholl/Ars-Nouveau#613]
After updating to 1.25.3, I can't start minecraft, it says an error. Only one crash log appeared, I don't know if it will help. When I return the average version 1.25.2, then I can enter minecraft. It says the failure occurred due to an incorrect Java Runtime configuration
![image](https://user-images.githubusercontent.com/93322905/179388638-1a7c0dff-ec36-41fc-9364-565489089244.png)
These settings in the launcher: -Xms3G -Xmx8G -XX:+UseConcMarkSweepGC 

Crashlog: https://pastebin.com/n5BLHHdr

**Comment by Alexthw46** [comment]
the log only mention an issue with the https://github.com/KosmX/emotes mod.
It doesn't also makes much sense to be a bug with 1.25.3 and not 1.25.2 since it only added ukr translations files

**Comment by DoctorSigma** [comment]
OK. I will write to the author of this mod. Well, even though the only change was that Ukrainian was added, the fact remains, it does not enter minecraft. Thank you.

**Comment by DoctorSigma** [comment]
I don't quite understand what else is being said here, but this is what the Emotes mod replied to me::
`Ars nouveau 1.25.3 (1.16.5) is missing required assets, so it cannot load...
The crash happened because something made a key hit with Emotecraft's keybinding before mod construction phase.`

`Well, the 1.25.3 is significantly I checked it and it is missing assets`

**Comment by Alexthw46** [comment]
Due to timezones it won't be as fast as their response, but we will look into it then. Maybe something went wrong while building the update.

**Comment by DoctorSigma** [comment]
I also want to inform you that some configs, for example from the ftbteam ftbauests mod, are overwritten or damaged, the default values are simply restored. After I try to enable minecraft with updated mod. I am writing this because it may help in identifying the problem

**Comment by Phweeeee** [comment]
My version just says Ars Nouveau 1.25.3 is not a valid mod file. It also seems to be very broken when the mod was built. as 1.25.3 is only 1.71 MB over 1.25.2, which was 4.39 MB. This suggests either the mod builder broke midway, or the jar was built too soon. I personally doubt adding a Ukrainian translation deleted almost 3 MB of the mod.

**Comment by baileyholl** [comment]
Try here: https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3879813
