### ISSUE TITLE
[1.19] Compatibility issue with Carry On

### ISSUE THREAD

**Issue by Silivek** [baileyholl/Ars-Nouveau#615]
Using the Sinister Switch spell and then carrying your clone causes the game of anyone who is rendering your player to crash. I don't know if it is an issue from this mod or Carry On, but I thought I would put it here anyway.
Ars Nouveau Version: 1.19.0-3.0.6
Forge Version: 41.0.63
Crash Log: https://pastebin.com/GcDrA37h

**Comment by baileyholl** [comment]
This is fixed in the latest version of Geckolib
