### ISSUE TITLE
(Suggestion) Summon strider

### ISSUE THREAD

**Issue by YenedeyEy** [baileyholl/Ars-Nouveau#619]
I had an idea which is to make a new tier 2/3 summon spell that as the one that summon a saddled horse this one will summon a saddled strider. You maybe could also make it so you can control this entity without a warped fungus on a stick. I would also add particles so when the strider is about to dissapear it tells you so you don't fall into lava a lot <3

Just a little idea I had, I hope you like it

**Comment by Alexthw46** [comment]
Hi, a bit late response but I added that feature around a month ago in Ars Elemental as a variation of summon steed while wearing a fire focus (1.18+). Just to let you and anyone else stumbling here know.
