### ISSUE TITLE
Spells can move and break unbreakable blocks such as bedrock

### ISSUE THREAD

**Issue by vtheskeleton** [baileyholl/Ars-Nouveau#620]
Using this spell
![image](https://user-images.githubusercontent.com/47392011/179731854-5187a61e-e3d0-4e17-9b6d-102856b609fc.png)

I was able to pull bedrock up, and by placing a torch under where it was falling it would break on impact

![image](https://user-images.githubusercontent.com/47392011/179731940-b11cc26a-f1de-4689-aaa0-803cfccc4287.png)

**Comment by vtheskeleton** [comment]
#88 Describes the same issue, but it does not appear fixed in version 2.6.5 on 1.18.2

**Comment by baileyholl** [comment]
Fixed here https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3888205
