### ISSUE TITLE
Rubidium, smoke and conjured mageblock

### ISSUE THREAD

**Issue by uhloin** [baileyholl/Ars-Nouveau#627]
I use minecraft 1.18.2 + forge + rubidium + oculus + this shaders (with default settings):
https://www.curseforge.com/minecraft/customization/makeup-ultra-fast-shader/
If place wall of "conjured mageblocks" and set campfire before wall and look through smoke puff to wall then smoke puff becomes more and more transparent but mageblocks also becomes invisible and I can see territory behind wall.

**Comment by baileyholl** [comment]
Rubidium changes core parts of rendering in the game, mods cannot typically accommodate these changes.
