### ISSUE TITLE
Ars causes a second effect hud element to be displayed while Stylish effects is installed.

### ISSUE THREAD

**Issue by Warhand** [baileyholl/Ars-Nouveau#632]
Ars nouveau version: 2.7.1
Stylish effects version: 3.1.0
Minecraft version: 1.18.2
Forge version: 40.1.68

When running Ars nouveau alongside Stylish effects, Ars nouveau causes a second vanilla hud element for effects to be displayed, when Stylish effects is supposed to overwrite and replace the vanilla effect hud element.

The image provided includes a few other mods, but I have confirmed that the issue still persists even when running a profile that only contains stylish effects, ars nouveau, and their respective dependencies.
![image](https://user-images.githubusercontent.com/29134223/180854273-7af12175-8733-4d0c-8f5b-3d62d94d8188.png)

The issue doesn't appear in the Ars nouveau versions in between and including version 2.3.2 and 2.4.2, and only starts appearing in 2.5.0, so the issue is caused by something included/changed in that version.

**Comment by baileyholl** [comment]
Should be fixed here: https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3943669
