### ISSUE TITLE
Stripped Archwood "randomly" showing their colored dots

### ISSUE THREAD

**Issue by CrustyPineapple** [baileyholl/Ars-Nouveau#634]
The stripped Archwood of the four different trees (blazing (red), cascading (blue), vexing (purple), and Flourishing (green)). When stripped, have a chance to either show their colored dots or not. I've tested this out, and it does not depend on how the log is placed (upright or sideways). It all depends on the world cord of the Minecraft world. For example, x=100 y=50 z=100 will show or not show the colored bits no matter how the log was placed. Not exactly sure if this is meant to happen but a way around it is by placing the stripped logs into a 2x2 to get the logs to show all side of colored bit and will show no matter the world cord.

EX: https://imgur.com/dvmcwY5
Mods list: https://imgur.com/teNHGQw

**Comment by baileyholl** [comment]
This is intended, they use minecrafts variant system which is position based.
