### ISSUE TITLE
Feature Request: Data Driven Enchanting Apparatus Recipes

### ISSUE THREAD

**Issue by MuteTiefling** [baileyholl/Ars-Nouveau#64]
I was hoping to hook into this to make some custom recipes, but that doesn't appear to be possible at this time. 

Would you consider making these recipes data driven so mods like KubeJS can hook into them to add or remove recipes?

**Comment by Crabby-Gamer** [comment]
I also was intending to use the enchanting apparatus for my modpack, as well as the glyph press for custom recipes.

**Comment by MuteTiefling** [comment]
I see this got into the latest release :D Very excited. I am having a bit of trouble with it, however. I can't seem to get it to make an enchanted book. How would one supply the NBT data necessary for this in the datapack?

**Comment by baileyholl** [comment]
Currently NBT is not supported, just items. I will look into NBT support in the future. Closing this for now.
