### ISSUE TITLE
[Bug]: Ars Nouveau Exchange spell, MythicBotany Mjollnir gets used as a block to exchange which removes data from it.

### ISSUE THREAD

**Issue by TheonlyTazz** [baileyholl/Ars-Nouveau#651]
### Modpack

FTB Presents Direwolf 20 1.18

### Modpack version

1.8.0

### Describe the bug

Ars exchange spell takes mjollnir as a block (probably because you can place it) and tries block swap, fails to do so removing enchantments from mjollnir and probably any other data while placing it in off-hand slot.

### Steps to reproduce

Above + I made a vid https://www.youtube.com/watch?v=sr6jhNtoh-w
If you want to test it yourself, remember you need ring of thor or absorbtion effect to have hammer in inventory.

### Expected behaviour

Spell ignoring Mjollnir or Mjollnir not allowing to be used that way.

### Additional information

This Issue has been posted on the FTB Modpack Issuetracker for Direwolf20 1.18.2
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1220

This is a Mod Issue regarding Ars Nouveau, thus forwarding it and requesting a fix

**Comment by baileyholl** [comment]
Fixed next version
