### ISSUE TITLE
Ars Nouveau conflict with Biomes O'Plenty

### ISSUE THREAD

**Issue by ncottrill** [baileyholl/Ars-Nouveau#653]
Minecraft 1.19.1
BiomesOPlenty-1.19.1-17.1.0.144.jar
ars_nouveau-1.19.1-3.2.5.jar
curios-forge-1.19.1-5.1.0.5.jar
geckolib-forge-1.19-3.1.14.jar
TerraBlender-forge-1.19.1-2.0.0.122.jar

During chunk rendering, Ars and BOP have a cycle that causes a crash. 
Crash report here https://pastebin.com/mBHv7ZbF

**Comment by baileyholl** [comment]
This should be fixed here, just updated 20 minutes ago :) https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3921458

**Comment by ncottrill** [comment]
Fixed! Thank you :)
