### ISSUE TITLE
[1.18.2] Ars Dynamic Lights only work when Rubidium Dynamic Lights are disabled in the settings

### ISSUE THREAD

**Issue by WFPhantom** [baileyholl/Ars-Nouveau#654]
^ Title, Rubidium Dynamic Lights work fine but ars light spells dont. When i go to settings and disable Rubidium Dyn Lights, ars spells work fine.

**Comment by baileyholl** [comment]
Rubidium Dynamic lights is unsupported.

Ars Nouveau has full Dynamic Light supports in the config, you can add any item or entity you need, Rubidium Dynamic lights is not needed. They are the exact same implementation of the lighting.
