### ISSUE TITLE
Game crashes when using Ars with Roughly Enough items

### ISSUE THREAD

**Issue by Greg-Boggs** [baileyholl/Ars-Nouveau#657]
I'm using Ars-Nouveau 3.2.6 and Roughly Enough Items 9.1.518 1.19. Every time I close the worn notebook, the game crashes. Cross posting because I can't tell which mod causes the crash:

https://github.com/shedaniel/RoughlyEnoughItems/issues/1060

**Comment by baileyholl** [comment]
This looks like an issue with REI or JEI. Does your server have JEI installed? Not sure how REI works, but something is missing on that end.
