### ISSUE TITLE
Imbuement and Enchantment floating items not rendering (most likely rubidium or starlight)

### ISSUE THREAD

**Issue by Shadowex3** [baileyholl/Ars-Nouveau#677]
Items in the imbuement chamber and on arcane pedestals are invisible, and also don't get listed in any hud element when targeting the block as near as I can tell which makes it a bit tricky to debug sometimes. Interestingly the central item in the enchanting apparatus seems to work ~90% of the time, and floaty items for the scribe's table work just fine.

99% I would bet this is Rubidium, Flywheel, or Starlight.

**Comment by baileyholl** [comment]
Likely Starlight, Rubidium and Flywheel are commonly run and users have not had issues with those in particular. Likely something they do to Item Entities.
