### ISSUE TITLE
[Suggestion] Use action bar for messages

### ISSUE THREAD

**Issue by ChloeDawn** [baileyholl/Ars-Nouveau#679]
Context-sensitive messages such as dominion wand interactions and mana emptiness can often spam the chat, it would be nice to see them moved to the action bar. I am more than happy to make a pull request to implement this if you are interested!

**Comment by baileyholl** [comment]
The mana message will not send duplicate messages if the last message was the same, there is a built in method for non-spamming messages. The dominion wand probably does not use it though.

Id accept a PR for a config/toggle option, but id rather keep the chat version as it is
