### ISSUE TITLE
Trickery & Illusions update

### ISSUE THREAD

**Issue by baileyholl** [baileyholl/Ars-Nouveau#680]
Invisible Blocks
Disguised blocks with ability to light them
Magic sense to reveal the above
Interdimensional warp scrolls/portals
Ritual to cancel teleports
Ritual to cancel spell casting
Greater invisiblity, hiding armor

**Comment by Sarenor** [comment]
Visible blocks that don't have collision (Think walk through walls, fall through floors)

**Comment by shoverno2** [comment]
If decoy could have nickname
Then it would be much more funny to trick other players

(But usually it works with less aware players
Even without name tag
And that's hilarious to watch)

**Comment by shoverno2** [comment]
disguise glyph

Because taking model of other mob or player would be really fun
+special mob invisibility, maybe

Like wearing matching mob head...

**Comment by shoverno2** [comment]
Name tag hide thread..?

Well, it isn't useful without friends or other players
So there's no big deal in set minimum slot level

A little trickery
In case of decoy not having their name tags...

**Comment by shoverno2** [comment]
Chameleon magic blocks...

If not augmented magic block glyph
Then completely new glyph
That could work just like simple magic block
Except one moment...
It could take texture from spell touched block

even air would work 
Transparent textures; yep, invisible wall

But, uh, yes
This one sounds more like cosmetic stuff
