### ISSUE TITLE
Suggestion: Automation of Glyphs

### ISSUE THREAD

**Issue by BooBeerb** [baileyholl/Ars-Nouveau#683]
I understand that there would be very little reasons to do this, but maybe if a recipe could stay inside the Scribe's table so you could infinitely produce one glyph. This is for ATM7, where the Wither's Compass requires a glyph of Wither. Yes, I understand that normally in the mod massproducing glyphs is nonsensical but pleeeassseeee, Bailey.

**Comment by baileyholl** [comment]
Glyph automation wont be coming back since it isnt necessary in the base mod, sorry.
