### ISSUE TITLE
[1.18.2][Bug]: Can Dupe Minecolony Field block with Ars Exchange Spell

### ISSUE THREAD

**Issue by Saereth** [baileyholl/Ars-Nouveau#685]
Place the field(scarecrow).
Cast exchange on the bottom block of the Scarecrow. Bottom block is replaced with whatever block you had ready.
The top of the scarecrow is still there but not visible, you can see the selection box, though.
Mine that top selection box to receive a 2nd Scarecrow.

Tried with a couple other 2-high items from vanilla, it doesn't work on them.

**Comment by Saereth** [comment]
https://github.com/ldtteam/minecolonies/issues/8630

**Comment by baileyholl** [comment]
Fixed next version
