### ISSUE TITLE
Summoned Wolf Texture with texture packs

### ISSUE THREAD

**Issue by Daihok41** [baileyholl/Ars-Nouveau#687]
Any way to use textures packs with Ars? any texture pack i use the texture for summoned wolf all messed up? Any work around for this when using texture packs?

**Comment by baileyholl** [comment]
Hello,
I am not sure that you will be able to replace the summoned wolves, as they use the minecraft wolf renderer and texture. Other mobs use Geckolib models, which can be replaced, but you would need to use the plugin, load the model, and add a new texture that fits appropriately.
