### ISSUE TITLE
[1.18.2] Using Ars Nouveau projectile->break->extract->pickup on some blocks crashes the server.

### ISSUE THREAD

**Issue by Saereth** [baileyholl/Ars-Nouveau#688]
Steps to reproduce:
For this example we used the experience obelisk from the Experience Obelisk mod. 
Place the obelisk, cast the spell on it, server crashes.

Here's is the server log
https://pste.me/v1/paste/39NEu3zRxBk/raw

**Comment by baileyholl** [comment]
Fixed next version
