### ISSUE TITLE
Starbuckle causing crashes when picked up with Carry On [1.18.2]

### ISSUE THREAD

**Issue by jaredniegas** [baileyholl/Ars-Nouveau#690]
Is there a way to get this fixed? Accidentally got picked up and now the world can't be opened.

[crash-2022-09-11_19.43.20-client.txt](https://github.com/baileyholl/Ars-Nouveau/files/9542409/crash-2022-09-11_19.43.20-client.txt)

**Comment by jaredniegas** [comment]
[crash-2022-09-11_19.46.19-client.txt](https://github.com/baileyholl/Ars-Nouveau/files/9542411/crash-2022-09-11_19.46.19-client.txt)

**Comment by baileyholl** [comment]
Updating to the latest version of Geckolib should fix that.

**Comment by baileyholl** [comment]
please use this version: https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3983779

**Comment by jaredniegas** [comment]
Thank you! Such a fast fix, very appreciated!
