### ISSUE TITLE
[request] [ui] Spellbooks too large, add option to make item scale smaller

### ISSUE THREAD

**Issue by FrederickEngelhardt** [baileyholl/Ars-Nouveau#691]
Hello, thank you for creating this mod!

## Question / Request
Is there a way to make the spellbook smaller? And if not can this be added in an upcoming version?

Possible alternatives / other ways to access the book without it equiped:
1. Make the spellbook spells accessible when the book is in the inventory
2. Make the spellbook part of curios and add the book to one of the slots (like a book belt option)

See the attached photo, the spell book takes up about 1/4 of the screen even with ultrawide. Having a downscaling option would be nice and similar to the [lower-shield texture pack](https://www.planetminecraft.com/texture-pack/lower-shield-4492282/)

Currently I'm using this client side mod to hide the offhand when the spell book is in it. https://www.curseforge.com/minecraft/mc-mods/hide-hands. Also curious if anyone else has recommendations for ultrawide and hand held items resizing libs.

![ars-nouveau-book](https://user-images.githubusercontent.com/31741411/189554044-aa29e10a-2fbd-4095-b2a7-347b06d11823.png)

**Comment by baileyholl** [comment]
These can be modified using a resource pack and editing the item model, configs cannot change these.
