### ISSUE TITLE
someone "ported" ars magica ....

### ISSUE THREAD

**Issue by ShadowOfDeath98** [baileyholl/Ars-Nouveau#694]
https://github.com/MinecraftschurliMods
/
[Ars-Magica-Legacy](https://github.com/MinecraftschurliMods/Ars-Magica-Legacy)

which based of the images looks like the 1.17 version of this mod just thought you should know.
items have the same  name and are the same textures as the older version of this mod.

**Comment by baileyholl** [comment]
That is not my mod, that is mithions, and they are aware.
