### ISSUE TITLE
[1.16.5]Incompatibility with SpongeForge

### ISSUE THREAD

**Issue by 1keponchem** [baileyholl/Ars-Nouveau#699]
The 1.16.5 server with SpongeForge and Ars Nouveau crashes _when generating a new world_.
This crash won't happen otherwise, for example running the same mods on server with an already existing world.
Crash log: [latest (1).log](https://github.com/baileyholl/Ars-Nouveau/files/9575080/latest.1.log)
Installed Mods:
- Patchouli-1.16.4-53.3.jar
- geckolib-forge-1.16.5-3.0.88.jar
- ars_nouveau-1.16.5-1.25.7.jar
- curios-forge-1.16.5-4.0.8.2.jar
- spongeforge-1.16.5-36.2.5-8.1.0-RC1182-universal.jar

**Comment by baileyholl** [comment]
Modified forge servers are unpredictable, and cannot be supported unfortunately.
