### ISSUE TITLE
1.15.2 Its impossible to craft glyphs due to broken recipes

### ISSUE THREAD

**Issue by Hiranus** [baileyholl/Ars-Nouveau#70]
It looks like this for Touch, Self and Projectile. Please fix it as those glyphs are kind of essential.

https://pastebin.com/bdAdwzUR 

![image](https://user-images.githubusercontent.com/6943031/99265895-7f9e1e00-2822-11eb-89eb-a4a16f854bf7.png)

**Comment by baileyholl** [comment]
You start with these in the book already.
