### ISSUE TITLE
Enigmatica configswapper error

### ISSUE THREAD

**Issue by DerpyManeuver** [baileyholl/Ars-Nouveau#709]
Hi!
My game doesn't launch up whenever I try to launch it up, having the error configswapper not having not enough data available
Here is the crash report.
I hope someone can help me with this
[crash-2022-09-19_21.16.38-fml.txt](https://github.com/baileyholl/Ars-Nouveau/files/9599796/crash-2022-09-19_21.16.38-fml.txt)

**Comment by baileyholl** [comment]
Not sure why you are posting this here, but you can usually fix config errors by wiping the entire config folder. You will need to redownload it from your pack though.
