### ISSUE TITLE
Geckolib 3.0 support coming?

### ISSUE THREAD

**Issue by Seth0067** [baileyholl/Ars-Nouveau#71]
Hi Bailey - would really love to use this mod in a new pack, but I'm using other mods that require the latest geckolib version. 

I did note in your closed issues that you do not support the latest version of geckolib, but do you have plans to update to include this support? If it just will take some time, that's fine, it would be great to know for planning purposes.

Thanks for your modding efforts!

**Comment by baileyholl** [comment]
Yes, sometime this week, version 1.6.0 will support Geckolib 3.
