### ISSUE TITLE
Enchanting apparatus bug

### ISSUE THREAD

**Issue by rowanistic** [baileyholl/Ars-Nouveau#711]
When i use the enchanting apparatus, it says 'Recipe found, pedestals must be within 3 blocks' when i have the pedestals next to the apparatus. Even with no items in any of the pedestals it still says this, and im unable to craft with it because of this.

**Comment by baileyholl** [comment]
Double check that you are using the correct block. If you are trying to make an Imbuement Chamber recipe, it wont work with teh apparatus.

**Comment by rowanistic** [comment]
> Double check that you are using the correct block. If you are trying to make an Imbuement Chamber recipe, it wont work with teh apparatus.

i was trying to make an enchanters bow, so i was definitely using the right magic machine.
