### ISSUE TITLE
[Suggestion] A way to disable mechanics in config.

### ISSUE THREAD

**Issue by TrueBlueFlare** [baileyholl/Ars-Nouveau#712]
So, I've been making a modpack that includes Ars Nouveau and would like a method in configs to disable specific mechanics, namely warp portals as a way to create permanent portals everywhere makes other travel systems completely redundant, and I would like a way to disable warp portals without having to remove the recipes for warp scrolls, as they have other uses, or arcane bricks, as they make for good decorative blocks.

**Comment by baileyholl** [comment]
For portals, you can disable them by removing the blocks from the an_decorative block tag. That is used by portals for valid blocks.
