### ISSUE TITLE
Potion Flasks cannot be filled with Enigmatic Legacy potions

### ISSUE THREAD

**Issue by LTCatt** [baileyholl/Ars-Nouveau#718]
![image](https://user-images.githubusercontent.com/40348278/193228612-76e6195e-8eb5-4a33-8f4c-477eb8b35a72.png)
![image](https://user-images.githubusercontent.com/40348278/193228700-96c031fd-b1c5-4e70-a58d-5019650833cc.png)

It is not minecraft:potion  :(
Enigmatic Legacy: https://www.curseforge.com/minecraft/mc-mods/enigmatic-legacy

**Comment by baileyholl** [comment]
Is this for 1.18 or 1.19?

**Comment by LTCatt** [comment]
urr it's under 1.16.5

**Comment by baileyholl** [comment]
1.16.5 is no longer supported, sorry
