### ISSUE TITLE
Nether Iron Ore not dropping items with "Break"

### ISSUE THREAD

**Issue by TommyG-87** [baileyholl/Ars-Nouveau#725]
When using Break on Nether iron ore from the Nourished Nether mod it drops nothing. Tested with and without Extract and various levels of Amplify. Mining with a pickaxe works as expected and drops iron nuggets.

Minecraft 1.18.2
Forge 40.1.69
Ars Nouveau 2.7.8
Nourished Nether v15
Modpack Medieval MC 14.5

**Comment by baileyholl** [comment]
Fixed next version
