### ISSUE TITLE
Incompartilibity with recent geckolib

### ISSUE THREAD

**Issue by uhloin** [baileyholl/Ars-Nouveau#726]
Versions **ars_nouveau-1.19.2-3.4.2.jar** and **geckolib-forge-1.19-3.1.24.jar** are incompartible. Some textures disappears for example magic blocks and archmage book.

**Comment by uhloin** [comment]
Version **geckolib-forge-1.19-3.1.25.jar** does not lost textures but loses color of coljured mage blocks: they are RGB 1-120-1 (grass-green) but looks like gray.

**Comment by jordan-moore** [comment]
Also experiencing this with geckolib on 1.18 `geckolib-forge-1.18-3.0.45` and `geckolib-forge-1.18-3.0.41`

**Comment by baileyholl** [comment]
This has been fixed in geckolib 3.0.45, are you sure you are still experiencing this issue? Should be fixed now.

**Comment by uhloin** [comment]
Yes, just fixed in geckolib-forge-1.19-3.1.27.jar
