### ISSUE TITLE
"Fixes crash" creates crash

### ISSUE THREAD

**Issue by uhloin** [baileyholl/Ars-Nouveau#728]
Version ars_nouveau-1.19.2-3.4.3.jar is introduced as "fixes crush with patchouli" but in fact there was not such crush in previous version but it was created in this version:

[crash-2022-10-19_11.24.33-client.txt](https://github.com/baileyholl/Ars-Nouveau/files/9817878/crash-2022-10-19_11.24.33-client.txt)

**Comment by baileyholl** [comment]
You need to update both patchouli and AN to the latest.

**Comment by uhloin** [comment]
Thank you! I forgot to subscribe Patchouli updates and thought have last version.
