### ISSUE TITLE
Ring of Greater Disount broken

### ISSUE THREAD

**Issue by GamerXD8991** [baileyholl/Ars-Nouveau#73]
Ars Version 1.5.3 and 1.5.2 (maybe older as well)
Forge Version: 35.0.18
MC: 1.16.4
Curios API: 4.0.2.1
having the Ring of Greater Disount in the inventory or Curios slot doesn't affect the mana cost.

**Comment by DerringersMods** [comment]
Greater Discount is worth the cost of _a single Amplify_. Good for spamming cheap spells - spraying lights all over a ravine, picking single ore blocks out of a wall at a distance - but don't expect it to do much for spells that have multiple Amplify or Fortune glyphs.
