### ISSUE TITLE
Minecraft server crash in an attempt to use any spell.

### ISSUE THREAD

**Issue by nghiaconga134** [baileyholl/Ars-Nouveau#730]
Minecraft server version 1.19.1, forge 42.0.9
Ars Noveau 3.4.3
Curious 1.19.2-5.1.1.0
Gecklib 1.19-3.1.27
Patchouli 1.19-75
Crash log : https://mclo.gs/jYltSpS

**Comment by baileyholl** [comment]
You need a 1.19.2 version of minecraft and forge.
