### ISSUE TITLE
Crash.

### ISSUE THREAD

**Issue by MagmaBro123** [baileyholl/Ars-Nouveau#732]
Title. Report has this mod written all over it, so I'm unsure if other mods are causing this issue.

Forge 36.2.39, AN 1.25.7, and MC 1.16.5.

https://pastebin.com/9u14DPNf

**Comment by DoctorSigma** [comment]
A similar crash is due to GeckoLib version 3.0.99. When there was version 3.0.65, there was no crash.

latest.log: https://gist.github.com/cf263799fbaefce9c4f294ddfeaefb72.git
crash log: https://pastebin.com/P30DMr7v

**Comment by MagmaBro123** [comment]
> A similar crash is due to GeckoLib version 3.0.99. When there was version 3.0.65, there was no crash.
> 
> latest.log: https://gist.github.com/cf263799fbaefce9c4f294ddfeaefb72.git crash log: https://pastebin.com/P30DMr7v

.100 now exists. Not sure if that fixes this issue either.

**Comment by MagmaBro123** [comment]
> A similar crash is due to GeckoLib version 3.0.99. When there was version 3.0.65, there was no crash.
> 
> latest.log: https://gist.github.com/cf263799fbaefce9c4f294ddfeaefb72.git crash log: https://pastebin.com/P30DMr7v

.100 is out, and issue still persists. @baileyholl Please fix this.

**Comment by baileyholl** [comment]
Update to the latest version.

**Comment by MagmaBro123** [comment]
> Update to the latest version.

I use 1.16.5. Yes, old-ish, but most modpacks still use it.
