### ISSUE TITLE
This spell crashes the game / server

### ISSUE THREAD

**Issue by KofiFS** [baileyholl/Ars-Nouveau#734]
[crash-2022-10-28_12.39.29-server.txt](https://github.com/baileyholl/Ars-Nouveau/files/9890329/crash-2022-10-28_12.39.29-server.txt)
![Desktop_Screenshot_2022 10 28_-_12 50 23 22](https://user-images.githubusercontent.com/7231074/198690957-20dfe23b-a1bc-46b2-9040-903134166cad.png)

**Comment by KofiFS** [comment]
It happens when it's used twice quickly.

**Comment by Alexthw46** [comment]
https://www.curseforge.com/minecraft/mc-mods/ars-elemental/files
Update Ars Elemental
