### ISSUE TITLE
1.25.8 for 1.16.5 reports incompatible with GeckoLib versions over 3.0.96

### ISSUE THREAD

**Issue by peetey897** [baileyholl/Ars-Nouveau#735]
Any attempts to launch MC with Ars Nouveau 1.25.8 with GeckoLib versions over 3.0.96 results in an immediate error that Ars Nouveau only supports GeckoLib versions up to 3.0.96. Ars Nouveau 1.25.7 launches with GeckoLib versions over 3.0.96 without issue.

**Comment by Alexthw46** [comment]
#733

**Comment by baileyholl** [comment]
https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/4087794
