### ISSUE TITLE
Ars Update to be compatible with Gecko?

### ISSUE THREAD

**Issue by Orangejewce92** [baileyholl/Ars-Nouveau#739]
I have other mods in my 1.16.5 packs that can't update do to having to leave GeckoLib at .96 
Will Ars be updated to fix this ? or is it not going to be fixed.
thank you. 
( i see the other tickets kinda mentioning the same thing but i just kinda wanted a cut and dry answer like yes or no)

**Comment by TheeMrCheeky** [comment]
Yeah, I need Ars compatible with latest geckoLib. Some mods I run require latest but ars requires older >_<

**Comment by Alexthw46** [comment]
Apparently the things that broke post .96 were readded recently. Try downgrading to 1.25.7 and use it with gecko 103 and let us know if it works without crashes

**Comment by Orangejewce92** [comment]
So if I'm understanding correctly, I can down grade my Ars , so that I can update GeckLib?

**Comment by TheeMrCheeky** [comment]
@Orangejewce92 correct

**Comment by Orangejewce92** [comment]
@TheeMrCheeky so it will start up but the game crashes.

**Comment by Orangejewce92** [comment]
[crash-2022-11-14_18.20.30-client.txt](https://github.com/baileyholl/Ars-Nouveau/files/10007837/crash-2022-11-14_18.20.30-client.txt)

**Comment by Orangejewce92** [comment]
[crash-2022-11-14_18.34.09-client.txt](https://github.com/baileyholl/Ars-Nouveau/files/10007844/crash-2022-11-14_18.34.09-client.txt)

**Comment by baileyholl** [comment]
https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/4087794
