### ISSUE TITLE
[1.19.2] Bookwyrm unobtainable?

### ISSUE THREAD

**Issue by Ashendale** [baileyholl/Ars-Nouveau#744]
MC version 1.19.2
Ars Nouveau version 3.4.6

Apologies if this isn't the right place to ask, but I cannot find anything via Google, Reddit, or YouTube. The recipe isn't showing on the book using the search function.

![image](https://user-images.githubusercontent.com/14125391/200864794-4676a06c-5416-42fa-a0d3-d0bfb7259f3b.png)

I cannot craft the Bookwyrm charm (videos I found suggest using the Enchanting Apparatus with 4 iron, 4 source gems and a book on the Apparatus; I also tried an egg instead of the book as an older video suggested).
The recipe for the charm is not available from JEI.

Searching for available recipes requiring the Apparatus (while on a creative world) does not show the recipe for the charm either. All other charms have their recipes (except the Amethyst golem, as it should).

![image](https://user-images.githubusercontent.com/14125391/200868208-113b3c71-54f3-4f90-a162-6948c2600e46.png)

Above issues and images are from a modpack made by myself. As I wrote this, I realized that there could be conflicts, so I fired up a creative world on a new instance using only Ars, Curios, Patchouli, and JEI. The issues remain.

If this is an issue (and not just me being dumb) and there is any other information I might add to assist, please let me know.

**Comment by Alexthw46** [comment]
The bookwyrm is disabled in 1.19 until #723 is finished. Their old job had become basically useless with rune/turrets improvements, so it's going to be relocated as a storage manager.

**Comment by Ashendale** [comment]
Thanks, I missed that. I wanted the little bugger for his spell discount modifier.
