### ISSUE TITLE
Cannot use Ender Chest (vanilla) with Starbuncle

### ISSUE THREAD

**Issue by Ashendale** [baileyholl/Ars-Nouveau#748]
MC version 1.19.2
Mod version 3.4.6

As per title. I can shift+right click with Dominion Wand on chest, and I get the "Position set." notification. After, when right-clicking on Starbuncle, I get no information and the overlay does not change (storing items at 0 locations, etc.).
The opposite is also true. I cannot set a Starbuncle to deposit on Ender Chests.

I have tried this on my survival and creative worlds. I have tried this with an empty Ender Chest, and one with items in it. The results are the same.

**Comment by Alexthw46** [comment]
Vanilla ender chests can only be used by players since it's vanilla design, every player have a different content. Not really a bug

**Comment by Ashendale** [comment]
My bad. Thanks for reply.
