### ISSUE TITLE
Performance issue with Magic Block

### ISSUE THREAD

**Issue by uhloin** [baileyholl/Ars-Nouveau#750]
I encountered a big performance issue. I have colony (minecolonies mod) near my home. When I look toward the colony I have significant FPS drop (usually more than twice) and when I look in reverse direction FPS is restored. This issue ocurs even if I in closed space and looking to solid wall and see only one block of stone. I thought the problem is Minecolonies but after check I found it is Ars Nouveau. When I remove it FPS is good in any direction. Only block of AN I use in colony is persistent Magic Block. I used may be 1000 of such blocks to align ground and walls. I am not sure absolutely about they are issue because it will take time to replace them and some of them may be already covered by grass and stone.

Here results of profiler.
Looking into wall with direction of view to MineColony center: 22-23 FPS
https://spark.lucko.me/xce6pFuSvI
Looking to opposite direction: 50-60 FPS
https://spark.lucko.me/L8AD4cqsU0

**Comment by Alexthw46** [comment]
Mageblocks appears to tank performance since the geckolib renderer is not made to be used on such a large scale. #746 moves the rendering to a vanilla one similar to grass color, also comes with latest geckolib that have few performance upgrades.
