### ISSUE TITLE
Containment Jar bugs

### ISSUE THREAD

**Issue by uhloin** [baileyholl/Ars-Nouveau#752]
If after successful ritual of containment broke containment jar and other empty jar is in range then jar moved inside the jar.

After dispel such jar-in-jar it disappeared with monster inside.

Also boat may be contaned (may be minecart too).

On dispel Jar entity may appear in the wall above the jar and die.

Sometimes entity contained not inside the jar but under jar flipped.

**Comment by Alexthw46** [comment]
About the jar-in-jar and boats etc, it's because they are whitelisted by default. You can use a datapack to overwrite the tag (replace to true) to block those interactions
https://github.com/baileyholl/Ars-Nouveau/blob/1.19.x/src/main/resources/data/ars_nouveau/tags/entity_types/jar_whitelist.json

**Comment by uhloin** [comment]
May be it should be opposite = not whitelisted by default and need datapack to whitelisted?

**Comment by Alexthw46** [comment]
Having items whitelisted is a choice made because you use the jars as item displays this way. I'd honestly only add an additional config defaulted to block only the jar-in-jar effect since it can be pretty annoying, but i'm not the decision maker :P
