### ISSUE TITLE
[Bug]: Breaking Exp Obelisk with Ars spell destroys the obelisk and all exp inside

### ISSUE THREAD

**Issue by TheonlyTazz** [baileyholl/Ars-Nouveau#756]
### Modpack

FTB Inferno

### Modpack version

1.2.1

### Mod versions

Ars Nouveau: ars_nouveau-1.18.2-2.8.0.jar
Experience Obelisk: experienceobelisk-v1.3.6-1.18.2.jar
Forge: 40.1.80

### Describe the bug

When I break the Experience Obelisk with break spell from ars, the block gets destroyed and all exp inside too. 

### Steps to reproduce

1. Create Ars spell in a book using touch + break + extract
2. Use the spell to break the experience obelisk (pressing shift)
3. Watch it get destroyed with all experience inside 

### Expected behaviour

Obelisk gets broken and I can pick it up to place somewhere else.

### Link to FtB Modpack Issue page

https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2029

**Comment by baileyholl** [comment]
Fixed next version
