### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by pja1982** [baileyholl/Ars-Nouveau#76]
Hi
I am getting a server crash 
Ars Nouveau 1.16.3-1.6.0
Forge 1.16.4-35.0.17
https://pastebin.com/qGBB3mY6

**Comment by baileyholl** [comment]
1.6.1 is out, try that one.

**Comment by SentinelX101** [comment]
Thanks for the update @baileyholl 

However I'm now getting the following error starting a dedicated server which prevents it from starting: https://pastebin.com/VLvMt3sz

It doesn't generate a crash report, so the above is just the log error indicating an unregistered ars_nouveau:mana_siphon which crashes the server at startup.

Ars Nouveau 1.16.3-1.6.1
Forge 1.16.4-35.0.18

**Comment by baileyholl** [comment]
Are you unable to use /fml confirm to get rid of blocks, just as if you had removed a mod?

**Comment by pja1982** [comment]
All good now
Thanks for the fix

**Comment by SentinelX101** [comment]
> Are you unable to use /fml confirm to get rid of blocks, just as if you had removed a mod?

Unfortunately it just seems to crash the server out immediately without asking for the fml confirm as usual, seems like its a conflict with either the Vampirism mod or MrCrayfish's Vehicles mod which are listed as listeners for missing mapper/block events in the log I posted. When those are removed I can start the server fine.

I know this is probably an edge case but if you have a second could you point me towards how to remove the ars_nouveau:mana_siphon manually from the world file safely?
