### ISSUE TITLE
[BUG] Game crash on enchanting mundane belt into levitation belt

### ISSUE THREAD

**Issue by Slam21** [baileyholl/Ars-Nouveau#761]
Repeated multiple times, first time it caused the game to hang and freeze the computer, other times it just closed immediately

**Comment by Slam21** [comment]
heres the crash log [crash-2022-11-26_06.41.09-client.txt](https://github.com/baileyholl/Ars-Nouveau/files/10122943/crash-2022-11-26_06.41.09-client.txt)

**Comment by Slam21** [comment]
i raised the enchanter and the core up by one tile, as i had the core in the floor and that fixed the problem

**Comment by baileyholl** [comment]
1.19 is no longer supported, you will need to update.
