### ISSUE TITLE
Mage blocks not redered during player sleep animations

### ISSUE THREAD

**Issue by LuciusV** [baileyholl/Ars-Nouveau#767]
Being mage, I made my house out of Mageblocks. Then when I went to sleep, I found that they are not rendered.

To reproduce:
1. Make spell with Conjure Mageblock -> Amplify, place several around bed
2. Wait for nighttime and go to bed
3. All mageblocks become invisible during animations.
Mod version 1.18.2-2.7.3, Forge version 40.1.84 
(Direwolf20 1.18 modpack)

**Comment by baileyholl** [comment]
Fixed in 1.19
