### ISSUE TITLE
Cannot craft Enchanter's Sword

### ISSUE THREAD

**Issue by Zaguaizo** [baileyholl/Ars-Nouveau#770]
I'm in 2.8.0 Ars Nouveau (1.18.2), and i can't craft an Enchanter's Sword, with the warning in chat "No recipe found...", but i'm using 2 gold blocks, 1 diamond, 2 source blocks and trying to put the sword in the enchanting apparatus, but i cant put and craft.

**Comment by baileyholl** [comment]
Usually this is from overlapping pedestals. Join the discord for faster help for general issues.
