### ISSUE TITLE
World gen crash due to incompatibility with BYG?

### ISSUE THREAD

**Issue by fixthissitepls** [baileyholl/Ars-Nouveau#771]
I was noticing some crashes while trying to explore some worlds and the game gave me a crash log with the "java.lang.IllegalStateException: Feature order cycle found" which seems to only appears when there is an incompatibility between mods.
I am using the latest version of both mods on 1.19.2 forge.
If this is a BYG problem i am sorry but I posted it here first since ars nouveau was listed first,if that even matters here.
[crash-2022-12-03_17.04.16-server.txt](https://github.com/baileyholl/Ars-Nouveau/files/10146882/crash-2022-12-03_17.04.16-server.txt)

**Comment by Alexthw46** [comment]
Since vanilla doesn't have a standard for it, we ended up with two features order inverted when i rearranged them to fix crashes with tundras. #774 should fix that, the discord have a build with the fix if the fix is not released too soon

**Comment by fixthissitepls** [comment]
Alright thank you for answering.
