### ISSUE TITLE
Mod Interaction - Crash - Alex's Mobs

### ISSUE THREAD

**Issue by MattB70** [baileyholl/Ars-Nouveau#778]
Server crash when some _Ars Nouveau_ interactions involve some _Alex's Mobs_ mobs.

Crash Report: https://gist.github.com/MattB70/52c995fb4b15df3bc5db2615397f859d

Let me know if I should cross report this on Alex's Mobs repo if the issue doesn't appear to be solvable on this end. The was reported by a player on my server.

**Comment by baileyholl** [comment]
This doesnt really seem fixable on our end, multipart entities are being marked as living entities. It is on them to correctly handle bad states. Vanilla provides a multi-part class to help compatibility.
