### ISSUE TITLE
Mob Weight Config

### ISSUE THREAD

**Issue by dannydjdk** [baileyholl/Ars-Nouveau#785]
Version: 1.19.2-3.5.1

It seems there is no longer a config for adjusting the weight of mobs. Can this feature be reintroduced like it was here: https://github.com/baileyholl/Ars-Nouveau/commit/788c921ff8786c685c52945bbfc663b678397a7e ? Or, is there another method for adjusting weights?

**Comment by Alexthw46** [comment]
In 1.19.2 the spawn weights of mobs are configured through forge biome modifiers, which are datapacks.
