### ISSUE TITLE
[1.16.5] Mana Not regenerating, able to use Caster Tomes infinitely

### ISSUE THREAD

**Issue by ErnestoPeroPezzi** [baileyholl/Ars-Nouveau#796]
https://github.com/baileyholl/Ars-Nouveau/issues/345

Seems identical to this issue, except this is on Singleplayer, and no familiars were added. I am on version 1.25.9

I tried reloading world, dying, downgrading ars nouveau, increasing my mana cap through ingame means, nothing changed. 
 
Haven't gotten very far in the mod either, have been using caster tomes and the initial spells available in the novice book

**Comment by ErnestoPeroPezzi** [comment]
After tweaking a bit, I narrowed it down to being caused by Zettai Ars. Removing it seems to have fixed the problem. Which is weird because I played a long time with it and it was working correctly.

**Comment by ZettaSword** [comment]
Hello, i'm creator of Zettai Ars! :3
Can you please send here:
- Your Config of Zettai Ars 
- And also giving me here or in discord( ZettaSword#4448 ) list of your mods

**Comment by ZettaSword** [comment]
Fixed, right now just waiting until it got approved by Curse
