### ISSUE TITLE
crash with ars at random times.

### ISSUE THREAD

**Issue by gravity-share** [baileyholl/Ars-Nouveau#804]
i have 2 logs first is a crash that just happened randomly and the second was a few minutes later when i logged back on and played for around a minute

[crash-2023-01-09_21.45.13-client.txt](https://github.com/baileyholl/Ars-Nouveau/files/10378834/crash-2023-01-09_21.45.13-client.txt)
[crash-2023-01-09_21.59.07-client.txt](https://github.com/baileyholl/Ars-Nouveau/files/10378836/crash-2023-01-09_21.59.07-client.txt)

i dont really know anything about crash logs but the first one seemns to be crashing when rendering ars lights i think. no  idea about the second one

**Comment by baileyholl** [comment]
Are you able to consistently reproduce this? I would test with rubidium removed. Generally rubidium is compatible without issues, but maybe a recent update has changed that. Ill look into it more.
