### ISSUE TITLE
Ars Nouveau and Identity mod

### ISSUE THREAD

**Issue by atran78** [baileyholl/Ars-Nouveau#805]
I'm using Identity and Ars Nouveau mod, and there seems to a bug, where when I press ~ to morph into another mob/creature, all entities inclusing myself become invisible. The game also becomes laggy, dropping fps from my max 500 to around 30. I've tested this a couple of times and it only occurs when using the Identity mod while having ars nouveau in.

**Comment by baileyholl** [comment]
Haven't experienced this, we run identity on all of our test servers. I presume this is fixed or was an older version?
