### ISSUE TITLE
Blink on multi-block mobs

### ISSUE THREAD

**Issue by uhloin** [baileyholl/Ars-Nouveau#809]
If cast blink on mob with warp scroll in off-hand, then some glitch occured. If it is Cave Centipede (from Alex's mobs) and cast to head it is teleported but body stays invincible. May be the same issue for Anaconda and other multi-block mobs.

**Comment by baileyholl** [comment]
This would be something they need to handle gracefully if they are not going to use vanillas provided multi-part entities.
