### ISSUE TITLE
1.18.2 Break Glyph spells don't harvest IntegratedDynamics' IntegratedTerminals' Storage Terminal

### ISSUE THREAD

**Issue by GamingGoombah** [baileyholl/Ars-Nouveau#813]
I haven't much tried with anything else from the mod, however it seems that the break glyph seems to LITERALLY break the terminals, is it meant to act like this? I don't know, but if it can mine stuff and harvest ores, surely it should have the ability to harvest machinery like such.

Just got told to post this here, new user to GH so don't even know if what I'm doing is right, but hopefully someone sees this and is able to respond or fix. Ty.

**Comment by baileyholl** [comment]
Fixed next version
