### ISSUE TITLE
tablet of containment

### ISSUE THREAD

**Issue by Luffy1p** [baileyholl/Ars-Nouveau#815]
Your tablet of containment ritual isn't working. When I activate the ritual all it says is awaiting activation. I have placed the mob I want to capture next to the ritual brazier, but the ritual next starts. I have even put full source jars next to it thinking that will fix it but nothing happens. When I break the ritual brazier I always get my tablet back. I'm not sure if that is supposed to happen. I have watched Direwolf 20 do this ritual multiple times and from what I can tell I'm doing it right.

**Comment by baileyholl** [comment]
Awaiting activation means it is waiting to be started. Right click with an empty hand to start it.

Some rituals can be augmented before being started, that one cannot.
