### ISSUE TITLE
Drygmy production question

### ISSUE THREAD

**Issue by edotenseilove** [baileyholl/Ars-Nouveau#816]
Hello I have a guestion concerning the drygmy loot production.

Is there a limit to the number of unique entities that contribute to the drygmy unique bonus number of items a drygmy produces?

or is it affected by drygmyQuantityCap and having more entities would just increase the variety and not the amount of drops?

**Comment by baileyholl** [comment]
The number of drops per cycle is determined by the number of unique mobs nearby + number of total nearby mobs, capped at that config value.

**Comment by edotenseilove** [comment]
Thank you for the clarification.

Have a great day and thanks for the development of such a great mod.
