### ISSUE TITLE
[1.19.2] Thread of Undying not being applied for every player in multiplayer. (fix included)

### ISSUE THREAD

**Issue by JensenJ** [baileyholl/Ars-Nouveau#819]
Hi there,
On multiplayer the thread of undying seems to work inconsistently. This seems to be caused by the sleepEvent function on line 96 in PerkEvents.java:
https://github.com/baileyholl/Ars-Nouveau/blob/c9687a1e716b4f167eaaddc31fbbd68041cf6cdc/src/main/java/com/hollingsworth/arsnouveau/common/event/PerkEvents.java#L96

I believe this should be `continue` instead of `return` as this prevents any players after the current player in the loop receiving the thread of undying perk if the current player does not possess the thread of undying as the function returns out before going to the next player.

Thanks for the great mod.

**Comment by baileyholl** [comment]
Good catch, thanks!
