### ISSUE TITLE
Crashing when using "Biomes You'll Go" mushrooms with Sylphs

### ISSUE THREAD

**Issue by MuteTiefling** [baileyholl/Ars-Nouveau#82]
Latest: 
[latest.log](https://github.com/baileyholl/Ars-Nouveau/files/5619821/latest.log)

Crash: 
[crash-2020-11-30_20.54.17-server.txt](https://github.com/baileyholl/Ars-Nouveau/files/5619818/crash-2020-11-30_20.54.17-server.txt)

Version: NaturesAura-33.1

Forge: 35.1.0

I was building out a test platform to see how the Sylph handled various modded mushrooms. So I made a 21x21 platform of mycelium and started filling it with BYG mushrooms. Not long after I got going, it crashed.

**Comment by baileyholl** [comment]
Fixed in next version, very strange.

**Comment by MuteTiefling** [comment]
Holy cow, that was fast :D Good job!
