### ISSUE TITLE
Jarseption

### ISSUE THREAD

**Issue by NJM1564** [baileyholl/Ars-Nouveau#828]
I don't know if this is a bug, or how I did it but...
![Screenshot (24409)](https://user-images.githubusercontent.com/4961158/216266766-6eeed8b3-8028-4f70-9fe6-096900a4ae60.png)
![Screenshot (24410)](https://user-images.githubusercontent.com/4961158/216267223-e5085ef9-d4f8-4cbe-9fce-b7a8bda78818.png)
![Screenshot (24411)](https://user-images.githubusercontent.com/4961158/216267230-c3745308-8d91-4772-b526-e71c300b8685.png)

**Comment by baileyholl** [comment]
this is intended
