### ISSUE TITLE
Suggestion for new Mage Armor Tier

### ISSUE THREAD

**Issue by JosephGallagher2001** [baileyholl/Ars-Nouveau#829]
Hello, baileyholl2 and Alexth99, I have a suggestion regarding a new upgrade within the Mage Armor Tier system for Ars Nouveau 1.19.2. 

Now that there has been Netherite armor in the game for almost Three years at this point, I think it is time to incorporate it into the mod's progression in some way. Maybe it could be used to further upgrade the Battlemage set and grant the armor increased knockback resistance, Armor Toughness, and durability. Or it could possibly provide fire resistance. Maybe this new upgrade could even combine the aesthetics of the Netherite pieces into the robes of the Battlemage armor, that might look kinda cool, not gonna lie.

But in the end, everything in Ars Nouveau is up to you guys, but tell me what you think.

**Comment by bigtruckin78** [comment]
I was thinking the same thing. Ars is an awesome mod. Kudos to the mod authors. Netherite gear would be a great addition.
