### ISSUE TITLE
Not enough source nearby

### ISSUE THREAD

**Issue by Maxei22** [baileyholl/Ars-Nouveau#833]
Constant not enough source nearby, tried over 35 source jars and still getting the error when trying to make Allthemodium Alloy equipment.
![2023-02-05_12 53 22](https://user-images.githubusercontent.com/124478723/216799083-4839bd9b-0fe5-4b60-8e8f-863217c1aed3.png)

**Comment by baileyholl** [comment]
That was (or is?) an issue with ATM's recipes.
