### ISSUE TITLE
Glide glyph...

### ISSUE THREAD

**Issue by shoverno2** [baileyholl/Ars-Nouveau#837]
... should been removed?

I found water breath robe talent useful only because there's no more water breath glyph existing.
I can see logic in deleting this glyph from mod.

This works with glide as well. (Tested. I literally turned off that glyph and... well, levitation belt works better anyway, but still thread of elytra feeling more useful now)

Why would anyone spend third level slot for effect that could be simply casted with spell..?

**Comment by Sarenor** [comment]
Because they are to lazy to keep casting or thinking about the spell. That's literally the point of the thread, as far as I'm concerned.
"I can stop thinking now."

**Comment by shoverno2** [comment]
24
minutes
Of glide effect (Full time extend, self spell)
Where effect gona be used about 1-2 minutes
If it's not so far adventure

While glide thread
Needs third level slot

Glide glyph making glide thread useless
Like water breath glyph would make useless water breath thread in third level slot...
Well, unless there's no rival mage
In underwater
Capable of dispel effects from you, yeah...


Maybe, it's not so useless at all
But too much situational

I think
It's hard choice here
But yes
At least it could be disabled if needed
