### ISSUE TITLE
Black Arcane Pedestal

### ISSUE THREAD

**Issue by yap241986** [baileyholl/Ars-Nouveau#838]
I have a missing texture:
<img width="1440" alt="Screenshot 2023-02-05 alle 23 49 07" src="https://user-images.githubusercontent.com/65458792/216850393-f405f4d5-b1d5-48f9-a147-abac87ec07a0.png">

MODS:
<img width="1286" alt="Screenshot 2023-02-05 alle 23 51 46" src="https://user-images.githubusercontent.com/65458792/216850520-eb6dd675-0a03-49cb-910b-fbaffa86777d.png">

is possible that any mod conflict with ars nouveau?

**Comment by baileyholl** [comment]
Likely optifine.

**Comment by yap241986** [comment]
Tried to remove. No.
