### ISSUE TITLE
Textures are switched (1.16.5)

### ISSUE THREAD

**Issue by NicxII** [baileyholl/Ars-Nouveau#839]
![2023-02-06_16_26_47-Minecraft__1 16 5_-_Multiplayer_3rd-party_Server](https://user-images.githubusercontent.com/123950437/217012892-6bbad571-9687-49f7-8980-dbff45ae7a46.png)

So I just relogged onto the server and my textures got switched anyone knows what i should do? I didn't change anything since last time it worked.

**Comment by baileyholl** [comment]
This happens when a clients mods are out of sync with the servers, this is not a mod specific issue. Double check all mods in your client and server.
