### ISSUE TITLE
Add amp cap to regen

### ISSUE THREAD

**Issue by baileyholl** [baileyholl/Ars-Nouveau#84]

**Comment by DerringersMods** [comment]
Suggest tuning duration (both base and extend value) instead of capping it. 16 seconds base plus 16 seconds extend duration if not amplified, shifted right by the amplify count.

**Comment by baileyholl** [comment]
It is effectively a one-off unexpected vanilla behavior. Since it works on health/tick, anything past 6 is 20 hearts a second (while regen 5 is 6.67 hearts a second). With invulnerability frames on hit, you would need to basically be insta-killed. It just isn't reasonable to have that much regen
