### ISSUE TITLE
pMMO compatibility?

### ISSUE THREAD

**Issue by MintTeaTx** [baileyholl/Ars-Nouveau#85]
Heya!  I was curious if you were interested in adding any sort of Project MMO Compatibility?  I'm currently working on a modpack that uses it, and I ADORE your mod.  For the most part, they're fairly compatible- until I started adding XP gains/requirements to crafting glyphs and using the Enchanting Apparatus.  I wouldn't mind footing the hard work for it, just curious if you're interested!

**Comment by baileyholl** [comment]
Sure, what kind of changes are required?

**Comment by MintTeaTx** [comment]
Mostly just event calls that PMMO can pickup/use to work within its level system for determining requirements and using the machines in the mod for gaining relevant exp.

**Comment by baileyholl** [comment]
There is currently a spell cast event and regen/max mana calculation events that you can use, available in the API. Any other specific ones needed?

**Comment by MintTeaTx** [comment]
That's it honestly, thanks!  Wish I would've seen that sooner.
