### ISSUE TITLE
Spell Parchment is still craftable

### ISSUE THREAD

**Issue by MuteTiefling** [baileyholl/Ars-Nouveau#853]
![image](https://user-images.githubusercontent.com/9543430/217524162-c8f87091-c4c5-4801-960d-526dc6837ae9.png)

These two recipes are no longer needed. The top is now obsolete with the new scribing function, and the bottom should probably just return a Blank Parchment instead

**Comment by Aceplante2** [comment]
How are they made now I cant seem to figure it out?
