### ISSUE TITLE
Sky appears completely white when using shaders with 3.11+

### ISSUE THREAD

**Issue by LeCreepyTux** [baileyholl/Ars-Nouveau#861]
![2023-02-12_21 18 20](https://user-images.githubusercontent.com/125232931/218369611-be5003bb-4455-4d62-b3b3-9871ff25aada.png)
![2023-02-12_21 18 30](https://user-images.githubusercontent.com/125232931/218369615-e964845c-6268-4fd0-9192-80ad6a9d80d9.png)
![2023-02-12_21 19 52](https://user-images.githubusercontent.com/125232931/218369617-3efb4448-3f6c-459b-8f60-124dab68af96.png)

When I try to use any shader, the sky appears pure white in the day, and shows a weird line above the horizon during sunrise, sunset, and nighttime.

**Comment by SammySemicolon** [comment]
Which shader is that?
I just tested the same thing using [Complementary](https://www.curseforge.com/minecraft/customization/complementary-shaders/files/4367398) shaders and, apart from the new Skyweave block not rendering as expected, I faced no such issues.

**Comment by SammySemicolon** [comment]
And also, are you running Rubidium & Oculus, or Optifine?

**Comment by maxknl** [comment]
I have the same Issue on the same version

**Comment by maxknl** [comment]
Im using optifine

**Comment by IAmSchilling** [comment]
Same issue here, also optifine

**Comment by lulabyte** [comment]
I am using Optifine and have the exact same issue!

**Comment by SammySemicolon** [comment]
Is there anything in the log file? Optifine is closed source so this is pretty difficult to figure out.

**Comment by tyrannusminusrex** [comment]
Exact same issue here
OptiFine_1.19.2_HD_U_H9
Forge 43.1.1
BSL Shader

@SammySemicolon I have no idea what I'm looking for, but I found two lines which stood out to me:
```
[22Feb2023 02:44:47.116] [modloading-worker-0/DEBUG] [net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber/LOADING]: Auto-subscribing com.hollingsworth.arsnouveau.client.SkyTextureHandler to FORGE
[22Feb2023 02:44:47.117] [modloading-worker-0/DEBUG] [net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber/LOADING]: Auto-subscribing com.hollingsworth.arsnouveau.client.ShaderRegistry to MOD
```

Is this information of any value?

**Comment by SammySemicolon** [comment]
No not really. Those 2 classes handle the sky rendering yeah, but I already know that.

**Comment by Emplexx** [comment]
I have the same issue when using Complementary shaders
(Forge 43.2.0, Optifine 1.19.2 HD U I1)

**Comment by ParadoxNova** [comment]
I too am also having issues with this mod and Complementary Shaders. I'm using Forge 43.2.0, Optifine 1.19.2 HD U I1, and Complementary Shaders 4.7.1. No other mod I'm using has issues and running with just those 3 enabled has no issues, yet when I turn on Ars Nouveau it breaks.

**Comment by SammySemicolon** [comment]
It's definitely a conflcit between ars noveou and optifine. 
With iris/oculus, the end result is the skyweave block not rendering at all.
Really not sure how to go about fixing this- I tried a whole bunch of minor tweaks to the code responsible for this whole array of issues, ranging from tiny changes to ripping crucial parts of the code out- without the know-how on OptiFine, it's hard to do anything. 
Having ars-noveou turn off the skyweave rendering (since it doesn't work anyway) when OptiFine is present and shaders are enabled might be the best course of action.

**Comment by hollowfae** [comment]
I have the same issue with Sildur Vibrant Shaders, Optifine 1.19.2 HD U I1 Forge 43.2.6, the sun and moon both have black squares around them and I can see both at all times through the floor. The issue disappears when it's cloudy/raining. I've tried looking for a sky option in the configs but I'm not very code savvy (my apologies), and could not find any. Is this something we can edit in a file somewhere?
