### ISSUE TITLE
Break spell deletes the Digital Miner

### ISSUE THREAD

**Issue by TiphaineLAURENT** [baileyholl/Ars-Nouveau#87]
**What happened:**
The Digital Miner get deleted from the world without dropping anything, including its content.
I tested both with and without the Extract augment and on every side of it.

**What was expected**
To get back the Digital Miner as an item

Edit: *It seems to be also broken with Wind generator, so maybe all tile entities are broken*

**Comment by baileyholl** [comment]
Is this on 1.16 or 1.15?

**Comment by TiphaineLAURENT** [comment]
This is in the last version of Enigmatica 6 for 1.16.4

**Comment by Ridanisaurus** [comment]
I can confirm that it also voids when used with Vein Mining (FTB Ultimine). 
Mod Version: ars_nouveau-1.16.3-1.6.1

Not sure if this has been fixed in newer version(s) yet.

**Comment by NillerMedDild** [comment]
And causes a crash when breaking some Refined Storage blocks: https://github.com/NillerMedDild/Enigmatica6/issues/609
