### ISSUE TITLE
Seeing only sky after loading into world

### ISSUE THREAD

**Issue by dejrons** [baileyholl/Ars-Nouveau#872]
After installing the mod (and all required) on a server and 2 client PCs I've encountered a problem on one of them that the only thing I see is the sky (with sun on 1 side and moon on the other). I've got exactly the same mod package in all 3 places. Tried with and without my resource packs and on old/new worlds. 

Minecraft 19.2
Forge 43.2.4
Mod version 19.2-3.12.1

**Comment by baileyholl** [comment]
Are you using optifine?

**Comment by dejrons** [comment]
Yes, OptiFine_1.19.2_HD_U_I1 on both computers

**Comment by baileyholl** [comment]
Fixed in next version
