### ISSUE TITLE
Says i dont have Geckolib installed even though i do (Im on 1.19.2)

### ISSUE THREAD

**Issue by Morshew** [baileyholl/Ars-Nouveau#874]

**Comment by baileyholl** [comment]
Cannot assist without a log. Your pre-edited log says you are missing architectuary. 

Failure message: Mod simplyswords requires architectury 5.12.42 or above
Currently, architectury is not installed

Ars Nouveau ships with geckolib in 1.19. If an addon is missing it, you need to update.
