### ISSUE TITLE
Worn Book not working

### ISSUE THREAD

**Issue by WH1T3B0Y75** [baileyholl/Ars-Nouveau#878]
Hello I am using ATM 8 and MC 1.19.2 and went to use the worn book to get some info and this is what come up when I open the book....
![2023-02-24_01 50 48](https://user-images.githubusercontent.com/123500526/221112417-d4f83b6f-4821-4d6d-a5e2-6d69681b7909.png)

**Comment by baileyholl** [comment]
The pack is missing the updated version of Ars Elemental on the server or client. The pack will need to fix their server pack.
