### ISSUE TITLE
[Possible Bug]  Gravity spell gives unobtainable items in survival.

### ISSUE THREAD

**Issue by SavageKiller13** [baileyholl/Ars-Nouveau#88]
Ignore this issue if it is intended.

While playing on a server with a friend using the mod (version 1.16.3-1.8.1) the Gravity spell gives the ability to obtain items that aren't normally obtainable in survival (without using other mods). With the way the spell works it creates the falling entity and then that entity can be dropped onto a torch and obtain that item. 

The way to produce this problem is to get a gravity spell and use it on bedrock (or any other unobtainable item (excluding Tile Entities)) with any caster modifier (like projectile or self). after that place a torch below the block or blocks (if using AOE modifier) and use gravity on that block, It will then fall onto the torch and give the item.

One way I would think about fixing this is to add a check that checks if the block the spell is being used on has a hardness higher than obtainable (like the hardness of bedrock).

**Comment by DerringersMods** [comment]
Well, that's certainly less of a rigmarole than trying to drive a piston through bedrock with TNT. There are some other blocks I'd like to test it out on though.
