### ISSUE TITLE
[Suggestion]Make the Mana Regen & Mana Boost enchantment compatible with armours from other mods.

### ISSUE THREAD

**Issue by tankyap** [baileyholl/Ars-Nouveau#881]
As the title suggests make it work on other modded armours.In this case I want to apply the enchantments on the Mekasuits from the mod [Mekanism](https://www.curseforge.com/minecraft/mc-mods/mekanism) on the anvil and it just won't work.

**Comment by Alexthw46** [comment]
That's not because Ars is not compatible, it's the Mekasuit that is intentionally made to not be enchantable

**Comment by tankyap** [comment]
Wait, what about you can just add an addon  mana upgrades by just add another two [modules](https://wiki.aidancbrady.com/wiki/Modules) from Mekanism about those two enchantments that can also be installed multiple times on a [modification station](https://wiki.aidancbrady.com/wiki/Modification_Station)? So that I can do it in the Mekanism-way,

Or if there is an another addon that adds similar to the title?

**Comment by Alexthw46** [comment]
That's addon territory, since Mekasuit have the modules it's tecnically easy to add. You might ask https://www.curseforge.com/minecraft/mc-mods/ars-industria maybe?

**Comment by tankyap** [comment]
Already commented after one day no response

**Comment by tankyap** [comment]
> I already commented after one day but no response

Oops I take that back,he say yes.
