### ISSUE TITLE
Skyweave?

### ISSUE THREAD

**Issue by robit4** [baileyholl/Ars-Nouveau#882]
Errrm
![2023-03-05_09 49 14](https://user-images.githubusercontent.com/126712560/222978880-91354be1-4731-4cc3-aaf0-7860cea97928.png)
Idk how this happened or how to recreate it though it's from a "invisible" base so can it be found and fixed please?

**Comment by baileyholl** [comment]
Is this with optifine? I cant fix anything without steps to reproduce.

**Comment by robit4** [comment]
> Is this with optifine? I cant fix anything without steps to reproduce.

Didn't you see on the screenshot that it says Idk how this happened or how to recreate it that is because its true
