### ISSUE TITLE
Exchange spell and slabs

### ISSUE THREAD

**Issue by uhloin** [baileyholl/Ars-Nouveau#886]
If slab is placed in the lower half of block and we try to Exchange it with different type slab, the new slab will be placed at upper half of block. For example, if made ceiling from cobblestone slabs and have sandstone slabs in the inventory and cast spell Projectile+Exchange+AOE+AOE+AOE... from below to ceiling then sandstone slabs will be placed a half meter upper then cobblestone slabs were placed.

It's forge version ars_nouveau-1.19.2-3.12.3.jar

**Comment by uhloin** [comment]
Upd: and if cast from above to below then slabs moved from upper half to lower.

**Comment by baileyholl** [comment]
Fixed next version
