### ISSUE TITLE
Bug/Suggestion 'Lightning' Spell Causes loss of mob drops.

### ISSUE THREAD

**Issue by Muramono** [baileyholl/Ars-Nouveau#888]
It seems like when killing a mob with 'lightning' spell the mobs do not drop any items. I am not sure if this is intended or if this is a cause of the lightning effect being seen as 'environmental damage'? I've noticed that other forms of lightning such as a 'thundering' enchantment from another mod does allow for mobs to drop loot.

**Comment by baileyholl** [comment]
This is intended. Ars Elemental adds a focus that lets you preserve drops.
