### ISSUE TITLE
Warden cannot kill drygmy and starbuncle

### ISSUE THREAD

**Issue by Neposis** [baileyholl/Ars-Nouveau#890]
Heya,
A mob from ars nouveau got down into the deep dark and the warden got stuck trying to kill it.
It was a starbuncle. I tried the other mobs and all were good apart from drygmy and whirlysprig. Although the latter was worse because the warden was stuck doing his echo attack the whole time.

Version 1.19.2, mod version 2,12,3, forge version 43.2.6

**Comment by baileyholl** [comment]
This is intended though accidental. Summons can only be killed by players.
