### ISSUE TITLE
Rebalance Needed

### ISSUE THREAD

**Issue by Wakatsu** [baileyholl/Ars-Nouveau#892]
So, lets talk Pull and Fortune glyphs.
The late one is nearly unobtainable. Rabbits spawn only in two vanilla biomes (desert and snowfield) both of which a rather rare and become even more rare in presence of other biome-adding mods. And then even if you happen on one, Rabbit Foot drop rate is abysmal, so you either have to waste your hard-earned diamonds on summoning rabbits, or keep running around desert hunting for an elusive drop.
Compare that to vanilla, that lets you have Fortune III on your tools as soon as you find 5 diamonds (for a pick and enchanting table)

And now even more disbalanced thing - Pull. Not only is it essentially a Silk Touch with extra steps, it's actually better than that as it allows you to pick blocks Silk Touch can't (like Budding Amethyst). Just drop a block you're interested in having on a torch.
And pull is available on tier 1. You guys sure you want to give players such power so early?

**Comment by Jarva** [comment]
Rabbits can be captured in a containment jar for a drygmy to farm it for rabbits foot, additionally an upcoming ritual will allow you to summon passive mobs in the biome you use it in

**Comment by Wakatsu** [comment]
Yeah, but to capture a rabbit you first need to find a rabbit. Which isn't such a small task as you might think it is. I play with Nature Compass, and at times have to travel 8k+ blocks to the NEAREST desert or snowy plains, and this is with me knowing the direction. Imagine somebody playing without biome-finding mods...
That, and the mana price for this augment is ridiculous. An equivalent to an iron pick with Fortune III would deplete your entire manabar after just 4-5 blocks mined. At this rate it's easier to get fully enchanted diamond pick that to pause and wait for mana regen every couple seconds.
Such basic spells are meant to provide better-than-vanilla means for players to play, not the other way around. Take Thaumcraft wands for example - wand with enhanced digging focus was way superior to enchanted diamond pick and thos a pleasure to use. This mod's Break glyph is somewhat on par with iron pick in early game, but loses significantly in convenience later on - you either have to constantly jump back to your spellbook to add \ remove augments, have multiple variants of the same spell clog your slots or invest heavily into mana capacity, otherwise your manabar gets depleted in just a few casts. The only advantage over vanilla picks it has is the possibility of making it into a projectile, but the joke here is that players rarely need to reach something so far out of reach that a projectile would be needed.

**Comment by Jarva** [comment]
You're able to change mana costs and recipes using datapacks or config files.

The unfortunate reality is that when you're playing with biome mods, it is more likely that the vanilla biomes will reside much further away on average. If you're playing with BYG you can check the biomepedia to see if there's any closer biomes that spawn rabbits and then you can use the Ritual of Animal Summoning if you're on a new enough version.

The mana cost can be changed in your config files, however the goal with these augments isn't necessarily to use them for every single block you mine, most simply don't need silk. If you still want to silk everything, then you can pursue various methods to increase your max mana and your mana regen, like learning more glyphs, improving your robes and enchanting them with mana capacity. If you're struggling with spell storage, you can also just craft a second spellbook primarily for mining spell variants.

**Comment by Wakatsu** [comment]
That's the thing - I DON'T use biome mods. Never used them. And I still get 10k+ distances between rare biomes. That is just how minecraft works.
And don't get me started on datapacks! How many people actually know how to make one? Surprise - not many. For most players downloading a mod and droping it in mods folder is as far as it gets.

**Comment by Jarva** [comment]
It would be very rare to have 10k+ distance between you and all Rabbit spawning biomes.

Just consulting the wiki this would include 10k distance from:
Snowy Plains
Ice Spikes
Snowy Slopes
Grove
Snowy Taiga
Old Growth Pine Taiga
Old Growth Spruce Taiga
Taiga
Flower Forest
Meadow
Desert

Any of these biomes can be used to summon a Rabbit.

Datapacks only change the recipes, for all mana costs you can change those in configs. Admittedly datapacks aren't the most well known, but if it's something you want to do, then you can feel free to reach out on the discord and there's people willing to help.
