### ISSUE TITLE
[1.19.2] Ad Astra Dupe bug when using break spell on landing pad

### ISSUE THREAD

**Issue by Saereth** [baileyholl/Ars-Nouveau#896]
Whenever you casts a break spell on the landing pad you get 2 back. Would be nice if there was a blacklist or a tag we could slap on blocks that would make break not work on them. Would help to deal with a few of these edge cases until a proper fix can get put in as well.

**Comment by Jarva** [comment]
`ars_nouveau:no_break_drop` is the block tag for that

**Comment by Saereth** [comment]
> `ars_nouveau:no_break_drop` is the block tag for that

Perfect that'll work ty

**Comment by baileyholl** [comment]
Fixed next version
