### ISSUE TITLE
Atm8 manipulation essence, no reciepe found

### ISSUE THREAD

**Issue by Eternal1992** [baileyholl/Ars-Nouveau#902]
![20230322_205857](https://user-images.githubusercontent.com/128666906/227100325-8f85c726-229f-40c7-b89f-e0a35363a518.jpg)
Tried recrafting everything, with source nearby as well. Will not work at all

**Comment by Eternal1992** [comment]
I can craft magebloom so the setup is valid, but I can't make the bow I will try other recipes as well and update if I find anymore with the same issue

**Comment by baileyholl** [comment]
You need an imbuement chamber.
