### ISSUE TITLE
3.13.0 - Nether server lockup

### ISSUE THREAD

**Issue by Sukasa** [baileyholl/Ars-Nouveau#910]
Forge 43.2.7

Running a somewhat large modpack, still figuring out mods and testing.  There is a server lockup in the Nether, just after initial chunk generation.  Knocks out the server and forces me to use the launcher to hard kill the process, as "save and quit" hangs waiting for the server to start saving chunks.

There is no crash or error noted in the log at the time of the lockup, the server just stops.  Removing Ars Nouveau prevents the lockup.

Game Log (w/ Ars Nouveau): https://paste.ee/p/WDILt

Game log (w/o Ars Nouveau): https://paste.ee/p/Xz9cB

**Comment by Sukasa** [comment]
Grabbed the previous version, 3.12.3.  Issue is NOT present after some creative-mode scooting through the nether

**Comment by baileyholl** [comment]
3.13.1 was released recently and this issue should now be fixed.

**Comment by Sukasa** [comment]
Ah, go figure I probably downloaded the outdated version minutes before the update came out.  My apologies!  I'll test it and close the issue if it's resolved
