### ISSUE TITLE
Weapon KILLS the server!!

### ISSUE THREAD

**Issue by EvilHaggies** [baileyholl/Ars-Nouveau#911]
I’m playing on a multiplayer server that keeps killing the server completely if someone uses the [Enchanter’s Sword] while fighting the Hydra (from twilight forest mod) inscribed with: TOUCH>HARM>AMPLIFY
We are using Ars Nouveau 3.13.0, Forge 43.2.6, and Twilight Forest 4.2.1518.

The Hydra is not the issue because we killed it using other weapons, it’s just something about the Enchanter’s Sword.

**Comment by baileyholl** [comment]
Need a crash log.

**Comment by katubug** [comment]
I think was the one who asked that this be reported, and I didn't provide them with the crash report from the server - that was my bad. I went to grab it just now, but I don't see any that implicate Ars Nouveau - just one to do with Canary.

So I tried to replicate it but on version 3.1.3 it seems to no longer occur.

For now I think we can consider this closed.
