### ISSUE TITLE
[Minor] Server Console Log Spam

### ISSUE THREAD

**Issue by UdoMorgenstern** [baileyholl/Ars-Nouveau#915]
ars_nouveau-1.19.2-3.13.1
Floating point values spamming the server console log

Root cause in EntityFlyingItem.java line 113 (latest commit when checked is sha 9caf9505f566b0b04a562fc18b76b04b0d905a70)
 - System.out.println(BlockUtil.distanceFrom(end, this.position()));

**Comment by baileyholl** [comment]
Ah, thank you.
