### ISSUE TITLE
(feature request) Add ability to disable certain enchantments

### ISSUE THREAD

**Issue by zinerith** [baileyholl/Ars-Nouveau#927]
I only seem to be able to disable the ability to do any enchantments, but there's only a few that need to be disabled. I do love this enchanting system, but the ability to remove some of the things would be incredible. (like removing tiers not accessible with the normal enchantment table like sharpness V for instance)

Also the ability to add custom recipes for new enchantments from other mods would be great for compatibility. That might be a bit more work to add though, and is only a compatibility suggestion and not a base function like removing certain enchantments would be.

**Comment by zinerith** [comment]
Nevermind, you can do that via https://www.curseforge.com/minecraft/mc-mods/kubejs-ars-nouveau

**Comment by baileyholl** [comment]
Its just a datapack with recipes. You can remove the recipes with normal kubejs or that addon.
