### ISSUE TITLE
Whirlisprig.<init> Causes High CPU usage while ending up in java execption

### ISSUE THREAD

**Issue by UdoMorgenstern** [baileyholl/Ars-Nouveau#934]
Forge: 1.19.2 43.2.8
Ars: v3.13.2

so far unknown how to reproduce, but seen reoccurring on our server 

Spark Profiler logs showing issue in Whirlisprig init:
![image](https://user-images.githubusercontent.com/90903255/232086700-3df5307e-901c-4b25-96e7-612ffc91c5ec.png)
com.hollingsworth.arsnouveau.common.entity.Whirlisprig.<init>()7.29%4
Link to full profiler result https://spark.lucko.me/yA4YFwjjrS

**Comment by UdoMorgenstern** [comment]
guessing its related to the Constructers calling:
if(!level.isClientSide)
  MinecraftForge.EVENT_BUS.register(this);

which seems to be only the case for the Whirlisprig (probably for good reason)

**Comment by baileyholl** [comment]
Should be fixed next version (1.19+)
