### ISSUE TITLE
[1.19.2] Item duplication with Quark Crate

### ISSUE THREAD

**Issue by ffuentesm** [baileyholl/Ars-Nouveau#935]
When breaking the quark crate item, while having things inside, with the break glyph, it drops a create while the original one stays in place.
![image](https://user-images.githubusercontent.com/44974827/232170158-7d28bf6f-2016-4a36-8fd0-d6a79d12a9f8.png)
![image](https://user-images.githubusercontent.com/44974827/232170172-dc59d207-804e-4d6f-8672-8b2a771b43d8.png)

**Comment by UdoMorgenstern** [comment]
Duplicate / same root cause as: https://github.com/baileyholl/Ars-Nouveau/issues/906

**Comment by baileyholl** [comment]
Fixed next version
