### ISSUE TITLE
Incompatible with the "(internal)" option in optifine shader 1.19.2

### ISSUE THREAD

**Issue by LrbsX** [baileyholl/Ars-Nouveau#936]
Starting from version 3.11.0, when loading both this mod and the "(internal)" option in the optifine shader, nothing will be visible. (other shaders will be normally except for this one)

**Comment by Jarva** [comment]
We're unable to support or resolve any issues that occur when using Optifine unfortunately. Optifine is a closed source mod that makes many unknown changes to the rendering pipeline.

We recommend using open-source alternatives like Rubidium and Oculus.
