### ISSUE TITLE
[1.19.2, Forge] Crash when using Fluid Pickup on Water

### ISSUE THREAD

**Issue by katubug** [baileyholl/Ars-Nouveau#937]
Hi, I had this reported to me, but I think this is more your field: https://github.com/katubug/CottageWitch119/issues/21

**Comment by Jarva** [comment]
This isn't an Ars Nouveau bug, this is from the addon Starbunclemania

[GitHub](https://github.com/Alexthw46/StarbuncleMania)
[Curseforge](https://www.curseforge.com/minecraft/mc-mods/starbunclemania)

**Comment by katubug** [comment]
Oh derp, you're completely right, sorry!
