### ISSUE TITLE
exchange spell clears backpacks when placed using the spell

### ISSUE THREAD

**Issue by WanderingCat27** [baileyholl/Ars-Nouveau#939]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack

if you exchange a block with a travelers backpack with items in it, the backpack will be placed and the items wiped.

it would be nice on top of fixing this, if there were a blacklisted items config in the exchange glyph config so that if stuff pops up it can at least be fixed temporarily until an actual fix is implemented.

**Comment by baileyholl** [comment]
Fixed next version
