### ISSUE TITLE
Grow Spell gives Botania flowers

### ISSUE THREAD

**Issue by angelnc1989** [baileyholl/Ars-Nouveau#94]
![2020-12-12_23 38 39](https://user-images.githubusercontent.com/5382585/101996489-316e2480-3cd3-11eb-9925-bc01ad98aa0c.png)

**Comment by baileyholl** [comment]
This is due to a datapack or a different mod adding Botania flowers to the bonemeal drop table. The Growth spell mimics bonemeal directly.
