### ISSUE TITLE
Starbuncle has troubles navigating farmland and dirt paths

### ISSUE THREAD

**Issue by AlexiyOrlov** [baileyholl/Ars-Nouveau#943]
Starbuncle will frequently get stuck when walking on farmland or dirt path and spin around in place.

![2023-04-20_21 46 34](https://user-images.githubusercontent.com/5513819/233459972-e8735eef-0abb-44f9-98f9-bb2e7732662a.png)

**Comment by baileyholl** [comment]
What version is this?

**Comment by AlexiyOrlov** [comment]
1.19.2-3.13.2

**Comment by baileyholl** [comment]
Should be fixed on latest now.
