### ISSUE TITLE
[Bug] Place Block Spell Doesn't Work In FTB Claimed Chunks

### ISSUE THREAD

**Issue by Phys09** [baileyholl/Ars-Nouveau#949]
Modpack: All the Mods 8
Mod Version: 3.13.2
Ars Nouveau Extension Mods: Ars Creo, Ars Elemental

Description:
- When using the place block glyph spell inside a claimed chunk using FTB chunks, you will not be able to place blocks.
- Outside of the chunks, you will be able to place blocks.
- "Break Block" spells work as intended inside and outside of claimed chunks, breaking blocks as expected.

**Comment by diantongren** [comment]
same with me, not work when using glyph of grow with timer spell turret in FTB chunks

**Comment by Alexthw46** [comment]
From Discord FAQ:

How do I fix my Spell Turrets in chunk claims?
You must ally the player Ars_Nouveau with UUID 7400926d-1007-4e53-880f-b43e67f2bf29

**Comment by diantongren** [comment]
> From Discord FAQ:
> 
> How do I fix my Spell Turrets in chunk claims? You must ally the player Ars_Nouveau with UUID 7400926d-1007-4e53-880f-b43e67f2bf29

thanks a lot
