### ISSUE TITLE
Crash on break block.

### ISSUE THREAD

**Issue by Vane79** [baileyholl/Ars-Nouveau#953]
When I attempt to use projectile->break->fortune on a block the game crashes. Version is ars_nouveau-1.19.2-3.13.4
[crash-2023-05-01_13.06.22-server.txt](https://github.com/baileyholl/Ars-Nouveau/files/11363826/crash-2023-05-01_13.06.22-server.txt)
Only happens when I hold the pickaxe with fortune enchantment.

If it helps, the pickaxe is made with tetra, but enchanted normally.

**Comment by baileyholl** [comment]
This looks like it is primarily with Tetra disallowing duplicated enchantments, which is valid in Vanilla. I would report it there.
