### ISSUE TITLE
Jar of voiding doesnt work in offhand

### ISSUE THREAD

**Issue by Aceplante2** [baileyholl/Ars-Nouveau#955]
Actually I would prefer if it worked from anywhere in your inventory, but at the very least your offhand? becuase lets say im mining out a large area and dont want stone variants (andesite/diorite/granite)... Uh, they can only be mined with a pick. Am I supposed to mine them from a distance and then tediously switch to the bottle before I pick them up?

The point being, if this is somehow intentional behavior, it is extremely impractical to only work in your mainhand

**Comment by baileyholl** [comment]
It will work in any hotbar slot. Next version will fix it for the offhand.
