### ISSUE TITLE
Config File loading error

### ISSUE THREAD

**Issue by MagicConnoisseur** [baileyholl/Ars-Nouveau#957]
Sorry I'm new to moding but I keep running into a config load error I tried running night config as a work around, but it didn't help I don't know if this is a problem with me or maybe I'm doing something to mess up the mod. My world loads up perfectly fine when I disable Ars, but I would really hate to play without😓 it any help would be great thanks.  😌
[crash-2023-05-02_19.44.27-server.txt](https://github.com/baileyholl/Ars-Nouveau/files/11378620/crash-2023-05-02_19.44.27-server.txt)

**Comment by Alexthw46** [comment]
try to delete the ars configs, maybe they are corrupted somehow

**Comment by MagicConnoisseur** [comment]
Deleting Config files seem to work but also impractical because what if I want to config them later, but nevertheless it did work; So, thank you, Alexthw46. I have no idea as to why the config files would become blank or corrupted.

**Comment by baileyholl** [comment]
Forge configs tend to be corrupted if you use Notepad++, or sometimes when editing them while the game is running.
