### ISSUE TITLE
[1.18.2 - 2.8.0] Bookwyrms cannot use Fell glyph

### ISSUE THREAD

**Issue by mooloor** [baileyholl/Ars-Nouveau#958]
To reproduce:

1. Summon a Bookwyrm from a Lectern.
2. Give it a spell with touch/projectile > fell > anything
3. Set the radius to encompass a tree
4. Watch as it attempts to fell grass, flowers, dirt, stone, and air - basically everything except for trees.

Reproduced in both single- and multi-player, creative and survival.
Has been tested with both modded and vanilla trees.

Judging by the behaviour, it seems to be an issue with the target selection, as it really seems to just target random blocks in all directions.

**Comment by baileyholl** [comment]
Spell turrets are preferred for these jobs, they got reworked in 1.19 because they were ultimately not very useful.
