### ISSUE TITLE
Spell Book copy weapon/tools enchant when you have both in hands

### ISSUE THREAD

**Issue by Urias0** [baileyholl/Ars-Nouveau#959]
Hey so i'm confused about something , i usually have my book in off hand and when i have a fortune pick for exemple or a silk touch shovel , when i use break it get the enchantment effect on the break spell (fortune without the fortune spell for exemple) is it supposed to work like that ? i doesn't really make sense

**Comment by baileyholl** [comment]
This is intended and falls in like with how Minecraft enchantments work. Looting applies when you swap to a sword after firing a bow, for example.
