### ISSUE TITLE
Storage Lectern Stealing Items From Scribe and Alteration Tables

### ISSUE THREAD

**Issue by ehuntzbe** [baileyholl/Ars-Nouveau#961]
Request: Some way to stop the storage lectern from taking items off of an adjacent scribe's table or alteration table.

**Comment by Hithroc** [comment]
@baileyholl Is this issue actually closed? I'm noticing that the commit adds a capability to disable auto-pull for the _scribe's table_ while the issue is talking about auto-pull for the _storage lectern_.

**Comment by baileyholl** [comment]
Oops, misread. You would be right, this isn't fixed yet.
