### ISSUE TITLE
[ATM8] Scribes Table is broken, causes crash

### ISSUE THREAD

**Issue by DizzyDJW** [baileyholl/Ars-Nouveau#963]
https://mclo.gs/g6ThTqk

The Scribes Table is causing a crash when trying to make the Sensitive Glyph, and the world cannot be loaded again until the scribes table is removed using a minecraft world editor.

Please Fix

**Comment by baileyholl** [comment]
A mod with an inventory nearby is not conforming to the forge inventory spec. They need to fix that, and you will need to move that block futher from the scribes table so it isnt pulled from.

`com.smashingmods.alchemylib`
