### ISSUE TITLE
Modifier to make pull and knockback not affect blocks

### ISSUE THREAD

**Issue by Aceplante2** [baileyholl/Ars-Nouveau#967]
Either a new modifier or simply make extract do this? Please?

I want to pull or knockback mobs and not grief my world

**Comment by Alexthw46** [comment]
If you have/can add TooManyGlyphs, it adds filter glyphs that prevent the spell from affecting things

**Comment by Aceplante2** [comment]
Unfortunately I am on a server where they do not want to add any more mods, so that wont be possible. But to prevent future users from experiencing this, I hope this functionality can be added?
