### ISSUE TITLE
Amethyst Golems crash when inserting into Quark Pipe

### ISSUE THREAD

**Issue by chasminimus** [baileyholl/Ars-Nouveau#973]
Looks like if you bind an Amethyst Golem so its home is a Pipe from Quark the game crashes when it tries to insert an item. I think it's because the pipes expect a direction to determine where to send the item initially but the Golem doesn't provide it? Maybe the solution would be to only allow them to insert on pipes with open ends where the inward direction can be deduced.
[Full crash log here](https://mclo.gs/JF2gcCB#L3392), linked to what I figure is the relevant part. Minecraft 1.19.2, Ars Nouveau 3.13.4, Quark 3.4-399

**Comment by baileyholl** [comment]
Please report this to quark oddities.

Forge allows 'direction' to be null, oddities is not respecting a nullable parameter.

**Comment by chasminimus** [comment]
will do, thanks!🫡
