### ISSUE TITLE
Ars noveau and vampirism

### ISSUE THREAD

**Issue by AbraaoLion** [baileyholl/Ars-Nouveau#975]
When I'm bat-like in vampirism I'm able to use the ars noveaus book. I've tested it with other mods that do things similar to the book but I'm unable to use them. Is there any way to resolve this?

**Comment by Alexthw46** [comment]
This is more something that Vampirism should handle, or at least it should be easier for them to do it unless it's the book interaction that is missing an important bit. Crosspost the issue to them.

They can solve it either way by listening to one of Ars event like https://github.com/baileyholl/Ars-Nouveau/blob/10ad284a4a4224379caca6e6e0e96c56dfdc37a3/src/main/java/com/hollingsworth/arsnouveau/api/event/SpellCastEvent.java#L10 and canceling it when conditions are met.
