### ISSUE TITLE
Scribes Table Shader Crash

### ISSUE THREAD

**Issue by SeijiTataki** [baileyholl/Ars-Nouveau#98]
Crash Log: https://pastebin.com/gGpLbixv
Ars Nouveau version: ars_nouveau-1.16.3-1.8.1
Forge Version: (tested on) 1.16.4-forge-35.1.13
Optifine Version: OptiFine_1.16.4_HD_U_G5

Tested on three different shaders (BSL, SEUS, Sildurs) with the same results. Breaking the Scribes Table causes a hard crash ( java.lang.IllegalArgumentException: Cannot get property DirectionProperty{name=facing, clazz=class net.minecraft.util.Direction, values=[north, south, west, east]} as it does not exist in Block{minecraft:air}) as long as any shaders are loaded. Disabling shaders prevents this from happening, and no other block from Ars Nouvea exhibits this behavior.

**Comment by baileyholl** [comment]
This is a known Optifine bug, nothing I can do about this one.
