### ISSUE TITLE
Harm spell deals damage as normal to undead mobs

### ISSUE THREAD

**Issue by Aceplante2** [baileyholl/Ars-Nouveau#984]
I would expect harm to heal undead mobs and heal to damage them, but currently, both damage them, meaning there is no way to heal undead mobs

I am playing forge 1.18.2

**Comment by Alexthw46** [comment]
Not for 1.18 since it was added only in 1.19, but just to let you know, the Ars Elemental addon adds a reverse Heal spell.

No update is planned for 1.18 and lower.
