### ISSUE TITLE
Using Durability from main hand weapon

### ISSUE THREAD

**Issue by AaronGrissom** [baileyholl/Ars-Nouveau#993]
using the amplified break spell in the off-hand while holding any tool uses and breaks the durability of the tool. This came into a major issue when using a tool w/ silk touch which caused the server to crash. See the Reddit post here: https://www.reddit.com/r/CurseForge/comments/13rrtm6/so_i_created_a_mod_pack_for_mc_w_tetra_arsnouveau/

**Comment by baileyholl** [comment]
This is intended, but Tetra should be allowing enchantments to be applied like vanilla does. Checks have been added for the existence of silk touch anyway.
